### ISSUE TITLE
Some way to access additional path options

### ISSUE THREAD

**Issue by hadley** [ropensci/magick#10]
i.e. how can I read just the first page of a pdf? With `convert` I can do `path.pdf[0]`

**Comment by jeroenooms** [comment]
Currently you just need to read the entire file.

```r
pdf <- image_read('https://cran.r-project.org/web/packages/magick/magick.pdf')
pdf[1]
```

I suspect that that is what convert does because stream-parsing various multi-frame formats seems tricky, but I could be mistaken.

**Comment by hadley** [comment]
Yeah, that's what I'm doing.  It just seems like a lot of wasted work when I'm generating a thumbnail of a 30 page pdf

**Comment by jeroenooms** [comment]
I think the parser is quite smart an doesn't do any work with the unused pages until it needs to.

**Comment by jeroenooms** [comment]
The new version of magick now lets magick read the path, so these path options should work.

Fun fact: magic uses zero-based indexing and R uses one-based.
