### ISSUE TITLE
question or feature: how do you extract x-y coordinates

### ISSUE THREAD

**Issue by statsccpr** [ropensci/magick#101]
I searched the issues for keywords: coordinate, points, text

I'm hoping to mimic the below posted example using native imagmagick

http://www.imagemagick.org/discourse-server/viewtopic.php?t=14646

Basically, once you get some binary edge boundary, how do you extract the x-y coordinates of that boundary?

```
library(magick)
?magick

# read in image
logo <- image_read("logo:")

# native imagemagick
# #create binary edge
# # convert heart_mask.gif -edge 1 -threshold 0 heart_mask_edge.gif


# extract coordinates above threshold
# 'text' in native imagemagick

# native imagemagick

# # list coordinates of only white edge pixels
# convert heart_mask_edge.gif txt:- | sed -n 's/^\(.*\):.*white$/\1/p'
# 13,10
# 14,10
# 15,10

# hoping for some kind of 
# magick::txt_coord()
```

I did try the below, but doesn't seem like the direct solution. Am i missing some middle step?
```
image_convert(logo,format = 'txt')

# how do you extract coordinates
# ?alternative to 'text', magick::as.raster()
as.raster(logo)
```

**Comment by jeroen** [comment]
I'm not sure exactly what your image looks like but here is an example. Some notes: 

 - image_quantize() reduces the number of colors to 2, i.e. convert to black/white
 - image_data() converts the image to a raw pixel array
 - the bitmap are raw values between 0 and 0xff (256)

```r
bitmap <- logo %>% 
  image_edge(radius = 1) %>%
  image_convert(type = 'grayscale') %>%
  image_quantize(2, colorspace = 'gray') %>%
  image_negate() %>%
  image_reducenoise(radius = 1) %>%
  image_data(channels = 'gray')
  
which(bitmap < 100, arr.ind = TRUE)
```

**Comment by statsccpr** [comment]
this is perfect, thanks.

my thinking for this use case would address the difficulty posted in the 'native' image magick thread. the last step  using image magick was hard; 'ordering' the coordinates say into a clockwise orientation or something. 

That last step inside R is easy and even easier if the start of the end-to-end process stayed completely inside R via Magick.
