### ISSUE TITLE
Feature suggestion: add "wrap" option in image_annotate for wrapping a long text inside an image

### ISSUE THREAD

**Issue by gsimchoni** [ropensci/magick#103]
(First thank you, this package is a life-changer)

Currently if I'm annotating an image with text which is "too long" compared to the image's width the rest of it is simply cut from the image:

```
X <- array(1, c(100, 100, 1))
image_read(X) %>%
  image_border(geometry = "2x2") %>%
  image_annotate("How much wood could a woodchuck chuck?")
```

It would be nice to have a `wrap` option in `image_annotate` which when `TRUE` would end in:

```
image_read(X) %>%
  image_border(geometry = "2x2") %>%
  image_annotate("How much wood could\na woodchuck chuck?")
```

**Comment by jeroen** [comment]
I don't think imagemagick supports this.
