### ISSUE TITLE
Is it possible to print bold text with image_annotate()?

### ISSUE THREAD

**Issue by smonsays** [ropensci/magick#104]
I would like to print bold text to an image using `image_annotate()`, but I couldn't find anything in the documentation in this direction. Is there currently a way to do this?

**Comment by jeroen** [comment]
It is easier to do this with `image_draw ()` and then use base `text ()`

**Comment by smonsays** [comment]
Yes, that is my workaround as well. Still, I would prefer to use `image_annotate()` as it behaves more consistent and user-friendly when it comes to properly position the text. 

Any chance that this feature could be added? I took a look at the Magick++ STL but couldn't find anything too promising in this regard..

**Comment by jeroen** [comment]
Dupe of https://github.com/ropensci/magick/issues/113
