### ISSUE TITLE
Magick behavior using shinyapps.io

### ISSUE THREAD

**Issue by jhcreed** [ropensci/magick#107]
The density option (and I am guessing others) is not working properly on shinyapps.io, but works fine on my local machine. I am trying to figure out what could be causing this. I know I am not alone with this problem [https://community.rstudio.com/t/question-about-resolution/3166](url). When the issue was reported to rstudio they claimed it had most likely been fixed, but it was still occurring as of 3 days ago [https://github.com/rstudio/shinyapps-package-dependencies/issues/122](url). A MWE is below showing the issue with the density option (the shinyapps.io version can be found at [https://gerkelab.shinyapps.io/bustedMagick/](url)).

```
library(shiny)
library(magick)

ui <- fluidPage(
   
   # Application title
   titlePanel("Magick Density"),
   
   # Sidebar with a slider input for density
   sidebarLayout(
      sidebarPanel(
         sliderInput("density",
                     "Density:",
                     min = 150,
                     max = 2000,
                     value = 1200)
      ),
      
      # Show image as png
      mainPanel(
         imageOutput("ximage")
      )
   )
)

# Define server logic
server <- function(input, output) {
   
   output$ximage <- renderImage({
      image <-  image_convert(image_read(path="https://github.com/jhcreed/bustedMagick/raw/master/pdf/DAGimageDoc.pdf", 
                                         density = paste0(input$density,"x",input$density)),
                              "png")
      tmpfile <- image %>%
         image_write(path=paste0(getwd(),"/image.png"),
                     format = 'png')
      
      list(src = tmpfile)
   })
}

# Run the application 
shinyApp(ui = ui, server = server)
```

**Comment by jeroen** [comment]
Differences in results between your local machine and a server usually have to do with the version of imagemagick that is installed on the server. AFAIK rstudio is now running a more recent version.
