### ISSUE TITLE
bold or italic text

### ISSUE THREAD

**Issue by maelle** [ropensci/magick#113]
This is a feature suggestion 😸 

My suggestion would be to either

* add the possibility to write bold or italic text via `image_annotate`

* document the `image_draw` hack near `image_annotate` in the CRAN vignette 

Thank you!

🎩 ✨ 🐇

**Comment by jeroen** [comment]
🐰🧙
===

**Comment by jzadra** [comment]
I'd love to see this as well.  In specifying the font, it appears that it only accepts the family name even if there are separate fonts for bold or italic within that family?  Or is there a way to specify a bold version of the font if it exists in the system?

For example, specifying `font = "Roboto-Bold"` in `image_annotate()` doesn't seem to work, but it does exist as it's own font: 

``` r
require(tidyverse); extrafont::fonttable() %>% filter(FamilyName == "Roboto")
#> Loading required package: tidyverse
#>   package                  afmfile
#> 1      NA       Roboto-Bold.afm.gz
#> 2      NA Roboto-BoldItalic.afm.gz
#> 3      NA     Roboto-Italic.afm.gz
#> 4      NA    Roboto-Regular.afm.gz
#>                                              fontfile           FullName
#> 1       /Users/u0982704/Library/Fonts/Roboto-Bold.ttf        Roboto Bold
#> 2 /Users/u0982704/Library/Fonts/Roboto-BoldItalic.ttf Roboto Bold Italic
#> 3     /Users/u0982704/Library/Fonts/Roboto-Italic.ttf      Roboto Italic
#> 4    /Users/u0982704/Library/Fonts/Roboto-Regular.ttf             Roboto
#>   FamilyName          FontName  Bold Italic Symbol afmsymfile
#> 1     Roboto       Roboto-Bold  TRUE  FALSE  FALSE         NA
#> 2     Roboto Roboto-BoldItalic  TRUE   TRUE  FALSE         NA
#> 3     Roboto     Roboto-Italic FALSE   TRUE  FALSE         NA
#> 4     Roboto    Roboto-Regular FALSE  FALSE  FALSE         NA
```

<sup>Created on 2018-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
