### ISSUE TITLE
image_graph throws error when called from RStudio notebook

### ISSUE THREAD

**Issue by dhmontgomery** [ropensci/magick#114]
I'm able to run the vignette demo for `image_graph` just fine from the RStudio console: `fig <- image_graph(width = 400, height = 400, res = 96)`

But if I copy and paste that exact line into an RStudio notebook and run it from there (whether running a single line or as part of a chunk), I get the following error: `Error in (function (which = dev.cur())  : Magick device has zero pages`

(If I proceed to run the rest of the demo, after running `dev.off()` from the notebook I get this error: `Error in dev.off() : cannot shut down device 1 (the null device)`. That also runs fine from the console.)

If I run the line from the notebook and get the error, I can then press the up arrow in the console to reload the same line of code that just threw an error and run it again, it runs perfectly!

I'm on RStudio 1.1.423, R 3.4.3 and magick 1.7.

**Comment by jeroen** [comment]
Confirmed. The problem seems that rstudio notebook somehow calls `clip()` on the new device even before creating a canvas with `plot.new()`. Not sure why it does this. The problem disappears when we disable clipping: 

```r
image_graph(width = 400, height = 400, res = 96, clip = FALSE)
```

@kevinushey @jmcphers is it expected that rstudio automatically calls a `clip()` when starting a new device?

**Comment by jeroen** [comment]
Wow it looks like the rstudio notebook viewer completely hijacks the graphics device in order to display the inline images. However it seems to have some problems. 

I have reported this upstream here: https://github.com/rstudio/rstudio/issues/2290

**Comment by jeroen** [comment]
Not much I can do here. This is a feature of rstudio notebooks it seems.
