### ISSUE TITLE
Flood fill not working with IM7

### ISSUE THREAD

**Issue by jeroen** [ropensci/magick#115]
<img width="550" alt="screen shot 2018-03-01 at 11 28 41 am" src="https://user-images.githubusercontent.com/216319/36839970-cc3afc48-1d43-11e8-9d6f-bd151131bb77.png">

@maelle

**Comment by maelle** [comment]
🎩 ✨ 💩 

😉

**Comment by jeroen** [comment]
Fixed upstream in https://github.com/ImageMagick/ImageMagick/issues/1014
