### ISSUE TITLE
Unable to save as png

### ISSUE THREAD

**Issue by coquito77** [ropensci/magick#116]
`library(magick)`

`testPic <- "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/President_Roosevelt_-_Pach_Bros.tif/lossy-page1-165px-President_Roosevelt_-_Pach_Bros.tif.jpg"`

`image <- image_read(testPic)`
`image_info(image)`
`image_convert(image, format = "png", depth = NULL)`

`Error in magick_image_write(image, format, quality) : 
  Magick: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `' @ warning/png.c/MagickPNGWarningHandler/1656`

see  https://stackoverflow.com/questions/45338822/error-using-r-magick-package?noredirect=1#comment85244918_45338822

**Comment by jeroen** [comment]
This is a [bug in imagemagick](https://github.com/ImageMagick/ImageMagick/issues/884). The workaround is to add `strip = TRUE` to `image_read()`:

	library(magick)

	testPic <- "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/President_Roosevelt_-_Pach_Bros.tif/lossy-page1-165px-President_Roosevelt_-_Pach_Bros.tif.jpg"

	image <- image_read(testPic, strip = TRUE)
	image_info(image)
	image_convert(image, format = "png", depth = NULL)

I'll try to ping upstream again to fix this.

**Comment by fmw42** [comment]
It works fine for me from the command line as: 

`convert https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/President_Roosevelt_-_Pach_Bros.tif/lossy-page1-165px-President_Roosevelt_-_Pach_Bros.tif.jpg tmp.png`

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `tmp.png @ warning/png.c/MagickPNGWarningHandler/1665. 

I get a warning only and the file is created. So perhaps your R is misinterpreting the warning as an error. Also it might be a version issue with either ImageMagick or libpng. What are your versions of each? I am using IM 6.9.9.37 & libpng 1.6.34

**Comment by jeroen** [comment]
@dlemstra has just explained to me that Magick++ may automatically raises an exception for warnings  unless we set `quiet(true)`. So  https://github.com/ropensci/magick/commit/289e997896b037517a3cb46400015e1b138555d9 now sets this before writing which should fix the issue.
