### ISSUE TITLE
Long form rasters

### ISSUE THREAD

**Issue by jeroen** [ropensci/magick#117]
@thomasp85 uses `lime:::tidy_raster` to get rasters in long form for plotting them with ggplot2:

```r
tidy_raster <- function(im) {
  raster <- as.raster(im)
  data.frame(x = rep(seq_len(ncol(raster)), nrow(raster)),
             y = rep(seq_len(nrow(raster)), each = ncol(raster)),
             colour = as.vector(raster),
             stringsAsFactors = FALSE)
}
```

This seems useful. Perhaps we can implement an optimized version of this in magick.

**Comment by thomasp85** [comment]
Unless `as.raster` is very inefficient I think my implementation is very close to optimal, but you might avoid some memory allocations by building it directly in C

**Comment by jeroen** [comment]
You are right, there is not much overhead in `data.frame()` here. I've added `image_raster()` now.

**Comment by jeroen** [comment]
You think it would be useful to have a `geom_magick()` which takes an image and plots the raster image?

**Comment by thomasp85** [comment]
Doesn’t really fit well with the grammar as a geom should work with tidy data. You could provide a fortify method (basically this would be image_raster) and/or an annotate_magick function
