### ISSUE TITLE
Allow the creation of a gradient?

### ISSUE THREAD

**Issue by maelle** [ropensci/magick#118]
Would it make sense to have this special case of a blank image, that'd have a gradient rather than an homogeneous background? https://www.imagemagick.org/script/gradient.php

Thank you!

🎩 ✨ 🐇

**Comment by maelle** [comment]
That said I probably do something wrong, I mean I guess it is already possible to do that with the package... My workaround is

```r
gradient_path <- tempfile(fileext = ".png")
 shell(paste0("convert -size 100x100 gradient:none-white ", gradient_path))
 gradient <- magick::image_read(gradient_path)
 file.remove(gradient_path)
```

**Comment by jeroen** [comment]
Thanks! Added it now:

```r
image_blank(600, 400, pseudo_image = "radial-gradient:purple-yellow")
```

**Comment by maelle** [comment]
Fantastic, thank _you_! Will use it soon, maybe with even more gradient options 😍

**Comment by yonicd** [comment]
is it possible use `-define` in the `pseudo_image`?

There are many arguments that can manipulate the gradient characteristics

http://www.imagemagick.org/www/script/gradient.php


```r
> image_blank(200, 200, pseudo_image = "-define gradient:direction=south gradient:#3498db-#db3a34")
Error in magick_image_blank(width, height, color, pseudo_image) : 
  Magick: UnableToOpenBlob `-define gradient:direction=north gradient:#3498db-#db3a34': No such file or directory @ error/blob.c/OpenBlob/2761
```

**Comment by maelle** [comment]
@yonicd maybe it's better if you open a new issue? cc @jeroen
