### ISSUE TITLE
Wrong path for NEWS.pdf

### ISSUE THREAD

**Issue by eddelbuettel** [ropensci/magick#120]
`R CMD check` fails with 

```
> if(require(pdftools))
+ image_read_pdf(R.home('doc/NEWS.pdf'), pages = 1, density = 100)
Loading required package: pdftools
Error in normalizePath(pdf, mustWork = TRUE) :
  path[1]="/usr/lib/R/doc/NEWS.pdf": No such file or directory
Calls: image_read_pdf ... <Anonymous> -> poppler_render_page -> loadfile -> normalizePath
```

because on a Debian system `doc` is below `/usr/share`:  

```
edd@debbuilder:~$ ls /usr/share/R/doc/NEWS.pdf
/usr/share/R/doc/NEWS.pdf
edd@debbuilder:~$
```

I think there is a variable for that directory but I can't recall what it is. 
At compile-time:  `--datadir=/usr/share/R/share`

**Comment by eddelbuettel** [comment]
Here you go:

```
R> R.home(component="share")
[1] "/usr/share/R/share"
R> file.path(R.home(component="share"), "doc", "NEWS.pdf")
[1] "/usr/share/R/share/doc/NEWS.pdf"
R> 
```

**Comment by jeroen** [comment]
Thanks. Why does this not show up on CRAN or travis? 

Your solution does not work for other platforms. Does this work for you?

```r
docdir <- Sys.getenv("R_DOC_DIR", R.home('doc'))
file.exists(file.path(docdir, "NEWS.pdf"))
```

**Comment by jeroen** [comment]
If we look at the source code for `R.home()` you see that it checks for `Sys.getenv("R_DOC_DIR")`. I think in your configuration of R you should be setting this variable if you install documentation to a non standard location.

**Comment by eddelbuettel** [comment]
Look at the [debian/changelog](https://sources.debian.org/src/r-base/3.4.4-1/debian/changelog/) we had this split between `/usr/lib` and `/usr/share` for probably a decade+.  

We don't need `R_DOC_DIR`.  The call `R.home(component="shared")` gives you the location.

**Comment by jeroen** [comment]
The issue is that on almost no other systems the docs are inside shared so your solutions breaks for all other systems but yours. You either need to put it in `file.path(R.home(), "doc")` or set the variable `R_DOC_DIR` to another location. 

The changelog you quote also mentions `R_DOC_DIR`

**Comment by jeroen** [comment]
So `R.home()` seems to only check `R_DOC_DIR` if `component=="doc"`. Can you test if this works?

```r
file.exists(file.path(R.home('doc'), 'NEWS.pdf'))
```

**Comment by eddelbuettel** [comment]
Looks ok:

```r
> file.exists(file.path(R.home('doc'), 'NEWS.pdf'))
[1] TRUE
>
```

**Comment by jeroen** [comment]
OK thanks for reporting. Fixed.
