### ISSUE TITLE
image_resize function not available on Linux (RHEL)

### ISSUE THREAD

**Issue by nasradev** [ropensci/magick#122]
Hi, after running `sudo yum install ImageMagick-c++-devel` and then `library(magick)` in R on my RHEL box, I am able to use most of Magick's functions. However, there is no function `magick::image_resize()`. E.g. if I do the following:
```
image <- image_read(file)
resize_by <- paste(2*image_info(image)$width, "x", sep="")
image <- image_resize(image, resize_by, filter="Hanning")
```
I get 
`Error in image_resize(image, resize_by, filter = "Hanning") : 
  could not find function "image_resize"`
Any ideas what I need to do to get this function to work?
Thanks

**Comment by jeroen** [comment]
That is very strange. Try reinstalling the magick package in R:

```r
install.packages("magick")
```

Perhaps also `update.packages(ask=FALSE)`

**Comment by nasradev** [comment]
Sorry, turns out the RHEL server had a copy of CRAN that contained an older package of Magick (0.4), which does not have the image_resize function.
