### ISSUE TITLE
Add support for magick equivalent of `identify -format "%[*]"`?

### ISSUE THREAD

**Issue by JoshOBrien** [ropensci/magick#123]
As mentioned in its documentation, `magick::image_info()` returns a data.frame with some commonly used image attributes. **magick** does not, however, seem to currently have any function that wraps the functionality of ImageMagick's [`identify`](https://www.imagemagick.org/script/identify.php) program or (more narrowly) an equivalent of a call to `identify -format "%[*]" <image_file>`.

Might it be possible to add a function (perhaps calling it `image_format`) that would return the same information returned by `identify -format`? If someone were able to wrap the relevant C or C++  code, so that the information gets returned as an R character vector, I'd be happy to do all cleanup of those character string needed to get them in an easily usable form.

In case it's of any interest, here's the use case that's motivating this question. I've got a series of drone photos (of grazing exclosures), and would like to annotate the photos with their latitude and longitude. That information is stored in the JPEGs as EXIF attributes, but I'm currently having to use an external utility (Phil Harvey's ExifTool, called by the **exifr** package) to do so. Things would be much cleaner and more efficient (plus faster) if I could access those EXIF attributes using **magick**. (There are additional problems with the **exifr**/ExifTool approach that I'll not elaborate on here.)

**Comment by jeroen** [comment]
`identify` does a lot of things. So you are mostly interested in reading jpeg exif tags?

**Comment by JoshOBrien** [comment]
Absolutely. It does way too many things to try to capture with one function.

All of the attributes I'm interested in do happen to be EXIF tags. I can get them using ImageMagick by typing `identify -format "%[EXIF:*]" file.JPG` at the command line, where the `"%[EXIF:*]"` is essentially a simple regex indicating I want just the attributes that begin with `"EXIF:"`. 

As far as I can see, it wouldn't require any extra programming effort to extract all the tags (rather than the EXIF tags specifically), so that's why I though it'd be better to provide the equivalent of `identify -format "%[*]`, which gets **all** the tags. A user could then easily sort through and extract the tags they're needing on the R side. Does that make sense?

**Comment by jeroen** [comment]
@dlemstra does Magick++ have a function to enumerate all attributes as for  `identify -format "%[*]`? Or is there a way I can get this via C?

I am aware of the Image++ `attribute()` method which allows for getting/setting a single attribute, but I can't find the api for listing them.

**Comment by JoshOBrien** [comment]
If I had to guess, I'd say [this is the C code](https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/identify.c#L1271-L1288) that the command-line `identify` uses to iterate through and record all of a file's properties.

Even if that's not exactly it, the functions that it's using -- `ResetImagePropertyIterator()`, `GetImageProperty()`, `GetNextImageProperty()`, `FormatLocaleFile()`, and `FormatLocaleString()` -- are surely involved!

**Comment by dlemstra** [comment]
@jeroen I use this in Magick.NET:

```C
MAGICK_NET_EXPORT char *MagickImage_FormatExpression(Image *instance, ImageInfo *settings, const char *expression, ExceptionInfo **exception)
{
  char
    *result;

  MAGICK_NET_GET_EXCEPTION;
  result = InterpretImageProperties(settings, instance, expression, exceptionInfo);
  MAGICK_NET_SET_EXCEPTION;
  return result;
}
```

**Comment by jeroen** [comment]
@dlemstra we're not interested in formatting but in listing all of the attributes from the image

@JoshOBrien https://github.com/ropensci/magick/commit/4567c6f6f10ceba1c641a1521733be1ac7ba6bf6 adds an implementation based on your suggestion. Can you test this?

**Comment by jeroen** [comment]
It looks as if imagemagick only reads exif tags that are strings though. 


```r
> exiv::read_exif("~/Downloads/abe.tif")
                               exif_key     exif_val exif_type
1             Exif.Image.NewSubfileType            0      Long
2                 Exif.Image.ImageWidth          256     Short
3                Exif.Image.ImageLength          256     Short
4              Exif.Image.BitsPerSample            8     Short
5  Exif.Image.PhotometricInterpretation            0     Short
6           Exif.Image.ImageDescription ImageJ=1.23y     Ascii
7               Exif.Image.StripOffsets          768      Long
8            Exif.Image.SamplesPerPixel            1     Short
9               Exif.Image.RowsPerStrip          256     Short
10           Exif.Image.StripByteCounts        65536      Long
> magick::image_attributes(magick::image_read("~/Downloads/abe.tif"))
             property                     value
1             comment              ImageJ=1.23y
2         date:create 2017-12-30T22:11:17+01:00
3         date:modify 2017-12-30T22:10:52+01:00
4          tiff:alpha               unspecified
5         tiff:endian                       msb
6    tiff:photometric              min-is-white
7 tiff:rows-per-strip                        32
```

**Comment by JoshOBrien** [comment]
Hmm. I'm on Windows, so can't compare the results with **exiv** (and of course don't have your "abe.tif" image). But on the JPEGs I'm looking at (the drone photos), your `magick::image_attributes()` gives me everything that I get from a command line call to `identify -format "%[*]`, including more than 60 exif attributes.

(In fact, probably because you're linking to a more recent ImageMagick, your function gives me three more exif attributes than I get at the command line: `exif:thumbnail:ResolutionUnit`, `exif:thumbnail:XResolution`, and `exif:thumbnail:YResolution`.)

I'll continue to test on some other files (including other image formats), but on the one file I've checked, this works great!

Would you like me to send you one of the drone images, so you can test using it?

**Comment by JoshOBrien** [comment]
OK, now I understand. `magick::image_attributes()` isn't a substitute for a full-featured EXIF reader. But it does capture all the same attributes that ImageMagick's `identify -format`  does.

Thank you so much for adding this functionality!

**Comment by JoshOBrien** [comment]
FTR, looking closer, I see that `magick::image_attributes()` also misses many of the exif attributes in my JPEGs (presumably because they are not string-valued). So its not just a matter of the driver for TIFF files.

**Comment by jeroen** [comment]
Perhaps imagemagick only reads a set of predefined attributes that it knows how to handle?

**Comment by JoshOBrien** [comment]
Yep. Good guess. Looks like that is exactly the case. 

At least for my image, the 65 EXIF tags that ImageMagick picks up are all included among the 270 tags enumerated in [this section](https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/property.c#L934-L1208) of ImageMagick's `property.c` file.

As can be seen [here](https://sno.phy.queensu.ca/~phil/exiftool/TagNames/index.html), utilities like ExifTool end up having to do a **lot** more work to keep up with all of the information that various manufacturers end up saving using the EXIF standard. In fact, about half of the drone-specific tags that ExifTool gets for me appear to actually be XMP tags (as documented [here](https://sno.phy.queensu.ca/~phil/exiftool/TagNames/DJI.html)).

**Comment by jeroen** [comment]
Looks like this is an issue in imagemagick that is out of our control in the bindings.
