### ISSUE TITLE
image_convolution how to provide kernel correctly byrow=FALSE?

### ISSUE THREAD

**Issue by jwijffels** [ropensci/magick#126]
I'm trying to see if the kernel passed on to image_convolution does what I expect it to do using the Sobel kernel which looks like 
![knipsel](https://user-images.githubusercontent.com/1710810/39630701-699278c4-4fb0-11e8-9561-ed9d1bbd8805.PNG)

The below shows that i1 is the same as i2, while I would have expected that i1 is the same as i3. Is this an error in magick_image_convolve_matrix when you execute matrix.begin?

```
library(magick)
img <- logo
kernel <- c(1, 0, -1,
            2, 0, -2,
            1, 0, -1)
i1 <- image_convolve(img, kernel = "Sobel")
i2 <- image_convolve(img, kernel = matrix(kernel, nrow = 3, ncol = 3, byrow=FALSE))
i3 <- image_convolve(img, kernel = matrix(kernel, nrow = 3, ncol = 3, byrow=TRUE))
i1
i2
i3
```

**Comment by jeroen** [comment]
Could be a bug. Do you think we should transpose the matrix before feeding it to ImageMagick?

**Comment by jeroen** [comment]
Maybe I assumed the kernel matrix is always square. Can you propose a PR to fix it?

**Comment by jwijffels** [comment]
The simplest solution from my side would be to add this code in the image_convolve R function.

```
if(is.matrix(kernel)){
  kernel <- sprintf("%sx%s: %s", 
                    ncol(kernel), nrow(kernel), 
                    paste(apply(kernel, MARGIN=1, paste, collapse = " "), collapse = "\n"))
}
```

**Comment by jwijffels** [comment]
@jeroen I'm wondering where I can find the correct link to the documentation of the C/C++ you are wrapping. Is it https://www.imagemagick.org/Magick++/Image++.html or is it https://legacy.imagemagick.org/Magick++/Image++.html or is it somewhere else?

**Comment by jeroen** [comment]
It looks like imagemagick always assume a square kernel because it has a single `order` parameter:

> The order_ parameter represents the number of columns and rows in the filter kernel, and kernel_ is a two-dimensional array of doubles representing the convolution kernel to apply.

**Comment by jwijffels** [comment]
I don't think imagemagick always requires a square kernel. 
```
img <- image_read("https://www.imagemagick.org/Usage/convolve/test_mag.gif")
i <- image_convolve(img, kernel = 
'4x5:  0 -1  0  0
      -1 +1 -1  0
      -1 +1 -1  0
      -1 +1 +1 -1
      0 -1 -1  0 ', bias = "50%")
```
But the fix is fine if users want to give in a non-squared kernel, they can still use the example above.
Many thanks for the fix!

**Comment by jeroen** [comment]
Right, I'll add this example to the manual page. I don't understand how to specify a non-square matrix via the Magick C++ API.
