### ISSUE TITLE
it would be nice to have a wrapper 

### ISSUE THREAD

**Issue by jwijffels** [ropensci/magick#130]
around the process method as it allows to `"Execute the named process module, passing any arguments via an argument vector, with argc_ specifying the number of arguments in the vector, and argv_ passing the address of an array of null-terminated C strings which constitute the argument vector. An exception is thrown if the requested process module does not exist, fails to load, or fails during execution."`
In this way we can use other functionalities from magick which aren't wrapped already in magick.

E.g. you can easily apply a convolution but the morphology operations (taking the min or max of a group of pixels in the neighbourhood to erode or dilate an image or other things like opening/closing/blacktophat/whitetophat which are easy in imagemagick can not be done using the R package. I was also thinking about all the fx expressions that imagemagick can apply on images so that you can easily add/subtract/... to images.

**Comment by jeroen** [comment]
I can try but I'm not sure this does what you expect. Most of the argument parsing is implemented in the imagemagick command utilities themselves, so I don't think this is available from the library.

**Comment by jeroen** [comment]
Thanks @jwijffels I am very open to suggestions. I'm not a domain expert so please open topics for features that are currently missing bindings.

I just added a binding for local adaptive tresholding, does this work for you? https://github.com/ropensci/magick/issues/40

**Comment by jeroen** [comment]
If you make a list of features we can meet in Brussels or Utrecht some day and we can implement them together so you can verify it does what it is supposed to do :) I don't really know what to look for after a morphology.

**Comment by jwijffels** [comment]
Yes, saw it, great. But maybe also black/white thresholding, the auto thresholding via otsu
https://www.imagemagick.org/script/command-line-options.php#black-threshold
https://www.imagemagick.org/script/command-line-options.php#white-threshold
https://www.imagemagick.org/script/command-line-options.php#auto-threshold
https://www.imagemagick.org/script/command-line-options.php#threshold
About morphology: it's pretty well explained at https://www.imagemagick.org/Usage/morphology/#difference
Where is the exact location of the C++ docs you use so I can find out what is exactly possible. I'm not 100% sure I use the correct C++ docs.

**Comment by jwijffels** [comment]
I don't need it directly but I would be happy to add that to magick so that the same course next year will probably be even more easy regarding installation & features in 1 place.

**Comment by jeroen** [comment]
The imagemagick c++ docs are a bit incomplete and dated. I usually rely on the api headers.

**Comment by jwijffels** [comment]
I think I found the correct headers. The process method is probably not what I thought that it was. I'm closing the issue and will try to add the morphology functionality and fx functionality as pull requests later.

**Comment by dmi3kno** [comment]
OTSU thresholding is still a useful thing to have:
https://www.imagemagick.org/include/api/threshold.php#AutoThresholdImage

**Comment by jeroen** [comment]
Can you open a new issue so that it doesn't get lost?

**Comment by jwijffels** [comment]
I think otsu thresholding is online part of imagemagick 7
