### ISSUE TITLE
Unable to read GeoTIFF files

### ISSUE THREAD

**Issue by AndyPL22** [ropensci/magick#134]
It does not seem possible to read GeoTIFF files.

```
image_read(RGBFile)

Error in magick_image_readpath(path, density, depth, strip) : 
  Magick: Unknown field with tag 34737 (0x87b1) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/912
```

I've found that the `readTIFF()` function in the `tiff` package can be used as a workaround. It actually gives warnings about the same unknown tags but does not throw an error. However, this workaround is very slow when working with large files (> 1 GB)

`image_read(tiff::readTIFF(RGBFile,  as.is = TRUE, native = TRUE))`

Would it be possible to allow `image_read()` to read GeoTIFFs?

**Comment by jeroen** [comment]
Can you include an example image so I can reproduce the problem?

**Comment by jeroen** [comment]
Also please include your `sessionInfo()`.

**Comment by jeroen** [comment]
I have pushed a fix. To try it, run this in a clean R session (make sure magick is not loaded in any R process):

```r
devtools::install_github("ropensci/magick")
```

**Comment by AndyPL22** [comment]
Works a treat. Thanks!
