### ISSUE TITLE
feature request: morphology

### ISSUE THREAD

**Issue by jwijffels** [ropensci/magick#136]
Currently the package does convolutions which basically look around the pixel and do an operation but the package lacks doing morphology operations (which basically take a min/max around a pixel or something more advanced like closing/opening).
Just putting this here to be able to start a discussion or refer to that later on when doing a pull request.

**Comment by dmi3kno** [comment]
Want to support this feature request. More on morphology in ImageMagick [here](http://www.imagemagick.org/Usage/morphology/).

**Comment by jwijffels** [comment]
Looks great to me. I had this implemented locally exactly the same way. While you are at it, let me add some more code which I had locally to the other feature requests.

**Comment by dmi3kno** [comment]
This is so awesome!
I always wanted to do paragraph detection. 
Original image:
![preview](https://user-images.githubusercontent.com/13419011/46260346-f235cd80-c4e4-11e8-801a-61865e570a69.jpeg)
```r
library(magick)
pdfurl <- "http://www.businesswithlatinamerica.com/images/finalised%20articles/indias%20energy%20quest%20in%20latin%20ameirca.jpg"
img <- image_read(pdfurl) %>% 
  image_convert(format="png", type="Grayscale") %>% 
  image_negate() %>% 
  image_lat(geometry = "50x50+10%") %>% 
  image_negate() %>% 
  image_deskew()

image_composite(img,
 img %>%
  image_negate() %>% 
  image_morphology(method="Dilate", kernel="Rectangle:10x15") %>% 
  image_edge(radius = 2) %>% 
  image_hough_draw(geom="10x10+400", bg="transparent")
)
```
Becomes:
![preview1](https://user-images.githubusercontent.com/13419011/46260354-0da0d880-c4e5-11e8-9d9a-a24462ead6a8.png)

**Comment by jeroen** [comment]
Thanks for the suggestions. Feel free to open more issues about things we could add in future versions.

**Comment by jeroen** [comment]
Would you be able to help one or more real-world use cases to demo these new features?

**Comment by jwijffels** [comment]
I think we can set up something like counting stars based on a picture from outer space.

**Comment by jeroen** [comment]
That would be really cool.

**Comment by jwijffels** [comment]
Maybe something like this:

```
library(magick)
img <- "https://www.microscopyu.com/assets/gallery-images/uv1a-bovine.jpg"
img <- image_read(img)
img
img %>% 
  image_channel(channel = "blue") %>%
  image_morphology(method = "OpenIntensity", kernel = "ConvexHull", iterations = 10) %>%
  image_morphology(method = "Dilate", kernel = "Disk", iterations = 1) %>%
  image_morphology(method = "Erode", kernel = "Disk", iterations = 1) %>%
  image_fuzzycmeans() %>%
  image_threshold(type = "white") %>%
  image_connect() %>% 
  image_split(keep_color = FALSE)

```

**Comment by jeroen** [comment]
Thanks! What does this image contain?

**Comment by jwijffels** [comment]
fluorescence intensity at bovine pulmonary cells
More details: https://www.microscopyu.com/gallery-images/bovine-pulmonary-artery-cell-nuclei-3
