### ISSUE TITLE
feature request: fx

### ISSUE THREAD

**Issue by jwijffels** [ropensci/magick#138]
The fx functionality in imagemagick would be nice to wrap around.
A use case for this is e.g. to compute the image gradient (https://en.wikipedia.org/wiki/Image_gradient) with fx you can more easily do this after you computed the gradient in the x/y direction using image_convolve 
 Just putting this here to be able to start a discussion or refer to that later on when doing a pull request.

**Comment by jwijffels** [comment]
FYI. I had this locally:

```
#' @export
#' @rdname convolutions
#' @param expression string with an fx expression (\url{https://www.imagemagick.org/script/fx.php})
#' @param channel a value of [channel_types()] specifying on which channel(s) to execute the fx expression
#' @examples
#' if(magick_config()$version > "6.8.8"){
#'   img <- image_convert(logo, colorspace = "Gray")
#'   image_fx(img, expression = "pow(p, 0.5)")
#'   image_fx(img, expression = "random()")
#'   gradient_x <- image_convolve(test, kernel = "Prewitt")
#'   gradient_y <- image_convolve(test, kernel = "Prewitt:90")
#'   gradient <- c(image_fx(gradient_x, expression = "p^2"),
#'                 image_fx(gradient_y, expression = "p^2"))
#'   gradient <- image_flatten(gradient, operator = "Plus")
#'   gradient <- image_fx(gradient, expression = "sqrt(p)")
#'   gradient
#' }
image_fx <- function(image, expression = "p", channel = NULL){
  assert_image(image)
  expression <- as.character(expression)
  channel <- as.character(channel)
  magick_image_fx(image, expression, channel)
}


// [[Rcpp::export]]
XPtrImage magick_image_fx( XPtrImage input, const std::string expression, Rcpp::CharacterVector channel){
  XPtrImage output = copy(input);
  // TODO: version of imagemagick needed
  if(channel.length()){
    Magick::ChannelType chan = Channel(std::string(channel.at(0)).c_str());
    for(size_t i = 0; i < output->size(); i++)
      output->at(i).fx(expression, chan);
  } else {
    for(size_t i = 0; i < output->size(); i++)
      output->at(i).fx(expression);
  }
  return output;
}

```

**Comment by jeroen** [comment]
Thanks for the suggestion. This function has been added to the package. Let me know if this works for you!

**Comment by jeroen** [comment]
What sort of ops do you mean? Can you give an example?

**Comment by jwijffels** [comment]
I mean something like subtracting two images. Or doing something simple like seeing whether the pixel intensity is == 1 or < 1. Or seeing if one picture has smaller intensities than the other picture. `<<, >>, <, <=, >, >=, ==, !=` where the left/right hand side can be an image or a number.

**Comment by jeroen** [comment]
This is on CRAN now.

**Comment by dmi3kno** [comment]
As recently raised in #244, `image_fx()` currently works only with single image. In some cases, second image may have to be provided to enable `fx` operation comparing/copying data between images. Could we please, add `image2` as a *last*, *optional* argument? that is 
```r
image_fx(image, expression = "p", channel = NULL, image2=NULL)
```

**Comment by jeroen** [comment]
Yes, can you open a new issue please so that it doesn't get lost?
