### ISSUE TITLE
feature request: edges/lines

### ISSUE THREAD

**Issue by jwijffels** [ropensci/magick#139]
The imagemagick library provides a canny edge detector and hough line transformations, why not wrap this also.
 Just putting this here to be able to start a discussion or refer to that later on when doing a pull request.

**Comment by jeroen** [comment]
Thank you for the request. Are you aware of `image_edge()` ?

**Comment by dmi3kno** [comment]
Hough Line are described [here](https://www.imagemagick.org/discourse-server/viewtopic.php?t=25476). The text export is pretty interesting, not sure how it will play with the pipe. Maybe we could wrap it into `img %>% image_hough2csv() %>% write_csv()`

**Comment by jwijffels** [comment]
FYI. Some code I had locally:

```
#include "magick_types.h"

// [[Rcpp::export]]
XPtrImage magick_image_canny( XPtrImage input,
                              const double radius=0.0, const double sigma=1.0,
                              const double lower=0.1, const double upper=0.3){
  // https://github.com/ImageMagick/ImageMagick6/commit/acfd403ca7ca38c3a06bdd81ca5b4e41b12e11bf
  XPtrImage output = copy(input);
  for(size_t i = 0; i < output->size(); i++)
      output->at(i).cannyEdge(radius, sigma, lower, upper);
  return output;
}


// [[Rcpp::export]]
XPtrImage magick_image_hough( XPtrImage input,
                              const size_t width, const size_t height,
                              const size_t threshold=40){
  // https://github.com/ImageMagick/ImageMagick6/commit/8dc68ae87b9ff7fa7ba0bec01231a2a3910d4015
  XPtrImage output = copy(input);
  for(size_t i = 0; i < output->size(); i++)
    output->at(i).houghLine(width, height, threshold);
  return output;
}

```

**Comment by jeroen** [comment]
I was just looking into this, but I couldn't reproduce the [example from the IM website](http://www.imagemagick.org/Usage/transform/#hough). If I do:

```r
test <- image_read('http://www.imagemagick.org/Usage/transform/shape_rectangle.gif')
test %>% image_hough(5, 5, 20)
```

The output seems empty?

**Comment by jwijffels** [comment]
I'll look into some code which I had next week.

**Comment by dmi3kno** [comment]
Jeroen,
Isn't hough supposed to run on edges and not on filled shapes? Did you try:
```r
test <- image_read('http://www.imagemagick.org/Usage/transform/rectangle.gif')
test %>% image_hough(5, 5, 20)
```

**Comment by jeroen** [comment]
@dmi3kno thanks I think you're right! The image still looks blank in the preview, but if I convert it to mvg/svg then I see indeed the lines!

**Comment by dmi3kno** [comment]
The whole point of lines is in text output. I can imagine plotting them over image(as ImageMagick examples show), but they are often used as features for CV tasks. Text (list? data.frame?) output is what’s most useful for hough. 

Maybe it should output svg, assuming it then can be parsed into a dataframe.

**Comment by jeroen** [comment]
Right I was trying to reproduce this image from the manual:

![](http://www.imagemagick.org/Usage/transform/rectangle_lines.gif)

**Comment by jeroen** [comment]
OK I have added `image_hough_draw()` and `image_hough_txt()` in the dev version. Would you mind testing this?

**Comment by jeroen** [comment]
I have now also added `image_canny()` as suggested by Jan above.

**Comment by dmi3kno** [comment]
Perfect!
```r
#remotes::install_github("ropensci/magick")
library(magick)
test <- image_read('http://www.kgs.ku.edu/Publications/OFR/1982/OFR82_2/gifs/fig4.gif')
test %>% image_composite(
  test %>% image_negate() %>% 
    image_hough_draw(geom = "10x10+300", bg="transparent")
)
```
![well_log](https://user-images.githubusercontent.com/13419011/46258230-3ade8e00-c4c7-11e8-9b38-92151a67ba66.gif)
![well_log_w_hough](https://user-images.githubusercontent.com/13419011/46258229-3ade8e00-c4c7-11e8-8cbe-a3f326aa6074.gif)

**Comment by jeroen** [comment]
Very cool. Can you explain why the negation makes the hough detection so much better?

**Comment by jeroen** [comment]
Looks like `image_canny()` also works instead of `image_negate()` (and works perhaps more generally)?

**Comment by dmi3kno** [comment]
I think it has something to do with identification of mask and/or background image. In `magick` background is typically black and created masks are also shown as black, not white. I also believe canny filter is doing `image_negate() %>% image_background('black') %>% image_canny_edge_detection()` in a sense it performs negation before detecting edges.

Same rule applies for `image_lat()`. It works MUCH better on negated images.

> "Negation is extremely common in image processing, particularly when dealing with gray-scale images as a step before or after other processing options. As such I recommend you play with it and keep it in mind whenever you are doing anything, as working with negated images can solve some otherwise difficult problems" --[ImageMagick](http://www.imagemagick.org/Usage/color_mods/#negate)

**Comment by dmi3kno** [comment]
I have a little concern related to default geometry (in both `image_hough_draw` and `image_hough_txt`):

1. Shouldn't the argument be called "geometry" instead of "geom" (keeping argument naming consistency with other function, like `image_crop` and `image_lat`)

2. The default value of "5x5+20" is too small for any reasonable sized picture. I think default behaviour should be that ignorant user should be able to try the function without having to fry his computer or having to terminate r session because it just goes into infinite loop. Better default value could be: 0.05*img_height x 0.05*img_width + 0.2*min(img_height, img_width).

This way for picture of 500x500, the geometry will be "25x25+100", and "5x5+20" would be good for image of 100x100 (which is what this one you tested the function on is):
![rectangle_lines](https://user-images.githubusercontent.com/13419011/46277182-b5102080-c562-11e8-8af9-d7b22574e358.gif)
This way geometry will capture any lines that are at least 20% of the image size (run at least across 20% of the image).

Current default is rarely useful (except for toy examples).

**Comment by jeroen** [comment]
@dmi3kno I have adopted your suggestions, can you test this?

**Comment by dmi3kno** [comment]
Yep. Not bad, I think.
![preview2](https://user-images.githubusercontent.com/13419011/46291673-62992900-c58f-11e8-8503-f1608ba67b97.jpeg)

**Comment by jeroen** [comment]
@jwijffels can you check if anything is missing, and close the issue if everything seems OK?

**Comment by dmi3kno** [comment]
1. I am less sure about the usefulness of `overlay` argument. In most circumstances, `image_hough_draw` will be preceded by `image_negate`, so it would show lines on inverted image. Might be OK as a "quick and dirty" test. I will let other people to chip in on this one.

2. I like the default of `background="transparent"`. Thank you!

**Comment by jwijffels** [comment]
For me the implemented functionality is more than sufficient. @dmi3kno , nice example of line detection by the way.

**Comment by jeroen** [comment]
This is on CRAN now.
