### ISSUE TITLE
Altering specific elements

### ISSUE THREAD

**Issue by BITREG1** [ropensci/magick#140]
It feels like something I've always wanted from R is tantalisingly close.

I saw another thread here about changing object colour but didn't think it was quite right for my use scenario.

Is it possible to change the fill colour (or other attributes) of specific elements within the SVG? For instance, let's say I had an SVG graphic of a thermometer, it would be amazing if I could specifically select the mercury in the thermometer (using its element ID say), change the fill colour of the mercury based on some temperature data and then save the SVG back out as a new file.

Is this possible and if so will it be implemented at any point in the near future?

**Comment by jeroen** [comment]
If you want to manipulate svg files it is better to use the xml2 package.
