### ISSUE TITLE
replace "white" with "red" for all pixel

### ISSUE THREAD

**Issue by kongdd** [ropensci/magick#142]
Can I change a line color from "white" with "red" in magick?
Or replace all the "white" pixel with "red"?

**Comment by jeroen** [comment]
Use `image_transparent` to set target pixels to alpha, end then fill them in with `image_background()`:

```r
image_background(image_transparent(logo, 'red', fuzz = 20), 'green')
```

**Comment by kongdd** [comment]
Thanks very much!
