### ISSUE TITLE
A more silent print

### ISSUE THREAD

**Issue by thomasp85** [ropensci/magick#143]
When creating animations with gganimate the frame number is often in the 100's and the default print method for `magick-image` is to print the info for all frames, while users are more interested in just seeing the animation in the viewer.

Can we provide a way to specify that `info = FALSE` for this particular object, e.g. by adding a subclass with a slightly different print method, or alternatively default to only printing the first 6 frames?

**Comment by jeroen** [comment]
Sure that makes sense.

**Comment by jeroen** [comment]
Can we accomplish this by making the info data a tibble?

**Comment by thomasp85** [comment]
That might work, but could break code I guess - don’t you define custom [ and [[ methods for your magick-image class?

**Comment by jeroen** [comment]
Yes but the printed info is not an image object, it's just a data frame.

**Comment by teng-gao** [comment]
what's the resolution for this?

**Comment by teng-gao** [comment]
print(img, info = FALSE)

**Comment by brontosorus32** [comment]
I just discovered this feature and it's very helpful!

Are there any other custom options for print.magick-image? I didn't find details on print() methods in the documentation.
