### ISSUE TITLE
Optimized gif color pallette

### ISSUE THREAD

**Issue by stephenbfroehlich** [ropensci/magick#147]
For image_animate and other gif outputs, is it possible to optimize the gif color palette to minimize dithering?  Very few charts have anywhere near 256 colors to start with.

**Comment by jeroen** [comment]
I don't think you can control that from imagemagick. However the latest development version of magick adds a function `image_write_gif()` which uses the [gifski](https://cran.r-project.org/web/packages/gifski/index.html) package to encode the gif. This should give better compression and quality.

**Comment by gaborcsardi** [comment]
Yeah, this would be great, actually. There is `image_map()` that can remap colors, but I can't seem to make it work for an animated gif, before or after creating an animation.
