### ISSUE TITLE
installation on RHEL

### ISSUE THREAD

**Issue by ringprince** [ropensci/magick#148]
This is more a question about RHEL than magick.  But my RHEL box (7.5 - Maipo) complains about not having `ImageMagick-c++-devel`

    # yum install ImageMagick-c++-devel
    No package ImageMagick-c++-devel available. 

I am not well versed with RHEL.  Do I miss a repository to be enabled?  How do I find out which one?

**Comment by jeroen** [comment]
See https://twitter.com/spotrh/status/984455124796964864

**Comment by ringprince** [comment]
Thanks!  Works now.
