### ISSUE TITLE
Support for large images

### ISSUE THREAD

**Issue by susanatfybr** [ropensci/magick#149]
Hello!

I am getting the following error while using the image_write() function:

`Error in writeBin(buf, path) : 
long vectors not supported yet: connections.c:4147`

The raw byte object produced in the line is over 2.9 billion:
`buf <- magick:::magick_image_write(image, format, quality, depth, density, comment)`

From the writeBin documentation itself, only just over 2.1 billion bytes can be written:  

> Only 2^31 - 1 bytes can be written in a single call

I am considering using tiling to resolving this issue, however, I was wondering if you are looking to add support for large images anytime in the near future.

Thanks!

**Comment by AndyPL22** [comment]
Seconded! This would be super useful. Thanks :)

**Comment by jeroen** [comment]
How do you end up with such a large image? Does it get smaller when you write as jpeg? Does it work if you manually do:

```r
output <- image_write(img, NULL)
```

And then write the output yourself (in pieces perhaps)?

**Comment by susanatfybr** [comment]
Thanks for your response! In the end, that's exactly what I did - captured the output of image_write() and wrote the raw data in chunks to file.

Large images like this are really common in GIS & remote sensing. I suppose my main question remains - although I'll close the issue - any chance of adding support for large images at any point?

Thanks again.
