### ISSUE TITLE
Request: don't import knitr

### ISSUE THREAD

**Issue by wch** [ropensci/magick#150]
In the interest of reducing dependencies, I suggest changing knitr from an imported package to a suggested package. From what I can tell, magick imports knitr only because it defines a `knit_print` method. If this is right, then it should be possible to move knitr from Imports to Suggests, by using `registerS3method`, and adding a hook to call that function when knitr is loaded.

See here for an example of how to do it: https://github.com/tidyverse/glue/blob/4e749011/R/zzz.R

**Comment by jeroen** [comment]
Will images still automatically show up in rmarkdown documents then?

**Comment by wch** [comment]
It should work. Webshot uses the same technique for `knit_print`: https://github.com/wch/webshot/blob/311882f/R/zzz.R

(Webshot has an earlier version of the code compared to glue, and I plan on updating it shortly.)

**Comment by jeroen** [comment]
Hmm it feels a bit hacky. The webshote code has a comment:

 > That means that R will only know to use our methods if webshot is actually attached, i.e., you have to use library(webshot) in a knitr document or else you'll get escaped HTML in your document. 

So I suppose it doesn't work when rendering vignettes for packages that import magick but do not attach it?

**Comment by jimhester** [comment]
Yes this dynamic S3 registration works as long as the namespace is loaded, nothing needs to be attached and it is pretty widely used by a number of packages on CRAN (https://github.com/search?q=user%3Acran+register_s3_method&type=Code). I have not encountered any issues with it in practice.

**Comment by jeroen** [comment]
Ok sounds good, do you have time to make a PR?

**Comment by jeroen** [comment]
This is on CRAN now.
