### ISSUE TITLE
convert into pixel values?

### ISSUE THREAD

**Issue by forrestw2005** [ropensci/magick#154]
Is there any function I can use to convert image into pixel values form( array or matrix)? I am new for this package. Thanks for any help~

**Comment by jeroen** [comment]
Either use `image_data()` or just `image[[1]]`

**Comment by forrestw2005** [comment]
thanks, Jeroen~

**Comment by forrestw2005** [comment]
Hey, Mr Jeroen. I used your method to get the pixel values and it seems that it is not the values I need, some values are in letter, i am confused for this type data.  Can you tell me how to convert the array with values from 0-255? also how I can show all the array? Thanks so much~

**Comment by jwijffels** [comment]
I generally do this with such a function
```
image_content <- function(x, ...){
  x <- image_data(x, ...)
  as.integer(x)
}
image_content(myimg)
```

**Comment by forrestw2005** [comment]
thanks @jwijffels

**Comment by forrestw2005** [comment]
@jwijffels  is there any way to convert the density of image when using image_read() function?

**Comment by jwijffels** [comment]
You should ask such questions on stackoverflow.

**Comment by forrestw2005** [comment]
thanks, i have it figured out, thanks again

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
