### ISSUE TITLE
image_read segfaults with svg images

### ISSUE THREAD

**Issue by Bisaloo** [ropensci/magick#156]
Hi,

I think this is a bug but it might also be my fault. I apologise in this case.

I get a segfault error when I try to open `svg` images with `image_read`. I tried with different images and always get this issue:

```
> magick::image_read("next.svg")

 *** caught segfault ***
address 0x108, cause 'memory not mapped'

Traceback:
 1: magick_image_readpath(path, density, depth, strip)
 2: magick::image_read("next.svg")
```

Please let me know what I can do to help pinpoint the exact issue.

**Comment by Bisaloo** [comment]
Actually, it looks like the issue lies with imagemagick itself.

I get the same error with 

```bash
identify next.svg
```

or

```bash
convert next.svg next.png
```

**Comment by Bisaloo** [comment]
Yes, it works with `image_read_svg` but I encountered with issue while using `ggimage` so I am stuck with `image_read`.

**Comment by znmeb** [comment]
@Bisaloo What version of the ImageMagick package do you have? I'm on Arch Linux, and I saw some problems today after an upgrade from `imagemagick-7.0.8.13-1-x86_64` to `imagemagick-7.0.8.14-1-x86_64`. I'll open a new issue with a reprex if this is still happening after my next set of changes.

**Comment by Bisaloo** [comment]
Ok, this was actually my mistake, I was running an outdated version of ImageMagick. I added the ppa at some point but then apparently removed it.

```bash
identify --version
```

> Version: ImageMagick 6.8.9-9 Q16 x86_64 2018-09-28 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib

So I re-added the ppa, updated ImageMagick to the latest available version, recompiled `magick` to get the correct bindings and everything now works as expected.

> Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib


Sorry for the noise!
