### ISSUE TITLE
Crop on rotated image

### ISSUE THREAD

**Issue by statist-bhfz** [ropensci/magick#161]
I have noticed some unexpected behaviour when rotated image is cropped:
```
> frink <- image_read("https://jeroen.github.io/images/frink.png")
> frink
  format width height colorspace matte filesize density
1    PNG   220    445       sRGB  TRUE    73494   72x72
> image_crop(frink)
  format width height colorspace matte filesize density
1    PNG   220    445       sRGB  TRUE        0   72x72
> frink <- image_rotate(frink, 12)
> frink
  format width height colorspace matte filesize density
1    PNG   310    483       sRGB  TRUE        0   72x72
> image_crop(frink)
  format width height colorspace matte filesize density
1    PNG   265    464       sRGB  TRUE        0   72x72
```
Rotated image 310x483 was cropped to 265x464 with default value `geometry = NULL`. Original image wasn't cropped.
I can't find any explanation in package or original ImageMagick documentation,

**Comment by jeroen** [comment]
I think you need to call `image_repage()` in between if you want to keep the entire canvas.

**Comment by statist-bhfz** [comment]
@jeroen Thanks! I think this function worth some documentation, it is completely absent for now.

**Comment by jeroen** [comment]
I don't really understand when imagemagick exactly requires repage either. But you're welcome to figure it out and send a PR with better documentation.
