### ISSUE TITLE
Masks

### ISSUE THREAD

**Issue by dmi3kno** [ropensci/magick#164]
Would be really cool to bring masks to magick:
https://www.imagemagick.org/Usage/masking/#special_masks

> write mask will limit what pixels will be written to an image

**Comment by jeroen** [comment]
Can you please elaborate a bit on what you would use this for and what it would look like?

**Comment by dmi3kno** [comment]
The objective is to be able to produce something like this
![229567](https://user-images.githubusercontent.com/13419011/61592675-c94b0a00-abd6-11e9-8da7-5e159afbb7ef.jpg)
The idea is to limit application of the functions to the area defined by black and white channel.

I understand that ImageMagick works with "memory-linked" images which might be difficult to implement. One idea might be to have a single wrapper
```r
image_with_mask(image, mask, f, ...)
```
where `f` is a function that can be applied to `image`. In this wrapper you can do "controlled" application of the function, using "b/w" mask image as a guidance on which pixels get affected by the function.

🤔 I guess you can argue that this can be implemented by converting mask to opacity and "cutting" the image with `composite` `operator="CopyOpacity"` with subsequent `composite` with `operator=atop`.💭

**Comment by dmi3kno** [comment]
I guess, this is not strictly necessary. I am happy to close the case. Now we can produce pretty good masks with `image_fill()`, so this effort would not be justified.

Let's say we have an image and its segmentation (from ML algorithm or OpenCV)
```r
library(magick)

# Source of images: https://thegradient.pub/semantic-segmentation/

cow <- image_read("~/Downloads/image7.png")
cow
```
![cow](https://user-images.githubusercontent.com/13419011/61593899-edfaae00-abe5-11e9-9f40-7f7837f9fd69.png)

```r
cow_seg <- image_read("~/Downloads/image7_mask.png")
cow_seg
```
![cow_seg](https://user-images.githubusercontent.com/13419011/61593900-f226cb80-abe5-11e9-8119-40edeb67155a.png)

I made my own little helper function to help me locate the points where I want to start flooding:
```r
image_plot<-function(img, x, y, col="green", pointsize=5){
  res <- image_draw(img, pointsize = pointsize)
  points(x, y, col=col)
  dev.off()
  res
}

cow_seg %>% image_plot(280, 180)
cow_mask <- cow_seg %>% 
  image_fill("purple", "+280+180", fuzz = 10) %>% 
  image_transparent("purple") %>% 
  image_channel("alpha")

cow_mask
```
![cow_mask](https://user-images.githubusercontent.com/13419011/61593906-0965b900-abe6-11e9-8c8a-75b21d7eafd8.png)

Now I can mask the cow and do something on the background (or at least this is how it looks at the end)

```r
cow_solo <- image_composite(cow, cow_mask, operator = "CopyOpacity")

image_composite(cow, image_negate(cow_mask), operator = "CopyOpacity") %>% 
  image_blur(20,20) %>% 
  image_threshold(threshold = "100%", channel = "Opacity") %>% 
  image_flatten() %>% 
  image_composite(cow_solo) 
```
![cow_composite](https://user-images.githubusercontent.com/13419011/61593920-2c906880-abe6-11e9-9504-3f203b04611e.png)

There's only one small problem. I can't find the way to turn off (delete) certain channel. in `ImageMagick` I can do `-alpha off`, but I couldn't find an easy easy way of doing it in R. I am circumventing it with:
```r
  image_threshold(threshold = "100%", channel = "Opacity") %>% 
  image_flatten() %>% 
```
But this is an ugly hack - there's a big white hole behind the cow.

May I suggest we add `negate` (or `drop`) argument to `image_channel()`, to be able to "drop" channels, instead of selecting them. You could argue I could have "composed" the picture from scratch by mixing channels with "composite", but that is really hacky and I would rather not.

**Comment by dmi3kno** [comment]
This can be closed now.
