### ISSUE TITLE
Conditional floodfill

### ISSUE THREAD

**Issue by dmi3kno** [ropensci/magick#165]
I understand that `image_fill` should imitate floodfill option
https://imagemagick.org/script/command-line-options.php#floodfill

However the last argument for conditional filling is not implemented in R
> Note that if the pixel at the 'seed point' does not itself match the given color (according to -fuzz), then no action will be taken.

**Comment by jeroen** [comment]
I have tried something in the [fill-to-color](https://github.com/ropensci/magick/tree/fill-to-color) branch but I'm not quite sure what this is supposed to do and how to test if it works. Can you test this?

```r
remotes::install_github("ropensci/magick@fill-to-color")
```

**Comment by dmi3kno** [comment]
@jeroen I love it! Thank you very much! 

I am taking @jennybc example from #32 and will try to floodfill it with red, from a single point:

```r
library(magick)

img <- image_read_pdf("~/Downloads/Arrows-jenny-2016-11-06.pdf") %>% 
  image_trim() %>% image_rotate(270) %>% image_resize("600x") 

# I am targeting point +20+82 of color 
pt <- img %>% image_crop("1x1+20+82") %>% image_raster()
pt$col
#> [1] "#000000ff"

# located here
res_img <- img %>% image_draw()
points(20, 82, col="green")
dev.off()
res_img
```  
![preview1](https://user-images.githubusercontent.com/13419011/61591154-55ebcd00-abc3-11e9-9cc5-b357f1cfbc2b.png)

Next, we will try to flood it, but only it the target color is less than `fuzz=20` away from `purple` color.

```r
img %>% 
  image_fill("red", point="+160+94", fuzz=20, "purple")
``` 
![preview2](https://user-images.githubusercontent.com/13419011/61591719-5045b580-abca-11e9-87fc-02ca101ec14a.png)

In this case nothing is selected because the color at the pixel we indicated is "further away" from "purple" than `fuzz=20`. Lets try again with higher `fuzz` value

```r
img %>% 
  image_fill("red", point="+160+94", fuzz=50, "purple")
``` 
![preview3](https://user-images.githubusercontent.com/13419011/61591769-b92d2d80-abca-11e9-8102-8a5054d22192.png)

Now, we're talking! Black is `fuzz=50` away from "purple".

-----------------------------

Let's try a different image from #32. Note that I trimmed it, so dimensions have changed

```r
img_mask <- img %>% 
  image_fill("red", point="+160+94", fuzz=50) %>% 
  image_transparent("red", fuzz=50) %>% 
  image_channel("Opacity") %>% 
  image_median(5) %>% 
  image_trim()

cool_gradient <- image_blank(image_info(img_mask)$width, image_info(img_mask)$height, 
                             pseudo_image = "radial-gradient:purple-yellow")

img2 <- image_composite(cool_gradient, img_mask, operator = "CopyOpacity", offset = "+0+0") %>% 
  image_convert(format = "png") 

# I am targeting point +160+45 of color 
pt <- img2 %>% image_crop("1x1+160+45") %>% image_raster()
pt$col
#> [1] "#8f1d71ff"

res_img2 <- img2 %>% image_draw(pointsize = 5)
points(160, 45, col="green")
dev.off()
res_img2
```
![preview4](https://user-images.githubusercontent.com/13419011/61591793-04dfd700-abcb-11e9-9192-379b52a7178e.png)

First we flood from "+160+45" with `fuzz=20` from "purple"
```r
img2 %>% 
  image_fill("red", point="+160+45", fuzz=20, "purple")
```
![preview5](https://user-images.githubusercontent.com/13419011/61591821-5ee09c80-abcb-11e9-99d7-beedfe7cc99d.png)

And the same with `fuzz=20` from "#8f1d71ff" (the color of the point actually found at that location)
```r
img2 %>% 
  image_fill("red", point="+160+45", fuzz=20)
```
![preview5_0](https://user-images.githubusercontent.com/13419011/61591842-a830ec00-abcb-11e9-919f-89f04b728a92.png)

Then we flood with `fuzz=50` from "purple"
```r
img2 %>% 
  image_fill("red", point="+160+45", fuzz=50, "purple")
```
![preview6](https://user-images.githubusercontent.com/13419011/61591843-acf5a000-abcb-11e9-9bb3-94bf89dbce59.png)

And the same with `fuzz=50` from "#8f1d71ff" (the color of the point actually found at that location)
```r
img2 %>% 
  image_fill("red", point="+160+45", fuzz=50)
``` 
![preview6_0](https://user-images.githubusercontent.com/13419011/61591846-b252ea80-abcb-11e9-9ad7-6448c5bb0301.png)

I think this is working as expected. I am not sure I agree to the argument name `endcolor`. Perhaps. `targetcolor` is a better name. I also suggest the following documentation string:
```r
#' @param point a geometry_point string indicating the starting point of the flood-fill
#' @param fuzz relative color distance (value between 0 and 100) to be considered similar in the filling algorithm
#' @param targetcolor if set, `fuzz` color distance will be measured against this color, not the color of the starting point (see `geometry`). 
#' Any color (within `fuzz` color distance of the given `targetcolor`), connected to starting point will be replaced with the `color`. 
#' Note that if the pixel at the starting point does not itself match the given `targetcolor` (according to `fuzz`), then no action will be taken.
```

**Comment by jeroen** [comment]
OK thanks. Maybe should we name it `fuzzcolor` then ?

**Comment by dmi3kno** [comment]
I updated the example above. This is reference color for fuzz argument.

**Comment by jeroen** [comment]
OK I set it to `refcolor` as you suggested and merged in master. Thanks!

**Comment by dmi3kno** [comment]
Jeroen, one minor issue here: Your default geometry in `image_fill()` is wrong. it should be `+1+1`(geometry_point) and you put `1x1` (geometry_area). Everything works as intended, if user overrides your default.

**Comment by jeroen** [comment]
Thanks will fix
