### ISSUE TITLE
rgl movie3d throws error

### ISSUE THREAD

**Issue by frevi** [ropensci/magick#167]
Sorry, this is probably the wrong place for this question but I couldn't find a better one (where should I ask?)

I just installed the magick package to R 3.5.1 using RStudio  1.1.463. I have rgl 0.99.16.

rgl movie3d with convert=TRUE is supposed to call magick and create an animation. However, when I try it, the files are generated to the temp directoery (not the final one), but the animation is not. The situation looks like this:

```
> movie3d(umr,
+         duration = 10,
+         fps=30,
+         movie="./output/tm1a/spin_tm1a",
+         frames="spin_tm1a",
+         dir="./output/temp",
+         convert=TRUE
+ )
Writing 'spin_tm1a300.png'          # files get generated
Error in movie3d(umr, duration = 10, fps = 30, movie = "./output/tm1a/spin_tm1a",  : 
  'ImageMagick' not found
In addition: Warning message:
In system2(progname, "--version", stdout = TRUE, stderr = TRUE) :
  running command '"convert" --version' had status 4
```
How can I get magick to run properly and do the animation please?  Thank you.

-Frank

**Comment by jeroen** [comment]
This has nothing to do with the magick package but with rgl. It looks like the code you are using doesn't use the magick package because it shells out to `convert.exe`.
