### ISSUE TITLE
Filename

### ISSUE THREAD

**Issue by msgoussi** [ropensci/magick#168]
when I try to open a file using magick in R, I get the following error
 Magick: UnableToOpenBlob `D:\CÃ´te.png'
 No such file or directory @ error/blob.c/OpenBlob/2701

my file name could be as follows
"C\xf4te.png" or "C\u00f4te.png"
Thanks

**Comment by jeroen** [comment]
Please include your sessionInfo

**Comment by msgoussi** [comment]
library(magick)
tiger <- image_read_svg('http://jeroen.github.io/images/tiger.svg', width =
400)
image_write(tiger, path = "C\u00f4te.png", format = "png")
tiger1 <- image_read("Côte.png")
Error in magick_image_readpath(path, density, depth, strip) :
  Magick: UnableToOpenBlob `D:\Documents\CÃ´te.png': No such file or
directory @ error/blob.c/OpenBlob/2701

> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United
States.1252
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C

[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] magick_2.0

loaded via a namespace (and not attached):
[1] compiler_3.5.2 magrittr_1.5   tools_3.5.2    rsvg_1.3       curl_3.2

[6] yaml_2.2.0     Rcpp_1.0.0

**Comment by msgoussi** [comment]
any news

**Comment by jeroen** [comment]
Fixed in magick 2.1 on CRAN.

**Comment by lwdalton3** [comment]
I have installed the 2.1 version


install.packages("magick")
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/magick_2.1.tgz'
Content type 'application/x-gzip' length 27242908 bytes (26.0 MB)
==================================================
downloaded 26.0 MB


In a file which is successfully opened by gimp I too have encountered the blob error even though I kept the tiger. Is there some fix? I could really use the cropping functions etc?

tiger <- image_read('/Users/louisedalton/Downloads/mites/Screenshot_754_.png')

Error in magick_image_readpath(enc2native(path), density, depth, strip) : 
  Magick: UnableToOpenBlob `/Users/louisedalton/Downloads/mites/Screenshot_754_.png': No such file or directory @ error/blob.c/OpenBlob/2761

**Comment by lwdalton3** [comment]
Sorry about the expanded font in the copy and paste-- did not intend to shout. LD

**Comment by lwdalton3** [comment]
This was my bad, and apologize. I did not notice two adjacent underscores on the files and alas thought only one was present. But gives me a chance to applaud the magick library.
I was able to properly crop a large number of files as a large batch as a preprocessing step for TensorFlow. The script necessary was not complicated.

**Comment by jeroen** [comment]
@msgoussi this is fixed in magick 2.5.1, see also https://github.com/ropensci/magick/issues/285
