### ISSUE TITLE
Create a watermark image like in ImageMagick

### ISSUE THREAD

**Issue by enricodata** [ropensci/magick#176]
Is it possible with magick to create a watermark transparent image as with ImageMagick with the following code?

convert -size 420x100 xc:transparent -font ComicSans -pointsize 50 \
           -fill black        -annotate +24+64 'Copyright' \
           -fill white        -annotate +26+66 'Copyright' \
           -fill transparent  -annotate +25+65 'Copyright' \
           trans_stamp.png

**Comment by jeroen** [comment]
Did you try the `image_annotate() function?

**Comment by EnricowithR** [comment]
yes, I used that function. 
However the effect is not the same as with ImageMagick, because with ImageMagick it is possible to give a transparent effect

**Comment by dmi3kno** [comment]
How's this different?
```r
image_blank(420,110, "transparent") %>% 
  image_annotate("Copyright", location = "+24+64", size=30, font="Roboto", color="black") %>% 
  image_annotate("Copyright", location = "+26+66", size=30, font="Roboto", color="white") %>% 
  image_annotate("Copyright", location = "+25+65", size=30, font="Roboto", color="transparent") %>% 
  image_write("trans_stamp.png")
```
![trans_stamp](https://user-images.githubusercontent.com/13419011/61667622-c0436100-acda-11e9-80c8-68e76f0aeb09.png)

**Comment by EnricowithR** [comment]
thanks dmi3kno, with that it works!

**Comment by dmi3kno** [comment]
Glad it helped. Could you please close the issue?
