### ISSUE TITLE
magick refuses to let go of memory

### ISSUE THREAD

**Issue by oganm** [ropensci/magick#181]
I noticed this when running a plumber api that uses magick functions. It seems like memory use of an R session increases for no apparent reason when running a basic command like 

```r
 img = image_read('image.png')
```

over and over again. You can repeat this by opening an R session and just repeating that line and watch the memory use go up till eventually, you're unable to allocate more memory. Running a `gc()` fixes this issue.

This is an Ubuntu 16.4 machine, running R 3.4.4

**Comment by oganm** [comment]
Yes but my understanding is that R is supposed to handle garbage collection on its own in most cases and I don't normally experience indefinitely rising memory use on a long running session without running `gc`. Was wondering if there's a preventable reason for that to happen.

**Comment by oganm** [comment]
It seems like on a machine with large memory, garbage collection eventually happens and the issue is unique to machines with small amounts of ram. Not sure what causes R to be fine with filling up the memory till it crashes when it could be avoided with a `gc` but it's more of an R issue than a magick issue

**Comment by jeroen** [comment]
I think it happens because the memory is allocated and managed by an external by imagemagick, not by R itself. So the GC doesn't really know how much memory the image objects are holding. Therefore it might not be active enough in collecting them...

**Comment by oganm** [comment]
For reference, here's what happens to memory use if I try to run `image_read` continuously on a machine with 1GB + 1GB swap RAM 

![magickMemory](https://user-images.githubusercontent.com/6352379/54783391-76d4ef00-4bde-11e9-8f2d-5aeb5439ffa3.png)

(this ends with an error)

vs a machine with 16 gb + 16 gb swap RAM

![magickMemory](https://user-images.githubusercontent.com/6352379/54783501-c3202f00-4bde-11e9-9a2f-8679a8f75c7b.png)

or 

![magickMemory2](https://user-images.githubusercontent.com/6352379/54783547-e2b75780-4bde-11e9-8c14-dc80e71f1e82.png)

Have no idea what is different between the two runs but they do look mildly interesting

**Comment by jeroen** [comment]
I have added a method `image_destroy()`: https://github.com/ropensci/magick/commit/d03ee31e3e7802bad71b50721f07d913bdac69fe

This allows you to explicitly free the images when needed.
