### ISSUE TITLE
Will the packages support read emf figures?

### ISSUE THREAD

**Issue by guokai8** [ropensci/magick#195]
Hi,
I wonder if you are planning to add read emf figures function in the future.
Kai

**Comment by jeroen** [comment]
I don't think so. If we would support it, it would only work on Windows anyway: http://www.imagemagick.org/script/formats.php

**Comment by guokai8** [comment]
Hi,
I am sorry.  The emf format also can be used with powerpoint on Mac. Can you add the function to import emf file?
Thanks,
Kai

**Comment by jeroen** [comment]
I'm sorry there is no portable way to do this I think. Why do you need emf? Who uses that?
