### ISSUE TITLE
accept vector of character strings in image_annotate?

### ISSUE THREAD

**Issue by dschneiderch** [ropensci/magick#196]
First, thanks so much for the package! It's proving essential for making timelapse videos from images.
A small update that would be nice is to accept a vector of strings for image_annotate(). in tidyverse style, I expected to be able to provide either vector length 1 that is repeated on each image in the stack or vector length n where n = number of images in the stack. 
Now I'm using a loop to to annotate the date from each filename onto each image.

I did take a look at the source, but I don't know how adding a for loop in image_annotate() would behave with the cpp bindings.

**Comment by jeroen** [comment]
OK I added this. The thing that worries me a bit is that users now might expect the other parameters are also vectorized, but this is not the case. Only 'text' parameter is vectorized, the others are fixed.

**Comment by julianaspector** [comment]
@jeroen Have you considered making the image parameter for image_annotate() vectorized as well? I'm trying to annotate a series of gif images (same image) to later create an animation where the text overlay changes at specified time intervals.
