### ISSUE TITLE
cannot find  -lMagick++-6.Q16 when installing on Ubuntu 19.04

### ISSUE THREAD

**Issue by Vladvance** [ropensci/magick#197]
I tried to install package and got this errors:
```
/home/vladvance/anaconda3/envs/r/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lMagick++-6.Q16
/home/vladvance/anaconda3/envs/r/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lMagickWand-6.Q16
/home/vladvance/anaconda3/envs/r/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lMagickCore-6.Q16
```

But I have libmagick++-dev installed:
```
vladvance@VladOS:~$ sudo apt install libmagick++-dev
[sudo] password for vladvance: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libmagick++-dev is already the newest version (8:6.9.10.14+dfsg-7ubuntu2).
```

**Comment by ShotaOchi** [comment]
Run the following code instead of "sudo apt install libmagick++-dev".
```
 conda install -c conda-forge imagemagick
```

**Comment by Vladvance** [comment]
@ShotaOchi, thanks for help. Well, now package installed succesfully, but when I try to install 'summarytools' package, I get this error: 
```
Error: package or namespace load failed for ‘summarytools’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/vladvance/anaconda3/envs/r/lib/R/library/magick/libs/magick.so':
  /home/vladvance/anaconda3/envs/r/lib/./librsvg-2.so.2: undefined symbol: cairo_tag_end
```

**Comment by ShotaOchi** [comment]
I recommend that you read the anaconda documentation.

**Comment by jeroen** [comment]
Please do not use anaconda. The the official R from the `r-base` ubuntu package will work seamlessly with `libmagick++-dev`.

**Comment by ShotaOchi** [comment]
We can use anaconda.

The installation error of summarytools didn't occur on my environment.
My environment was created according to the website below.
https://docs.anaconda.com/anaconda/user-guide/tasks/using-r-language/

I think Vladvance can fix the error by installing missing package or rebuilding of environment.
