### ISSUE TITLE
Editing svg content

### ISSUE THREAD

**Issue by john-harrold** [ropensci/magick#199]
Is it possible to modify the contents of an svg file. If I have field like:

`<text>PLACEHOLDER</text> `

can I modify the PLACEHOLDER content in a programmatic fashion? Like have it replaced with 'my text', so that when the image is rendered it says my text?

**Comment by jeroen** [comment]
You should use the `xml2` package to modify xml documents.

**Comment by dmi3kno** [comment]
Hey @john-harrold ,
I edited SVG logo with xml2 [here](https://gist.github.com/dmi3kno/da6323a063ea736572bfacb7be21b165). To edit text you might need to extract the node of interest, modify it and then place it back with `xml2::xml_replace()`. Good luck!
