### ISSUE TITLE
SVG format different on windows and ubuntu

### ISSUE THREAD

**Issue by marchandpatrick** [ropensci/magick#200]
# Same image reports different properties when read from windows or ubuntu:

library("magick")
tiger <- image_read('http://jeroen.github.io/images/tiger.svg')
tiger

# correct result on windows:
#> library("magick")
#> tiger <- image_read('http://jeroen.github.io/images/tiger.svg')
#> tiger
#format width height colorspace matte filesize density
#1    SVG   900    900       sRGB  TRUE    68630   96x96

# on ubuntu 18 several parameters are different: (format,density)
#> tiger <- image_read('http://jeroen.github.io/images/tiger.svg')
#>Warning message:
#>  ImageMagick was built without librsvg which causes poor qualty of SVG rendering.
#For better results use image_read_svg() which uses the rsvg package.
#>
#> tiger
#format width height colorspace matte filesize density
#1    MVG   900    900       sRGB  TRUE    77546   72x72

tiger2 <- image_read_svg('http://jeroen.github.io/images/tiger.svg')
tiger2

#> tiger2 <- image_read_svg('http://jeroen.github.io/images/tiger.svg')
#> tiger2
#format width height colorspace matte filesize density
#1    PNG   900    900       sRGB  TRUE        0   72x72
#>

sessionInfo()
#R version 3.4.4 (2018-03-15)
#Platform: x86_64-pc-linux-gnu (64-bit)
#Running under: Ubuntu 18.04.2 LTS
# 
#Matrix products: default
#BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
#LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
# 
#locale:
#[1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8       
#[4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=en_US.UTF-8   
#[7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
#[10] LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
# 
#attached base packages:
#[1] stats     graphics  grDevices utils     datasets  methods   base     
# 
#other attached packages:
#[1] magick_2.0       Tools13399_0.1.0
# 
#loaded via a namespace (and not attached):
#[1] compiler_3.4.4   backports_1.1.4  assertthat_0.2.1 plyr_1.8.4       magrittr_1.5    
#199 [6] cli_1.1.0        rprojroot_1.3-2  tools_3.4.4      fs_1.3.1         rstudioapi_0.10 
#[11] curl_3.3         rsvg_1.3         crayon_1.3.4     Rcpp_1.0.1      
#> 

#imagemagick is already the newest version (8:6.9.7.4+dfsg-16ubuntu6.4).

**Comment by jeroen** [comment]
Unfortunately the Debian/Ubuntu version of imagemagick is built without support for cairo/librsvg these days. I reported this a while back in Debian but they didn't care much: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882852

Indeed, as a workaround you can use `image_read_svg()` which uses the R package `rsvg` to render the svg. This should result in OK rendering but indeed loses some meta data. Not much else I can do.
