### ISSUE TITLE
Point to different imagemackick installation on linux

### ISSUE THREAD

**Issue by johanneswaage** [ropensci/magick#201]
Hi,
Due to an old version being available on RHEL 7.5, I've compiled ImageMagick from source, and installed into /opt/imagemagick. How do I tell `magick` to use this installation instead of the one installed into `/usr/lib64` by RHEL? Setting `LD_LIBRARY_PATH` doesnt' work.

Thanks.

**Comment by jeroen** [comment]
You also need to set both `PKG_CONFIG_PATH` to your `.pc` file and `LD_LIBRARY_PATH` to your library.
