### ISSUE TITLE
Add image_shadow()

### ISSUE THREAD

**Issue by dmi3kno** [ropensci/magick#204]
Pretty standard challenge is trying to add drop-shadow to images (particularly charts and screenshots). Would be cool to implement `convert ... -shadow geometry` pattern
References: http://www.imagemagick.org/Usage/blur/#shadow

Here's a function i use today to add drop shadow to screenshots:
```r
im_add_shadow <- function(file, size, shdw=80){
  file_new <- glue::glue(tools::file_path_sans_ext(file), "-s.",tools::file_ext(file)) 
  sysstr <- glue::glue("convert {file} -filter Lanczos -resize {size} \\( +clone -background black -shadow {shdw}x10+0+15 \\) +swap -background transparent -layers merge +repage -trim {file_new}")
  system(sysstr)
}
```

**Comment by jeroen** [comment]
@dlemstra I tried with both STL `shadowImage()` and `Image->shadow()` but all images become completely black (for sigma > 50) or white (for sigma <50). 

Is this a bug? Or should I set some attribute first?

**Comment by dmi3kno** [comment]
@jeroen , I think this is as intended. the 
`+swap -background transparent -layers merge +repage` part of the ImageMagick command is converting the mask to shadow. I.e. shadow becomes dark and then original image is supposed to be placed atop it.

```
convert {file} \\( +clone -background black -shadow {geometry} \\) +swap -background transparent -layers merge +repage {file_new}
```
As you can see the shadow layer is prepared in the "cloned" copy and the `layer merge` is re-composing it together (placing shadow layer underneath).

**Comment by jeroen** [comment]
OK I was able to figure it out. @dmi3kno I have added `image_shadow()` in the master branch. Can you test this?

**Comment by dmi3kno** [comment]
Cool! 

Oh, look I can now produce my own [carbon](https://carbon.now.sh) cards for tweeting!
![my_carbon](https://user-images.githubusercontent.com/13419011/61544952-b275ad80-aa46-11e9-8646-c6c6c5a7ff45.png)
