### ISSUE TITLE
image_alpha()

### ISSUE THREAD

**Issue by dmi3kno** [ropensci/magick#208]
I can't find the way to turn off (delete) alpha channel. in `ImageMagick` I can do `-alpha off`, but I couldn't find an easy easy way of doing it in R. 
_Originally posted by @dmi3kno in https://github.com/ropensci/magick/issues/164#issuecomment-513569147_

Could we have a look at the `-alpha` [options in ImageMagick](https://imagemagick.org/script/command-line-options.php#alpha) and what can be done in this package?

**Comment by jeroen** [comment]
What about `image_convert(x, colorspace = 'rgb')`? Is that the same as droppig alpha?

**Comment by jeroen** [comment]
@dmi3kno I have added a new parameter `matte` to `image_convert()` to enable/disable matte. I think you can also use e.g. `image_convert(x, colorspace = 'rgb')` to convert it to a color space without alpha channel.



To extract the alpha channel you can use `image_channel(x, "a")` I think. 

Does this make sense?

**Comment by dmi3kno** [comment]
`image_convert(x, colorspace='rgb')` does not remove matte, but your new parameter does. Thank you! Closing #208.

**Comment by dmi3kno** [comment]
I will just leave the comment here for the future self that `image_convolve()` will not work unless the matte layer is removed.   image_convert(matte=FALSE) ` does the job perfectly

**Comment by jeroen** [comment]
Perhaps that should be a parameter then?

**Comment by dmi3kno** [comment]
I am not sure if this is a feature or a bug. For now I consider it to be a feature. There's nothing to add because convolution can be done more than 1 way (using image_morphology and using image_convolve)
