### ISSUE TITLE
bug in image_write_gif()

### ISSUE THREAD

**Issue by dmi3kno** [ropensci/magick#210]
There seems to be a bug in gifski? when all frames in gif have transparent background.
[images_4.zip](https://github.com/ropensci/magick/files/3421926/images_4.zip)
```r
list.files("D:/R/", pattern = ".png$", full.names = TRUE) %>% 
  lapply(image_read) %>% 
  {Reduce(c, .)} %>% 
  image_write_gif("D:/R/broken.gif")
```
Produces gif like this:
![broken](https://user-images.githubusercontent.com/13419011/61711192-bf9ae100-ad53-11e9-8be1-273da9c8aa8b.gif)
Note that last frame contains two frames combined.

**Comment by jeroen** [comment]
Yeah looks like it. You can work around it by removing the matte:

```r
library(magick)
list.files("~/Downloads/testgif/", pattern = ".png$", full.names = TRUE) %>% 
  image_read() %>% 
  image_convert(matte = F) %>%
  image_write_gif("out_gifski.gif")
```

**Comment by dmi3kno** [comment]
sounds good. Should I close the issue?
P.S. I always forget `image_read()` is vectorized! Sorry about that.

**Comment by jeroen** [comment]
Maybe open an issue in the gifski repo. But I'm not sure there is much I can do about it.

**Comment by dmi3kno** [comment]
Jeroen, on completely different note: How do i drop a single frame out of the {magick} stack? Right now I coerce to list, drop an element and `Reduce(c, .)` back. Is there a better idea? Not urgent.

**Comment by jeroen** [comment]
Just with the index operator `[` like you would do with any vector?

**Comment by dmi3kno** [comment]
great, thanks!
