### ISSUE TITLE
add image_extend

### ISSUE THREAD

**Issue by jeroen** [ropensci/magick#211]
Added gravity in image_crop() but the other part of the request was to add image_extend: https://github.com/ropensci/magick/issues/44

**Comment by yutannihilation** [comment]
If this issue is about `image_composite()`, `compositeImage()` accepts a `GravityType` object.

https://www.imagemagick.org/Magick++/Image++.html

**Comment by dmi3kno** [comment]
I don't think extent is needed directly. You can always create blank image of pre-defined size  and compose your image `atop`. What would be userful, is like @yutannihilation says, gravity argument, so that if you have to place the image in the center, you wouldnt have to manually calcualte offset.
