### ISSUE TITLE
compose_args in image_composite() ignored

### ISSUE THREAD

**Issue by dmi3kno** [ropensci/magick#212]
It seems like `compose_args` argument in `image_composite()` is simply not wired up:

```r
img_bi <- image_read("https://www.imagemagick.org/Usage/mapping/blur_map_bool.gif")
img_gt <- image_read("https://www.imagemagick.org/Usage/mapping/blur_map_gradient.gif")

image_composite(img_bi, img_gt, operator = "Blur", compose_args = "10")

#> Error in magick_image_composite(image, composite_image, offset, operator,  : 
#>  Magick: InvalidGeometry 'compose:args' '(null)' @ warning/composite.c/CompositeImageChannel/1850
```
Expecting 
![blur_edge_gradient](https://user-images.githubusercontent.com/13419011/62070775-78bd5780-b23b-11e9-8598-8a1f5d0f5aa2.gif)
I understand it should be geometry there, so it could very well be "10x10" but no matter what I try I get the same message. This error does not show in other types of compose methods because few (none?) of them require additional arguments.

Command line is working as planned:
```
convert blur_map_bool.gif blur_map_gradient.gif -compose blur -define compose:args=10 -composite blur_edge_gradient.gif
```

**Comment by jeroen** [comment]
Can you test if the example that comes with that function has any effect for you? It seems fine here.


```r
# Compose images using one of many operators
imlogo <- image_scale(image_read("logo:"), "x275")
rlogo <- image_read("https://developer.r-project.org/Logo/Rlogo-3.png")

# Standard is atop
image_composite(imlogo, rlogo)

# Same as 'blend 50' in the command line
image_composite(imlogo, rlogo, operator = "blend", compose_args="50")

```

**Comment by dmi3kno** [comment]
Yes, looks like my Ubuntu ImageMagick installation has some problems. Issue closed.

**Comment by jeroen** [comment]
Which version of Ubuntu do you use?

**Comment by dmi3kno** [comment]
I need to investigate whats happening with this one and revert. I am on 18.04

**Comment by dmi3kno** [comment]
Issue is gone after updating `magick` package. Dunno how, but I had ImageMagick 6.9.x linked up. Sorry for lack of diligence on testing on different platforms.
