### ISSUE TITLE
separate and combine

### ISSUE THREAD

**Issue by dmi3kno** [ropensci/magick#213]
I implemented separation and re-combining of channels in {bunny} using [channel copying](https://www.imagemagick.org/Usage/color_basics/#combine_other). However, there's known bug in ImageMagick in `-compose -composite` with `operator=CopyBlack` for CMYK colorspace when copying Black channel [fails and ruins the whole image](https://www.imagemagick.org/Usage/bugs/testing/). This is apparently an old and know [issue](https://www.imagemagick.org/Usage/color_basics/#combine_other) which is [unlikely to be fixed](https://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=10322&p=167753#p32517). 

That said,  `-separate` and `-combine` roundtrip seem to work as advertised. 

![rose_cmyk](https://user-images.githubusercontent.com/13419011/62252922-81a55900-b3f4-11e9-936e-790339834a39.jpg)

```
convert rose_cmyk_cmyk.tif -separate separate_CMYK_%d.gif
```
![separate_CMYK_0](https://user-images.githubusercontent.com/13419011/62252854-50c52400-b3f4-11e9-88c9-aa31e857aca9.gif) ![separate_CMYK_1](https://user-images.githubusercontent.com/13419011/62252858-53277e00-b3f4-11e9-9537-366f212e35e8.gif) ![separate_CMYK_2](https://user-images.githubusercontent.com/13419011/62252862-5589d800-b3f4-11e9-84d0-a8b991445df8.gif) ![separate_CMYK_3](https://user-images.githubusercontent.com/13419011/62252866-57539b80-b3f4-11e9-90c1-a9b0bcba3846.gif)
```
convert separate_CMYK_?.gif -set colorspace CMYK -combine \
        -colorspace RGB rose_CMYK_recombined.gif
```
![rose_CMYK_recombined](https://user-images.githubusercontent.com/13419011/62252344-e790e100-b3f2-11e9-9022-0d0eef30ff1a.gif)

These two functions are pretty poorly documented in C++, but they are here in the source code:

[combine](https://imagemagick.org/api/Magick++/STL_8h_source.html#l02259) in Magick++ is `Magick::combineImages` in `STL.cpp`
[Example](https://www.imagemagick.org/discourse-server/viewtopic.php?t=29005#p129388) of constructing grayscale image stack and iterators 

[separate](https://imagemagick.org/api/Magick++/STL_8h_source.html#l02770) in Magick++, is `Magick::separateImages` which is in turn referencing `MagickCore::SeparateImages`. You can find it in the `MagickCore/channel.c` in lines 825-877

If you don't want to do it, I will understand. Everything works fine for `RGB` colorspace and I those who deal with `CMYK` can always drop to CLI for this one operation.  Your call.

**Comment by jeroen** [comment]
Sounds ok if you think this is useful. 

So do I understand it correctly that _separate_ is similar to `image_channel()` but then you get to extract several channels at once?

**Comment by dmi3kno** [comment]
Yes. `separate` takes image, iterates over available channels and returns `image_channel(image, channel)` in an image stack.

`combine` takes image stack and merges it into single image, assuming "0" channel is Red (or Cyan), "1" is Green (or Magenta), "2" is Blue(or Yellow), "3" is Black (if available) and "4" is Opacity.
https://imagemagick.org/script/command-line-options.php#channel

BTW, image_channel(img, "0") does not currently give you Red channel, as it should. It reports "Gray" image, but returns something else. 
![Capture](https://user-images.githubusercontent.com/13419011/62274891-0ddd6d80-b441-11e9-8839-3eccb9d81ce5.PNG)

Is there some sort of iterator in C++ allowing you to get the list of non-empty channels for any given image?

**Comment by dmi3kno** [comment]
Things started to move in Magick and the bug may be fixed [soon](https://imagemagick.org/discourse-server/viewtopic.php?t=10322)

**Comment by jeroen** [comment]
I have added `image_separate()` and `image_combine()`. Can you test this?

**Comment by dmi3kno** [comment]
I see you have been working on this, so half of my comments are gone by now.
Under RGB everything works fine.
Under CMYK image is separating fine, but `combine` is not working.
```r
library(magick)

frink <- image_read("https://jeroen.github.io/images/frink.png")

frink %>% image_flatten() %>% 
  image_convert(colorspace = "CMYK") %>% 
  image_separate() %>% 
  image_combine()
```
![_cmyk_broken](https://user-images.githubusercontent.com/13419011/62392797-a15d8e00-b568-11e9-836f-29136e9f9511.png)

It is not working in my package either, but for a different reason ([bug in CopyBlack](https://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=36465)). At least it is working for "CMY":
```r
# not working in magick
frink %>% image_flatten() %>% 
  image_convert(colorspace = "CMY") %>% 
  image_separate() %>% 
  image_combine()
```
![_cmy_broken](https://user-images.githubusercontent.com/13419011/62392929-0ca76000-b569-11e9-969c-1c452787aaa0.png)

```
# working in bunny
library(bunny)
frink %>%  image_flatten() %>% 
  image_convert(colorspace = "CMY") %>% 
  image_separate() %>% 
  bunny::image_channel_combine(channel_index = "CMYA")
```
![_cmy_working](https://user-images.githubusercontent.com/13419011/62392963-26e13e00-b569-11e9-9a01-add185e83665.png)


### Questions
0) I think we should warn users that you have changed and expanded `channel_types()`. "O" is gone and numbered channels are expanded.
1) Why is there  `channel` argument in separate? `image_separate(frink, "Red")` seems to be equivalent to `image_channel(frink, "Red")`. It can stay of course, if you meant is as synonym.
2) What is the purpose of `channel` argument in `combine()`?
3) How do you enumerate channels? Or rather when you have a stack of 4 images are you making an assumption that they are RGB + Opacity? How do you intend to deal with CMY+Opacity then? I think you can not get away without asking user about the colorspace he/she intends to get. I am doing it in `bunny::image_channel_combine(channel_index="CMYK")`. `channel_index` accepts character vector or single-letter abbreviation, so "RGB", "RGBA", "CMYA" and "CMYK" are all valid indices. Even "AGRB" is a valid index, but that's another story.

I am OK with heuristics you adopted
1) Last channel is always Alpha (even if opacity was missing you create white channel)
2) Sequence of channels is always 0:4 (ref [-channel](https://imagemagick.org/script/command-line-options.php#channel))
In this case all you need is to ask user for colorspace. I mean that `image_combine()` should have `colorspace` argument, not `channel`

**Comment by jeroen** [comment]
> I think we should warn users that you have changed and expanded channel_types(). "O" is gone and numbered channels are expanded.

I haven't changed it, this is probably a result if you upgrading imagemagick.

> Why is there channel argument in separate? image_separate(frink, "Red") seems to be equivalent to image_channel(frink, "Red"). It can stay of course, if you meant is as synonym.
What is the purpose of channel argument in combine()?

I'm just exposing the paramaters from the C++ API. Both `separateImages` and `combineImages` take a channel parameter in C++, so I assume it is needed for something :-)

> Last channel is always Alpha (even if opacity was missing you create white channel)

Again, this is something in imagemagick. But I did notice that if you use `image_separate(logo, "default")` you get 3 channels but if you do `image_separate(logo, "all")` you get 4 channels.

**Comment by jeroen** [comment]
OK I think I found it. I added a `colorspace` argument to `image_combine()` so now you can do:

```r
library(magick)

frink <- image_read("https://jeroen.github.io/images/frink.png")

frink %>% image_flatten() %>% 
  image_convert(colorspace = "CMYK") %>% 
  image_separate() %>% 
  image_combine(colorspace = 'CMYK')

```

**Comment by jeroen** [comment]
Do you think I should drop the channels argument in `image_separate` and `image_combine` and just always set it to `all` in the C++ call ?

**Comment by dmi3kno** [comment]
Looks good after you pull #214. 

You don't need to drop it, I think. Just set it the useful default and let it be. Maybe intention is to add individual layers to incomplete pictures.

**Comment by jeroen** [comment]
OK that's fine by me. Maybe I'll change the default for channel "all" which seems to be what IM7 does.

**Comment by dmi3kno** [comment]
Feel free to close this. I am satisfied.

**Comment by jeroen** [comment]
OK I switched around the arguments as you suggested. 

I also changed the default `colorspace = "undefined"` into `colorspace = "sRGB" which is what undefined actually defaults to in this case (I think).

**Comment by jeroen** [comment]
This is on cran now in magick 2.2
