### ISSUE TITLE
`density` option when reading PDFs with `image_read`

### ISSUE THREAD

**Issue by pboesu** [ropensci/magick#22]
PDFs appear to be down sampled quite badly when you read them in currently. Is there a way to add a `density` argument to specify the resolution of a PDF when using image_read()? Something analogous to command line statements like `convert -density 300  file.pdf file.png`

**Comment by jeroenooms** [comment]
Right I noticed this as well. I'll try to figure this out. 

Note that if you're on linux or mac, you can render pdf via pdftools:

```r
library(pdftools)
library(magick)
bitmap <- pdf_render_page("https://cran.r-project.org/web/packages/magick/magick.pdf", 1)
img <- image_read(bitmap)
```

**Comment by jeroenooms** [comment]
I have added a `desnity` paramamter to image_read:

```r
download.file("https://cran.r-project.org/web/packages/magick/magick.pdf", "magick.pdf")
page <- image_read("magick.pdf[1]", density = "300x300")
```

**Comment by pboesu** [comment]
Brilliant! Thank you.
