### ISSUE TITLE
Memory allocation error

### ISSUE THREAD

**Issue by sealavi** [ropensci/magick#222]
I am trying to create a multipanel animation in r and am using the magick package and gganimate to put a few GIFs together. When I try to read in the GIFs I get this error

Is there a solution to this?

library(magick)
library(gganimate)
ateles_mgif <- image_read("Ateles_geoffroyi_Inez.gif")

Error in magick_image_readpath(path, density, depth, strip) : 
  Magick: MemoryAllocationFailed `C:\Users\sealavi\Documents\Nasua_narica_Avery.gif' @ error/gif.c/ReadGIFImage/1307*

**Comment by jeroen** [comment]
Your machine is either running out of memory, or you run a very old buggy imagemagick....

**Comment by dmi3kno** [comment]
This is cross-post with [SO 59167139](https://stackoverflow.com/questions/59167139/error-using-magick-package-in-r-memory-allocation-error). I think you are simply running out of memory. Try a smaller `gif` and revert.

**Comment by vladtarko** [comment]
This error doesn't necessarily mean you've run out of memory. It only means you've run out of the memory allocated in the ImageMagick policy. You can change that in this file:

`/etc/ImageMagick-6/policy.xml`

Look for:

- `<policy domain="resource" name="memory" value=`
- `<policy domain="resource" name="disk" value=`

They're usually set at fairly low values for modern hardware. Set them at something that makes sense for your computer.
