### ISSUE TITLE
ubuntu installation also need 'apt-get install imagemagick`

### ISSUE THREAD

**Issue by GreenEric** [ropensci/magick#223]
Dear sir,
Per suggestion, I tried `sudo apt-get install libmagick++-dev`, but still got the error message, `Unsupported file format. Please convert to jpeg/png/bmp or install image magick`.
After some search, I also `sudo apt-get install imagemagick`, and that works for me.
Just feed back for your reference,
Thanks for the great work.

**Comment by jeroen** [comment]
I'm not sure where that error comes from but it's not the magick package.
