### ISSUE TITLE
Add functions as these in Inkscape

### ISSUE THREAD

**Issue by WatershedFlow** [ropensci/magick#225]
Magick package is a powerful tool for us using R. I would suggest to add some functions as we can see in Inkscape (https://inkscape.org/), an open source software which I have used for a while. That would be excellent for any R user if your package could do similar tasks as these in the Inkscape.

Looking forward to more excitement in this adventure.

**Comment by dmi3kno** [comment]
Incscape is a vector editor, this is based on raster images. Magick has very little to offer in editing vector shapes. I think this wish, although understandable, is addressed wrong.

**Comment by dmi3kno** [comment]
May I also suggest [minisvg by @coolbutuseless](https://github.com/coolbutuseless/minisvg) which offers toolkit for working with vector graphical objects. I suggest this issue be closed. Thank you

**Comment by jeroen** [comment]
Thanks :)
