### ISSUE TITLE
Reading svg text/xml?

### ISSUE THREAD

**Issue by dmi3kno** [ropensci/magick#231]
As I was working on reproducible magick logo (#230) I imported a couple of SVGs and tried rendering Rstudio's `fontawesome` icons (which renders valid SVG code). 

It could be useful to have a function that accepts SVG text object (like what `fontawesome::fa()` outputs or what you can define with @coolbutuseless `minisvg` [package](https://github.com/coolbutuseless/minisvg)) or an `xml2` object (like when you read an SVG using `xml2::read_xml`) and can render it directly onto canvas. It is actually requiring only small tweak in `image_read_svg()` to start accepting text and xml, but I wonder if it would be confusing when used inside code like this:

```r
my_image %>%
  image_composite(image_read_svg(fontawesome::fa('r-project', "steelblue"), width=200),
                  operator="Atop")
```
Maybe it would be better to have a separate function `image_svg` which accepts only text/xml (along with width/height attributes to allow instant scaling before rasterization)?

**Comment by jeroen** [comment]
Either solution is fine for me. I think the simplest solution is to generalize `image_read_svg` to accept literal svg instead. There are already so many functions in magick, maybe not introduce a new one if we can generalize the existing one.

Want do do a PR?

**Comment by dmi3kno** [comment]
So I just wanted to share what would the workflow with literal SVG look like combining `minisvg` and `magick`
```r
library(minisvg)
library(magick)

doc <- svg_doc(width=1280, height=640)
len     <- 50
angles  <- (seq(0, 360, 60) + 90) * pi/180
xs      <- round(len * cos(angles) + len, 2)
xs0     <- xs - min(xs) # shift left edge to 0
ys      <- round(len * sin(angles) + len, 2)
ys0     <- ys - min(ys) # shift top endge to 0
pat  <- stag$defs()$pattern(width=max(xs0), height=max(ys0)+len, 
                            id = 'motif', patternUnits = 'userSpaceOnUse')
patg <- pat$g(stroke = 'grey5', stroke_width = 10, fill_opacity=0)
patg$add('polygon', xs = xs0, ys = ys0)
patg$add('line', x1 = max(xs0)/2, y1=max(ys0), 
                 x2=max(xs0)/2, y2=max(ys0)+len)
doc$append(pat)
doc$add('rect', x=0, y=0, width='100%', height='100%', fill=pat)
#doc$save("hexmesh.svg")
doc$show()
```
![hexmesh400](https://user-images.githubusercontent.com/13419011/74475336-8c629f80-4ea7-11ea-9680-bfe50162c13f.png)

And then we can read this mesh into raster
```r
hexmesh <- as.character(doc) %>% image_read_svg()
gh_card <- image_blank(width=1280, height=640, 
                       pseudo_image = "radial-gradient:purple-yellow") %>% 
  image_composite(hexmesh, operator = "Screen") %>% 
  image_annotate("All of your packages!", size=100, gravity = "center", font = "Aller",
                 color = "white") 

gh_card %>% image_convert("png") %>% 
  image_write("gh_hexmesh.png")
``` 
![gh_hexmesh400](https://user-images.githubusercontent.com/13419011/74475341-91275380-4ea7-11ea-992e-11e3e8d11976.png)
