### ISSUE TITLE
is it possible use `-define` in the `pseudo_image`?

### ISSUE THREAD

**Issue by dmi3kno** [ropensci/magick#234]
is it possible use `-define` in the `pseudo_image`?

There are many arguments that can manipulate the gradient characteristics

http://www.imagemagick.org/www/script/gradient.php

```r
> image_blank(200, 200, pseudo_image = "-define gradient:direction=south gradient:#3498db-#db3a34")
Error in magick_image_blank(width, height, color, pseudo_image) : 
  Magick: UnableToOpenBlob `-define gradient:direction=north gradient:#3498db-#db3a34': No such file or directory @ error/blob.c/OpenBlob/2761
```

_Originally posted by @yonicd in https://github.com/ropensci/magick/issues/118#issuecomment-569713825_

**Comment by yonicd** [comment]
I didn't see @maelle 's comment, thanks for creating the new issue @dmi3kno

**Comment by dcaud** [comment]
It would be great to hear about this!

**Comment by dmi3kno** [comment]
The easiest I think this can be done is 
```r
image_blank(width, height, color = 'none', pseudo_image = '', define='')
```
Whatever is provided in `define` argument you parse into pieces and provide into [`MagickSetOption`](http://www.imagemagick.org/api/magick-property.php#MagickSetOption) BEFORE `.read` is called, like this:
```c++
MagickSetOption(magick_wand, "gradient:direction", "East");
MagickReadImage(magick_wand, "gradient:black-white");
```
References:
http://www.imagemagick.org/discourse-server/viewtopic.php?t=35521


All pseudo-images and their "define" arguments
https://www.imagemagick.org/script/formats.php#pseudo

**Comment by jeroen** [comment]
I've added an `options` parameter to `image_blank.

@dmi3kno or others, would it make sense to add `options` to other apis as well, like `image_read()`? Or are there no relevant options that will affect image_read?

Or would it make sense to add a new function `image_set_option()` to manually set options on image objects?

**Comment by dmi3kno** [comment]
Oh this is pretty amazing
```r
image_blank(200, 200, pseudo_image = "radial-gradient:#db3a34-#3498db",
            options = c('gradient:radii'='128,64',
                        'gradient:angle' = 45))
```
![image](https://user-images.githubusercontent.com/13419011/83424330-8aa7f200-a42c-11ea-9bdf-67a2d4fb781b.png)

I am not sure where else it might be required. I wonder if `image_set_option()` is a little bit off-track for current `magick` API. Perhaps we should just keep the SetOption pattern in mind for future requests?

`options` as argument might be a good design decision to adopt, wherever you have too many optional attributes, but we will need to look at each instance individually. Trying to create consistent UX is a great idea!

**Comment by jeroen** [comment]
I think i'm going to rename `options` to `defines` because the word `options` is already in use elsewhere for other things....
