### ISSUE TITLE
Scheduler does not work which running a code using magick package

### ISSUE THREAD

**Issue by AmrapalliKaran** [ropensci/magick#239]
I am using the magick package to read an image file from a URL. I am trying to automate the script hence using the command prompt to test the script.

![image](https://user-images.githubusercontent.com/42533457/78748243-249d7200-7989-11ea-8d70-9fc0789db64c.png)

After loading the magick package, the script automatically stops and does not proceed further to read the script. What needs to be added here? Thanks in advance.

**Comment by jeroen** [comment]
What is in your script?

**Comment by AmrapalliKaran** [comment]
Thanks but there was slight tweaking while setting up the scheduler and it has worked.
