### ISSUE TITLE
unexpected output from image_read_svg()

### ISSUE THREAD

**Issue by gjabel** [ropensci/magick#240]
I am trying to use `image_read_svg()` to correctly read the flag for El Salvador from [https://github.com/lipis/flag-icon-css/blob/master/flags/1x1/sv.svg](https://github.com/lipis/flag-icon-css/blob/master/flags/1x1/sv.svg). For most other flags in the repository I can read the images without any trouble from the raw address, however for El Salvador I get the following
```
# no problem
image_read_svg("https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/1x1/fr.svg")
# problem... see picture below
image_read_svg("https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/1x1/sv.svg")
```
![image](https://user-images.githubusercontent.com/2735201/79629509-01d73e80-817d-11ea-8f70-20956049682e.png)

I think it is an issue with the file - as I get the same result regardless of reading the image from the URL or locally (once saving a copy). Is there anything I can do to get the SVG file as it appears in the browser - without the mess?

**Comment by jeroen** [comment]
Which operating system is this? It seems to work fine on macos.

**Comment by gjabel** [comment]
Yep, Windows 10. I get the same problem on both my laptop and PC.

**Comment by jeroen** [comment]
The librsvg library is a bit outdated on Windows. Sadly it is difficult to upgrade it because CRAN the latest versions of librsvg require at least WIndows 7, and cran still runs Windows 2008 (Vista).

**Comment by jeroen** [comment]
OK I found a solution. Version 2.0 of the rsvg package that should solve this problem. It's already on CRAN but the Windows binaries should be there in a couple of days.
