### ISSUE TITLE
Include EBImage as a dependency

### ISSUE THREAD

**Issue by coolbutuseless** [ropensci/magick#241]
Hi,

EBImage is not marked as a dependency, yet needed for `as_EBImage()`.

Could it be added to Imports/Remotes?  Or maybe a `if (require('EBImage')` test at the start of the `as_EBImage()` call?

**Comment by jeroen** [comment]
We can't add it to Imports because that would make it a strong dependency.

What would adding `if (require('EBImage'))` solve? If there is no `EBImage` package then it is still not possible to use `as_EBImage`, even when we test for it?

**Comment by jeroen** [comment]
I see you already removed the dependency on your side, so this is no longer needed I suppose.
