### ISSUE TITLE
Basic question: channel lookup tables

### ISSUE THREAD

**Issue by schienstockd** [ropensci/magick#244]
Hello,

I have a TIFF file with channels and frames.
When I load the image with image_read I get greyscale images.

I would like to colour each channel with a different lookup table ie/ Cyan or Magenta and then combine the channels.

I can combine the images with image_composite and blend but I couldn't figure out how to make the channels colourful.

EDIT: Ok, I found a solution that works for me. But is there a way to assign a channel lookup table?

img <- image_read("image.tif")

img.combo <- img[c(1,2)]

a <- image_colorize(img.combo[1], 100, "Cyan")
b <- image_colorize(img.combo[2], 100, "Magenta")
a.1 <- image_normalize(img.combo[1])
b.1 <- image_normalize(img.combo[2])

a.2 <- image_composite(a, a.1, operator = "Multiply")
b.2 <- image_composite(b, b.1, operator = "Multiply")

image_composite(a.2, b.2, operator = "blend")

**Comment by jeroen** [comment]
Are you looking for `image_separate` and `image_combine` ? See this post for an example: https://ropensci.org/technotes/2019/09/27/ropensci-docs/

**Comment by schienstockd** [comment]
I was looking for something like 'Color Look Up Tables':
https://www.imagemagick.org/Usage/color_mods/

**Comment by dmi3kno** [comment]
The `-clut` operator is not implemented in `{magick}`, neither is 2-argument `-fx` (so you can't cook up your own color lookup). I am afraid you have to go back to command line for this operation

**Comment by dmi3kno** [comment]
Dear @schienstockd . Have a look at the newly added function and example in #250 and consider closing the issue, because you can now make your own color lookup with `fx` function.

**Comment by jeroen** [comment]
Should we also add a clut function?
