### ISSUE TITLE
image_crop function causes permanent no response of R

### ISSUE THREAD

**Issue by ShotaOchi** [ropensci/magick#248]
R shows permanent no response after running the following code.
```
library(magick)
image_crop(wizard, "1x1")
```

Is this a bug?

My session info is here.
> R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)
other attached packages:
[1] magick_2.3.9000

**Comment by dmi3kno** [comment]
Good question. 
``` r

library(magick)
#> Linking to ImageMagick 7.0.10.11
#> Enabled features: fontconfig, freetype, lcms, webp, x11
#> Disabled features: cairo, fftw, ghostscript, pango, rsvg
#> Using 8 threads
library(tictoc)

tic()
wizard %>% 
  image_crop("10x10+0+0")
```

![](https://i.imgur.com/ah1k5Zo.gif)

``` r
toc()
#> 0.236 sec elapsed

tic()
wizard %>% 
  image_crop("5x5+0+0")
```

![](https://i.imgur.com/cQKs2LL.gif)

``` r
toc()
#> 2.691 sec elapsed

tic()
wizard %>% 
  image_crop("3x3+0+0")
```

![](https://i.imgur.com/TxUBuq7.gif)

``` r
toc()
#> 46.388 sec elapsed
```

<sup>Created on 2020-05-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jeroen** [comment]
@dlemstra do you have any guess why `MagickCore::CropImageToTiles` is increasingly slow when cropping into small images?
