### ISSUE TITLE
Could we please, add `image2` as optional argument to `image_fx()` 

### ISSUE THREAD

**Issue by dmi3kno** [ropensci/magick#250]
As recently raised in #244, `image_fx()` currently works only with single image. In some cases, second image may have to be provided to enable `fx` operation comparing/copying data between images. Could we please, add `image2` as a *last*, *optional* argument? that is 
```r
image_fx(image, expression = "p", channel = NULL, image2=NULL)
```

_Originally posted by @dmi3kno in https://github.com/ropensci/magick/issues/138#issuecomment-627590648_

**Comment by jeroen** [comment]
Hmm the `fx()` method in C++ doesn't have a second parameter, see [docs](http://www.imagemagick.org/Magick++/Image++.html).

Perhaps this is something we need to do in a separate al to image-composite?

@dlemstra how would one use `fx()`in c++ with multiple images?

**Comment by dmi3kno** [comment]
Just to make sure we're on the same page, I am talking about [this usecase](https://www.imagemagick.org/Usage/color_mods/#clut)

> If your IM is too old to understand the "-clut" operator or you want to do something out of the ordinary, such as a 2 dimensional color lookup table, then you can roll your own using the General DIY Operator, FX. For example here is a slow, but equivalent command to the above. 
```bash
convert gray_image.jpg  gradient_ice-sea.png -fx 'v.p{0,u*v.h}'  gray_recolored_fx.jpg
```

**Comment by dlemstra** [comment]
@jeroen The `fx` operation only works on a single image.

**Comment by dmi3kno** [comment]
Ok. If that's the case, I guess the issue can be closed, but I still do not understand what `u` and `v` in the `fx` command correspond to then. [Documentation](https://imagemagick.org/script/fx.php) says:
> ## Source Images
> The symbols u and v refer to the first and second images, respectively, in the current image sequence. Refer to a particular image in a sequence by appending its index to any image reference (usually u), with a zero index for the beginning of the sequence.

**Comment by dlemstra** [comment]
I misunderstood what you were trying to accomplish. Thought you wanted to perform the same operation on multiple images at the same time. You could call `fxImages` from `STL.h` instead on a list of images to perform this operation @jeroen. But be aware of this:

> It is important to note the special role played by the first image. This is the only image in the image sequence that is modified, other images are used only for their data.

It might be a good idea to allow specifying a list as the second arguments instead of just `image2` when calling `image_fx`.

**Comment by jeroen** [comment]
Thanks Dirk! Actually I wasn't aware of `fxImages` because it's not in the STL documentation. I should have double checked the STL header files. 

How exactly should I call this? If I have a vector of images and I run:


```cpp
for_each ( vec->begin(), vec->end(), Magick::fxImage(std::string("some expression")));
```

Does this then only modify the first image in the vector? Because most STL methods modify each image in the vector.

**Comment by jeroen** [comment]
@dmi3kno I have added a function `image_fx_sequence` that allows you to pass formulas that treat the input as a sequence with multiple images. Does that work for you?

**Comment by dlemstra** [comment]
This method is an exception @jeroen. The list is linked together and apparently you are even allowed to not have the image that will be modified in the list because you will need to pass that as an argument.

**Comment by dmi3kno** [comment]
Yes, @jeroen this seems to be working. The #244 can be closed as well, i think because there's now a solution for colorlookup
```r
library(magick)

gimg <- image_read("gray_image.jpg") %>% 
  image_convert(type="TrueColor")
gimg
````

![gray_image](https://user-images.githubusercontent.com/13419011/83339718-d776b600-a2d0-11ea-908f-1bdf472b0728.jpg)

```r
gr <- c(
  image_blank(10, 33, pseudo_image = "gradient:wheat-brown"),
  image_blank(10,33, pseudo_image = "gradient:Brown-LawnGreen"),
  image_blank(10,34, pseudo_image = "gradient:DodgerBlue-Navy")
  ) %>% image_append(stack=TRUE) 
```
![gradient3](https://user-images.githubusercontent.com/13419011/83339712-ce85e480-a2d0-11ea-9b7c-c1c627928e0a.jpg)

```r
image_fx_sequence(c(gimg, gr), 'v.p{0,u*v.h}') 
```
![combined](https://user-images.githubusercontent.com/13419011/83339728-ec534980-a2d0-11ea-8400-9b2e279f7dfd.jpg)
