### ISSUE TITLE
magick causes permanently unresponsive R: image_hough_txt, image_hough_draw or image_write

### ISSUE THREAD

**Issue by Kronos-admin** [ropensci/magick#251]
As part of an image processing pipeline, I run the below code in a "for" loop on a set of images. 
R becomes unresponsive after a few images, usually 2-3, always at this step. I must then terminate and restart RStudio. after which the same image processes just fine.

```r
Packages      <- c("magick", "tesseract", "imager", "pracma","dplyr","magrittr","raster","EBImage")
invisible(suppressMessages(suppressWarnings(lapply(Packages, library, character.only = TRUE))))

image <- magick::image_read("177.png")
hough <- magick::image_hough_txt(image, geometry = '100x100+50',  format = "mvg")
  print("Hough text done.")
 magick::image_hough_draw(image, geometry = '100x100+50', color = "red", bg = "transparent",size = 3, overlay = TRUE) %>% magick::image_write("177.hough.png")
```

![177](https://user-images.githubusercontent.com/56801988/82846641-dea85900-9eb7-11ea-87e5-f0f0feb326a8.png)

Windows 10 Pro, v.1903 
Rstudio Version 1.2.5033
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Platform: x86_64-w64-mingw32/x64 (64-bit)
magick v.2.3

**Comment by dmi3kno** [comment]
I would run hough only on edges and increase the threshold.

The more ink you have the more "noisy" the fitted lines will be. As the [manual says](http://www.imagemagick.org/Usage/transform/#hough), if you have too many lines running close to each other, work on edge detection. You can go as far as trying to reduce circles to single point with morphology operation and then fit an unambiguous line through that. Scaling the image down might help as well.

The threshold will drop the lines that have too few hits (not necessarily shorter lines, but rather points too close to each other). Your window size is too big compared to your threshold, basically.
```r
library(magick)
img <- magick::image_read("177.png")

img %>% 
  magick::image_canny() %>% 
  magick::image_hough_draw(geometry = '100x100+150', overlay = TRUE) %>%
  magick::image_write("177_hough_100_100_150.png")
```
![177_hough_100_100_150](https://user-images.githubusercontent.com/13419011/82899021-90986180-9f5a-11ea-8ee7-5ed4861473ed.png)

I know it does not capture the corners but it identifies the pattern much cleaner than in your case.

**Comment by jeroen** [comment]
@Kronos-admin I can't reproduce the problem. Is the image that you posted the `177.png` in your code? Why are you loading all these extra packages that have nothing to do with magick?

Does the advice from @dmi3kno solve your issue? Otherwise please include a minimal reproducible example to let me debug the issue.

**Comment by Kronos-admin** [comment]
@jeroen thank you so much for looking at this. 
1) yes, the above image is 177.png, but the crash is not specific to this image
2) I am running a pipeline that requires other packages. I am currently testing if I can prevent the unresponsiveness by isolating magick from other packages as much as possible. 
3) @dmi3kno gave me some great ideas (thank you!), which I am implementing (see code below). Unfortunately, that has not solved the issue for me. 
4) here is my attempt at a minimal reproducible example (see file timestamps in screnshot):

Packages      <- c("magick", "tesseract", "imager", "pracma","dplyr","magrittr","raster","EBImage")
invisible(suppressMessages(suppressWarnings(lapply(Packages, library, character.only = TRUE))))
setwd("C:/Users/Nikolaus Obholzer/Desktop/arrays/ARv7/ARv7_out")

for(l in 1:50){
prefix = paste0("177.",l)
image <- magick::image_read("177.png")
houghimage <- image %>% 
    image_morphology('CloseI', 'Disk', iterations = 5) %>% 
    image_morphology('Thinning', 'Skeleton', iterations = 5) 
  hough <- magick::image_hough_txt(houghimage, geometry = '100x100+150',  format = "mvg")
 print(paste("Hough text",l,"done."))
  
  houghi <- magick::image_hough_draw(houghimage, geometry = '100x100+150', color = "red", bg = "transparent",size = 3, overlay = TRUE) %>%
  magick::image_write(paste0(prefix,".hough.png"))
  houghi <- NULL  # 
  print(paste("Hough draw",l,"done."))
}

![image](https://user-images.githubusercontent.com/56801988/83268520-bf4d4c80-a193-11ea-8905-820c11ff3ba4.png)

**Comment by dmi3kno** [comment]
If you could put the codeblock into the triple backticks please. It is difficult to read otherwise.

Yeah so the "Skeleton" is freezing for a different reason which we are still to identify in #249
