### ISSUE TITLE
Feature request: "angle" function for image_deskew?

### ISSUE THREAD

**Issue by Kronos-admin** [ropensci/magick#252]
Hi,

would it be possible to add this helper?
magick::image_deskew(image, 40)$angle

similar to:
angle=`convert rose: -background black -rotate 5 -deskew 40 -format '%[deskew:angle]' info:`
echo $angle
-4.02199

Thanks much!

**Comment by dmi3kno** [comment]
In the current interface this type of metadata is lost. I would approach it similar to how `hough` transforms are exposed: an `image_deskew()` and `image_deskew_txt()`, then you can return as many metrics as you want in structured way.

**Comment by jeroen** [comment]
OK I added `image_deskew_angle` and also a more general `image_get_artifact` function that allows you to extract arbitrary artifacts from the image.

**Comment by Kronos-admin** [comment]
Thank you so much! This is going to save me a lot of time!
