### ISSUE TITLE
issue with .gif file generated from image_write()

### ISSUE THREAD

**Issue by makratofil** [ropensci/magick#254]
I'm trying to create an animation comprised of a bunch of plots (daily plots for a whale satellite tag deployment). Creating the animation object works fine, but when I used image_write() to save the animation as a .gif file, the .gif file doesn't work (i.e., is frozen on the first frame, see attached screenshot). The animation also doesn't show up in the viewer panel, although I suspect it is because the file is too large and would take a long time to load.

![magick_animation_gif_fail](https://user-images.githubusercontent.com/61757397/84806503-ab3e8300-afba-11ea-8802-5d0361ff1222.jpg)

Here is my code:
```
all <- image_scale(c(apr18, apr19, apr20, apr21, apr22, apr23, apr24, apr25, apr26, apr27, 
                     apr28, apr29, apr30, may01, may02, may03, may04, may05, may06, may07,
                     may08, may09, may10, may11, may12, may13, may14, may15, may16, may17,
                     may18, may19, may20, may21, may22, may23, may24, may25, may26, may27,
                     may28, may29, may30, may31, jun01, jun02, jun03, jun04, jun05, jun06,
                     jun07, jun08, jun09, jun10, jun11, jun12, jun13, jun14, jun15, jun16,
                     jun17, jun18))

GmTag225Full <- image_animate(all, fps = 1, dispose = 'previous')

image_write(GmTag225Full, "GmTag225_EddyVectorAnimation_FullDply.gif")
```

**Comment by jeroen** [comment]
Can you test your luck with `image_write_gif()` ?

**Comment by makratofil** [comment]
@jeroen That worked, thank you!

**Comment by jeroen** [comment]
You should also look into image_write_video() to generate a high quality video with a much smaller filesize.

**Comment by makratofil** [comment]
Will do, thanks for the suggestion!
