### ISSUE TITLE
Offset from Bottom

### ISSUE THREAD

**Issue by ept2020** [ropensci/magick#256]
This may be a silly question, but I cannot find a way to do it after looking at how the geometry arguments work. Is it possible to write a geometry expression where the y offset is from the bottom, rather than the top? I am trying to use image_annotate to add text of variable length to the bottom of over 200 images. Whether the text is one line, or multiple lines, I want it to end near the bottom of the image. Y offset from the top means that shorter text annotations don't do that, and I have to go and manually adjust them with custom y offset values.

**Comment by dmi3kno** [comment]
try `gravity="South"`
