### ISSUE TITLE
Cannot use built-in color maps

### ISSUE THREAD

**Issue by gmbecker** [ropensci/magick#257]
Unless I am missing something (apologies if so) there doesn't seem to be a way to invoke the "embedded" colormap images built into imagemagick. This would be useful to have.

In particular the one I wanted was NETSCAPE:, which appeasr to be a very good way of getting a good looking image that is much smaller than its true-color/full sRGB original.

Is this something that could be added?

**Comment by jeroen** [comment]
Can you give an example using the command line imagemagick of the functionality that you are after?

**Comment by gmbecker** [comment]
Of course, sorry.

`convert input.png -remap NETSCAPE: output.png`

I can try to find time to make a PR but I can't say exactly when that will be at the moment

**Comment by jeroen** [comment]
Ah OK. You can read embedded images by adding a colon at the end:

```r
image_read("NETSCAPE:")
```

So you can do this:

```r
input <- image_read("input.png")
netscape <- image_read("NETSCAPE:")
image_map(input, netscape)
```

**Comment by gmbecker** [comment]
A cool. thats great to know. I didn't see that documented anywhere (I did look, and did again now), so apologies if I missed it but if not, perhaps a quick note in `?image_read`?

**Comment by jeroen** [comment]
Most embedded images like `logo` or `wizard` or `rose` are also preloaded.
