### ISSUE TITLE
Request: allow define for image_write

### ISSUE THREAD

**Issue by wch** [ropensci/magick#258]
Sometimes I want to write an image with certain options defined. For example, from the command line, this will write a JPEG with a max size of 100kB:

```
convert input.jpg -define jpeg:extent=100kb output.jpg
```

It would be useful to be able to things like this with `image_write()`.

**Comment by jeroen** [comment]
Probably similar to https://github.com/ropensci/magick/commit/f280d53671bfbdd91918381b54fb207d3db62cde

**Comment by jeroen** [comment]
As of magick 2.5.0 you can now do:

```r
image_write(img, 'out.jpg', defines=c('jpeg:extent'='400kb'))
```

**Comment by jeroen** [comment]
This is on CRAN now.
