### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by bersbersbers** [ropensci/magick#260]
Hi,
I noticed that loading a bunch of images (png format, 2400x1800, no alpha channel that I am aware of), which should require some 2400x1800x3 bytes in memory, so around 13 megabytes per image, consumes approximately 50 megabytes per image (measured by `top`). This means the simple procedure of merging 200 of these png files in a gif file requires at least 10 GB of memory just to read the images. During the course of the conversion (see code below), memory usage increases to just under 30 GB, which I find an insane amount. The final gif is some 30 MB.
```
        pngs <- magick::image_read(frames, strip = TRUE)
        gifs <- magick::image_animate(pngs, fps = fps, dispose = "previous")
        magick::image_write(gifs, filename)
```

Are there options that I can use to reduce the memory requirements? Is there some streaming approach where files are read and written in batches?

**Comment by jeroen** [comment]
Can you try `image_write_gif()` instead of `image_animate()`

**Comment by bersbersbers** [comment]
This doesn't work too badly for me, with peak memory usage of 3 GB.
```
        batch_size <- 10
        batches <- split(frames, ceiling(seq_along(frames) / batch_size))
        batch_gifs <- c()
        for (batch in seq_along(batches)) {
            # inspired by gganimate::magick_renderer() (magick_renderer.R)
            pngs <- magick::image_read(batches[[batch]], strip = TRUE)
            # dispose = "previous" required to fix empty n>1 GIF frames
            gifs <- magick::image_animate(pngs, fps = fps, dispose = "previous")
            batch_gifs[batch] <- tempfile(fileext = ".gif")
            magick::image_write(gifs, batch_gifs[batch])
            invisible(gc())
        }
        gifs <- magick::image_read(batch_gifs, strip = TRUE)
        unlink(batch_gifs)
        magick::image_write(gifs, filename)
```

**Comment by jeroen** [comment]
Creating gifs is just incredibly expensive because. I recommend you use gifski with `image_write_gif()`, or even better and actual video format with `image_write_video`.
