### ISSUE TITLE
image_ggplot generates an upside down ggplot object

### ISSUE THREAD

**Issue by sqli68** [ropensci/magick#266]
Not sure how and why this bug happens this way as the bug seems elaborate. The bug fixes are straightforward. In the original source code image_ggplot, you can see two things rendering this bug. First of all, it calls scale_y_reverse() and in annotation raster function, it is passed a minus value of height.

`image_ggplot <- function(image, interpolate = FALSE) {
  info <- image_info(image)
  ggplot2::ggplot(data.frame(x = 0, y = 0), ggplot2::aes_string('x', 'y')) +
    ggplot2::geom_blank() +
    ggplot2::theme_void() +
    ggplot2::scale_y_reverse() +
    ggplot2::coord_fixed(expand = FALSE, xlim = c(0, info$width), ylim = c(0, info$height)) +
    ggplot2::annotation_raster(image, 0, info$width, -info$height, 0, interpolate = interpolate) +
    NULL
}`

**Comment by steffengreup** [comment]
Example of upside down ggplot:

``` r
library(magick)
#> Linking to ImageMagick 6.9.9.14
#> Enabled features: cairo, freetype, fftw, ghostscript, lcms, pango, rsvg, webp
#> Disabled features: fontconfig, x11

plot(logo)

# Plot image with ggplot2
library(ggplot2)
```

![](https://i.imgur.com/sG9KLWt.png)

``` r
myplot <- image_ggplot(logo)
myplot
```

![](https://i.imgur.com/dAesotm.png)

<sup>Created on 2020-10-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by steffengreup** [comment]
It seems this can be fixed by reversing the sign for info$height in 2 places:

reprex({
  
  library(magick)
  
  image_ggplot_alt <- function (image, interpolate = FALSE) 
  {
    info <- image_info(image)
    ggplot2::ggplot(data.frame(x = 0, y = 0), ggplot2::aes_string("x", 
                                                                  "y")) + ggplot2::geom_blank() + ggplot2::theme_void() + 
      ggplot2::scale_y_reverse() + ggplot2::coord_fixed(expand = FALSE, 
                                                        xlim = c(0, info$width), ylim = c(0, -info$height)) + 
      ggplot2::annotation_raster(image, 0, info$width, info$height, 
                                 0, interpolate = interpolate) + NULL
  }
  
  myplot <- image_ggplot_alt(logo)
  
  myplot
  
})

**Comment by steffengreup** [comment]
It seems this can be fixed by reversing the sign for info$height in 2 places:

``` r

library(magick)
#> Linking to ImageMagick 6.9.9.14
#> Enabled features: cairo, freetype, fftw, ghostscript, lcms, pango, rsvg, webp
#> Disabled features: fontconfig, x11

image_ggplot_alt <- function (image, interpolate = FALSE) 
{
  info <- image_info(image)
  ggplot2::ggplot(data.frame(x = 0, y = 0), ggplot2::aes_string("x", 
                                                                "y")) + ggplot2::geom_blank() + ggplot2::theme_void() + 
    ggplot2::scale_y_reverse() + ggplot2::coord_fixed(expand = FALSE, 
                                                      xlim = c(0, info$width), ylim = c(0, -info$height)) + 
    ggplot2::annotation_raster(image, 0, info$width, info$height, 
                               0, interpolate = interpolate) + NULL
}

myplot <- image_ggplot_alt(logo)

myplot
```

![](https://i.imgur.com/4RfXloY.png)

<sup>Created on 2020-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jeroen** [comment]
This only seems to happen on Windows, and it smells like a bug in R.

**Comment by jeroen** [comment]
This may be an ImageMagick 6 vs 7 things. The picture looks OK on IM7, but is upside-down with IM6.

**Comment by jeroen** [comment]
There seems to be a bug in ggplot2, or perhaps the R graphics device: https://github.com/tidyverse/ggplot2/issues/4230

**Comment by jeroen** [comment]
Workaround added via https://github.com/ropensci/magick/pull/277
