### ISSUE TITLE
Request: image_convert to take interlace argument

### ISSUE THREAD

**Issue by mikemahoney218** [ropensci/magick#268]
It would be awesome if `image_convert` provided support for the [interlace](https://imagemagick.org/MagickStudio/Interlace.html) option in order to specify interlacing methods when converting to raw formats. This enables the raw formats to be imported into other programs which expect specific interlacing methods.

**Comment by mikemahoney218** [comment]
This was resolved by #269, closing the issue out now. Thanks again Jeroen :)

**Comment by jeroen** [comment]
This is on CRAN now.
