### ISSUE TITLE
image_montage

### ISSUE THREAD

**Issue by romainfrancois** [ropensci/magick#27]
I'm trying to use `image_montage` perhaps I don't know how, but I get: 

``` r
> image_read(files) %>% image_montage()
Fontconfig warning: line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf
Fontconfig warning: line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf
Error in eval(substitute(expr), envir, enclos) : 
  Magick: NoDecodeDelegateForThisImageFormat `' @ error/blob.c/ImagesToBlob/1813
> 
> traceback()
6: stop(list(message = "Magick: NoDecodeDelegateForThisImageFormat `' @ error/blob.c/ImagesToBlob/1813", 
       call = eval(substitute(expr), envir, enclos), cppstack = NULL))
5: .Call("magick_magick_image_write", PACKAGE = "magick", input, 
       format, quality)
4: magick_image_write(image, format, quality)
3: image_write(x, path = tmp)
2: `print.magick-image`(x)
1: function (x, ...) 
   UseMethod("print")(x)
```

This however seems to create something that makes sense: 

``` r
> montage <- image_read(files) %>% image_montage()
> str( montage )
Class 'magick-image' <externalptr> 
> montage[[1]]
4 channel 768x504 bitmap array: raw [1:4, 1:768, 1:504] ff ff ff ff ...
 - attr(*, "class")= chr [1:2] "bitmap" "reba"
```

but then: 

``` r
> montage
Error in eval(substitute(expr), envir, enclos) : 
  Magick: NoDecodeDelegateForThisImageFormat `' @ error/blob.c/ImagesToBlob/1813
```

This seems to work: 

``` r
image_write(montage, format = "jpeg", path = "/tmp/test.jpeg")
```

![test](https://cloud.githubusercontent.com/assets/2625526/18544023/11946be4-7b33-11e6-8290-44ca967a6c02.jpeg)

Also, it seems that the `image_montage` function does not offer the `geometry` (or any other option actually, e.g. background, etc ...) control as in the [underlying api](http://www.imagemagick.org/script/montage.php)

`files` that I use above is the list of [these images](https://github.com/tmm1/emoji-extractor/tree/master/images/160x160)

``` r
# git clone https://github.com/tmm1/emoji-extractor.git
files <- list.files( "emoji-extractor/images/160x160/", full.names = TRUE )
```

**Comment by romainfrancois** [comment]
relatedly 

```
$ locate fonts.conf
/Applications/Wondershare AllMyTube.app/Contents/Resources/fc/fonts/fonts.conf
/Library/Frameworks/R.framework/Versions/3.3/Resources/fontconfig/fonts/conf.avail/10-scale-bitmap-fonts.conf
/Library/Frameworks/R.framework/Versions/3.3/Resources/fontconfig/fonts/conf.d/10-scale-bitmap-fonts.conf
/Library/Frameworks/R.framework/Versions/3.3/Resources/fontconfig/fonts/fonts.conf
```

Is it talking about the `fonts.conf` from R  in this warning : 

```
> image_read(files) %>% image_montage()
Fontconfig warning: line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf
Fontconfig warning: line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf
Error in eval(substitute(expr), envir, enclos) : 
  Magick: NoDecodeDelegateForThisImageFormat `' @ error/blob.c/ImagesToBlob/1813
```

**Comment by jeroenooms** [comment]
Yeah that warning is sort of a bug. In the mac binary package I use `fonts.conf` from XQuartz but that one seems outdated :(

**Comment by jeroenooms** [comment]
You can get rid of the warning with `brew install imagemagick` and then installing from source

**Comment by jeroenooms** [comment]
This is sort of a bug. Magick uses it's internal image format when creating a montage, and I haven't implemented a previewer for that. Use `image_convert` to convert it to a regular format. For example:

```r
out <- image_read(files) %>% image_montage() %>% image_convert("png")
```

Also it seems that it limits the number of frames in the montage because `out` still contains 36 images:

```r
image_info(out)
out[1]
out[2]
out[3]
```

**Comment by romainfrancois** [comment]
Thanks, I guess this would just be a matter of adding some parameter to `image_montage` , e.g. `tile` etc ... I might have a go later, it does not look that hard to replicate what  you've done with other functions.

**Comment by jsta** [comment]
A `tile` parameter would be great! For now, I am using nested `image_append` for this purpose.

**Comment by hklinke** [comment]
Nested append is one way to go. 
Another: use ImageMagick via system(). ¯\_(ツ)_/¯
Or, if the result of montage is a list of images, use montage on that list again (not perfect but often sufficient).

**Comment by jeroen** [comment]
See [this topic](https://github.com/ropensci/magick/issues/41#issuecomment-513579423) for some references to collage / montages.
