### ISSUE TITLE
does magick support the 'perspective' operation of imageMagick?

### ISSUE THREAD

**Issue by dankelley** [ropensci/magick#273]
First and foremost, thanks for this great package.  It really is very helpful to have this way to access imageMagick functionality.

I wonder, is there any thought of adding a hook to the imagemagick "perspective" transform (see  http://www.imagemagick.org/Usage/distorts/#perspective)?  This would be quite useful in my work, and I'm guessing that other users of your package might also find it handy.

Please accept my apologies if it *is* in there.  I couldn't find it in my quick reads of the documentation, nor in my `git grep` explorations.

Again, thanks for the great package!  Dan.

**Comment by jeroen** [comment]
It wasn't there but I have added it now. Can try to install the latest version:

```r
remotes::install_github("ropensci/magick")
```

To test:
```
library(magick)
building <- demo_image('building.jpg')
image_distort(building, 'perspective', c(7,40,4,30,4,124,4,123,85,122,100,123,85,2,100,30))
```

**Comment by dankelley** [comment]
This works beautifully.  Thanks very much for the rapid response!

**Comment by jeroen** [comment]
This is on CRAN now.

**Comment by dankelley** [comment]
Excellent. Thanks for letting folks know.  Best regards.
