### ISSUE TITLE
Does the lib have `compare`?

### ISSUE THREAD

**Issue by gaborcsardi** [ropensci/magick#28]
It would be great to use the `phash` algorithm for testing images.

**Comment by jeroenooms** [comment]
There seems to be a [compare method](https://www.imagemagick.org/Magick++/Image++.html) but I am not sure if this is what you mean.

**Comment by gaborcsardi** [comment]
I mean sg like this: 
```
compare -metric PHASH black.png white.png diff.png
```
from here: https://github.com/MangoTheCat/visualTest/issues/19#issuecomment-247678627

**Comment by gaborcsardi** [comment]
That docs does not mention phash, so maybe it is not included? I thought command like imagemagick was just a wrapper on the lib....

**Comment by gaborcsardi** [comment]
The imagemagick source seems to have it, but I am not sure what this repo is exactly:
https://github.com/ImageMagick/ImageMagick/blob/eecd3e43c17f89bc9d0ffd9e1ce1836a66683b61/MagickCore/option.c#L1403

**Comment by jeroenooms** [comment]
@dlemstra is phash available in the C++ api?

**Comment by gaborcsardi** [comment]
Or any of the other metrics? I guess it's either all of them, or none.....

**Comment by jeroenooms** [comment]
Looks like there are some undocumented methods here: http://git.imagemagick.org/repos/ImageMagick/commit/41c73241c91f5a5debf9380cdcff10f26aa04cc3...

**Comment by jeroenooms** [comment]
OK found it :)

**Comment by dlemstra** [comment]
You can get the phash in ImageMagick 7 (https://github.com/ImageMagick/ImageMagick/blob/77328896b876314656427663695bc7b2c9be3f74/Magick%2B%2B/lib/Magick%2B%2B/Statistic.h). This has not yet been added to IM6.

**Comment by jeroenooms** [comment]
```r
frink <- image_read("https://jeroenooms.github.io/images/frink.png")
frink2 <- image_blur(frink)
image_compare(frink, frink2, metric = "phash")
```

**Comment by jeroenooms** [comment]
@dlemstra actually it seems to work in IM6

**Comment by dlemstra** [comment]
I'm sorry. I did not realize you wanted this for compare. Those classes can be used to get the perceptual hash of an image.

**Comment by jeroenooms** [comment]
@gaborcsardi implemented @ https://github.com/ropensci/magick/commit/ce8c0fcecfc6e3a8e80ee741f0ce34dd55640614. It returns a double, not sure how to interpet that.

**Comment by gaborcsardi** [comment]
@jeroenooms If it is big, then the images are very different. Zero means the same. I don't know if there is an upper limit. 

Thanks much for adding it, I'll try it. It would be great to work out what metrics are supported, but I can help with that.

**Comment by dlemstra** [comment]
All the MetricOptions from the link you posted earlier are supported.

**Comment by jeroenooms** [comment]
I added a link in the documentation to a list of supported types. It seems to work, comparing similar images (even if they are upside down) results in (nearly) zero. Comparing different images gives a higher value, though the scale seems to depend on the image at hand .

**Comment by gaborcsardi** [comment]
Cool, thanks much!
