### ISSUE TITLE
R Package Documentation similar to main Image Magick?

### ISSUE THREAD

**Issue by dcaud** [ropensci/magick#280]
A number of times I have wanted to use a series of functions documented elsewhere for the main Image Magick program. But I want to use these with your lovely R package. 

For example, I want to feather an image as documented here:

https://legacy.imagemagick.org/Usage/morphology/#distance_feather

Is there any documentation that could help me find the analogue of those functions in the R package?

**Comment by jeroen** [comment]
The R package builds on the imagemagick C++ API and sadly there is no one-on-one mapping between the command line tools. Sometimes you can look at the imagemagick C++ docs, in particular:  
 - https://www.imagemagick.org/Magick++/STL.html
 - https://www.imagemagick.org/Magick++/Image++.html

And then search in the R package where these methods are used.
