### ISSUE TITLE
Connection error in windows R CMD check

### ISSUE THREAD

**Issue by chilampoon** [ropensci/magick#283]
Hi,
I used magick in my package, and if I run `R CME check` on a Windows machine, I get a warning:
```
> ### ** Examples
> 
> exportImage(species="9606", output="fireworks", 
+                    format="jpg", quality=7)
Warning in file(con, "wb") :
   cannot open file 'C:\Users\magic\AppData\Local\Temp\RtmpWiDvne/working_dir\RtmpQFcjIl\file92c79ad5e1c9606.jpg?quality=7&flgInteractors=true&title=true&margin=15&diagramProfile=Modern&resource=TOTAL&fireworksCoverage=false': Invalid argument
   Error in file(con, "wb") : cannot open the connection
   Calls: exportImage ... vapply -> FUN -> paste0 -> download_url -> writeBin -> file
   Execution halted
```
The `exportImage()` returns a magick object.

It only occurs on Windows 10 but not macOS or Linux. 
Any resolution? Thanks!

**Comment by jeroen** [comment]
Can you point me to the package or log file? Does this happen in rstudio, or in the CI? I can't guess from this error message what the problem is.

**Comment by chilampoon** [comment]
> Can you point me to the package or log file? Does this happen in rstudio, or in the CI? I can't guess from this error message what the problem is.

Okay, this is the build report: http://bioconductor.org/spb_reports/ReactomeContentService4R_buildreport_20201027190227.html
The package is https://github.com/reactome/ReactomeContentService4R

**Comment by chilampoon** [comment]
Also I remember that there were some similar warnings when the Windows builder rebuilt the vignette -- it can't print the magick image, sorry I didn't save the error message. Then I changed to use the saved images in the vignette to prevent those errors...

**Comment by jeroen** [comment]
OK I see, there seems to be an issue with very long URLs. Minimimal example:

```r
url <- "https://reactome.org/ContentService/exporter/fireworks/9606.jpg?quality=7&flgInteractors=true&title=true&margin=15&diagramProfile=Modern&resource=TOTAL&fireworksCoverage=false"
magick::image_read(url)
```

To work around it, in your code [here](https://github.com/reactome/ReactomeContentService4R/blob/c78d50d592e2d2174b41911042727a6057d01bc5/R/exporters.R#L144) maybe you can first download the url to a local jpg file, and pass that to `image_read()`.

**Comment by jeroen** [comment]
I also fixed it in magick, but it may be a while before that lands on CRAN.

**Comment by chilampoon** [comment]
Oh OK, but the goal of the `exportImage()` is just to download an image with the long url, not to process the image..

**Comment by chilampoon** [comment]
So I installed the lastest magick and ran R CMD check on my local Windows machine again, the warning was gone. Thanks for the fix.
