### ISSUE TITLE
After last update (2.5.0) does not read file with diacritics in file name anymore

### ISSUE THREAD

**Issue by theobroekman** [ropensci/magick#285]
After last update (2.5.0) does not read a file with diacritics in the filename anymore.
OS is Windows 10.
Example with ê: 
This works:
    image_read("O:/R/betastats/Beta-prikkel.png")
This does not work anymore:
    image_read("O:/R/betastats/Bêta-prikkel.png")
Error in magick_image_readpath(enc2native(path), density, depth, strip,  : 
  rsession.exe: UnableToOpenBlob `O:\R\betastats\Bêta-prikkel.png': No such file or directory @ error/blob.c/OpenBlob/2924

**Comment by jeroen** [comment]
@dlemstra dit something change wrt the expected encoding of windows filepaths?

**Comment by dlemstra** [comment]
This should still work the same as it used to do. Are you using the C++ api?

**Comment by jeroen** [comment]
Yes we use STL `readImages()` function.

**Comment by dlemstra** [comment]
Can you make this easily reproducible for me?

**Comment by jeroen** [comment]
@dlemstra it's a bit difficult to create an example with a string literal, because that depends on the encoding assumed for string literals  by the compiler. But maybe the example below clarifies? 

Basically, previously, Magick++ would use native string encoding, and now it assumes UTF-8 strings. Maybe this is not a bug but a feature, I don't know.




```cpp
/* Encoding used by Magick++. For filenames. 
 * This works: ./a.exe test.png
 * This does not work: ./a.exe bêta.png
 */
#include <iostream>
#include <cstdio>
#include <windows.h>
#include <Magick++.h> 
using namespace Magick;

static const char *formatError(DWORD res){
  static char buf[1000], *p;
  FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
                NULL, res,
                MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
                buf, 1000, NULL);
  p = buf+strlen(buf) -1;
  if(*p == '\n') *p = '\0';
  p = buf+strlen(buf) -1;
  if(*p == '\r') *p = '\0';
  p = buf+strlen(buf) -1;
  if(*p == '.') *p = '\0';
  return buf;
}

int main(int argc, char *argv[]) {
  const char *filename = argv[1];
  Magick::Image image("logo:");
  image.write(std::string(filename));
  if(GetFileAttributesA(filename) == INVALID_FILE_ATTRIBUTES){
  	printf(formatError(GetLastError()));
  	return 1;
  }
  return 0;
}

```

**Comment by jeroen** [comment]
@theobroekman I have pushed an experimental fix, can you try it:

```r
install.packages("magick", repos = 'https://dev.ropensci.org')

**Comment by theobroekman** [comment]
Thanks Jeroen, works perfectly as it did before!

**Comment by jeroen** [comment]
This is on cran now in magick 2.5.1
