### ISSUE TITLE
Why are there fontconfig config files included?

### ISSUE THREAD

**Issue by QuLogic** [ropensci/magick#286]
Starting with 2.5.1, there are suddenly a whole bunch of fontconfig files in the CRAN tarball. This is not mentioned in the NEWS, which seems like mostly a bugfix, and the [diff](https://github.com/ropensci/magick/compare/v2.5.0...v2.5.1) between the v2.5.0 and v2.5.1 tags don't seem to show anything saying they should be there.

Was their addition intentional?

**Comment by jeroen** [comment]
Shit, no

**Comment by jeroen** [comment]
They were included by accident, you can ignore them. I'll remove them in a next release.

**Comment by QuLogic** [comment]
OK, I'll remove them during build to leave them out of the package.

**Comment by jeroen** [comment]
Thanks for catching this, sorry again.

**Comment by jeroen** [comment]
I have pushed a new release to CRAN
