### ISSUE TITLE
Masking/clipping an image

### ISSUE THREAD

**Issue by royfrancis** [ropensci/magick#288]
I am trying to mask an image using a shape and I am not sure how to get it to work using R.

Here is a working example.

Read image

```
library(magick)
path <- "https://cdn.pixabay.com/photo/2016/08/17/21/12/people-1601516_960_720.jpg"
img <- magick::image_read(path)
img
```

![](https://i.stack.imgur.com/KO33R.jpg)

Convert to square aspect ratio

```
ii <- magick::image_info(img)
ii_min <- min(ii$width,ii$height)
img1 <- magick::image_crop(img, geometry=paste0(ii_min,"x",ii_min,"+0+0"),repage=TRUE)
img1
```

![](https://i.stack.imgur.com/yJrbs.jpg)

Circular mask

I have got this circular mask to work in shell.

    convert -size 500x500 xc:white -fill cropped.jpeg -draw "circle 250,250 250,1" circ.jpg

![](https://i.stack.imgur.com/qyiyw.jpg)

How can I achieve similar results using R?

**Comment by jeroen** [comment]
There are many ways to do this, here is one example:


```r
library(magick)
img <- "https://cdn.pixabay.com/photo/2016/08/17/21/12/people-1601516_960_720.jpg" %>%
  magick::image_read() %>%
  image_crop('480x480')

fig <- image_draw(image_blank(480, 480))
symbols(240, 240, circles = 230, bg = 'white', inches = FALSE, add = TRUE)
dev.off()

image_composite(img, fig, operator = 'copyopacity') %>%
  image_background('white')

```

**Comment by royfrancis** [comment]
Thank you for the quick reply and example!
