### ISSUE TITLE
Fontconfig warning: line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf

### ISSUE THREAD

**Issue by jeroen** [ropensci/magick#29]
Can appear on macOS when you have an old version of fontconfig. Upgrading XQuartz to the latest XQuartz-2.7.10 resolves the issue: https://www.xquartz.org/releases/index.html.

Upstream issue: [bug 97493](https://bugs.freedesktop.org/show_bug.cgi?id=97493).

**Comment by marks-yag** [comment]
It seems doesn't work, finally I removed the "<blank/>" block in fonts.conf. :(

**Comment by jeroenooms** [comment]
Did you get the rc version of xquartz?

**Comment by piotrp88** [comment]
I had this issue in another context (plotting graphs on R and macOS Sierra) and installing XQuartz-2.7.11 solved it. I had 2.7.9 installed. Thank you :)

**Comment by jeroen** [comment]
We now ship our own fontconfig files.
