### ISSUE TITLE
Convert png to eps

### ISSUE THREAD

**Issue by msgoussi** [ropensci/magick#290]
convert png to eps

![Afghanistan_Polar](https://user-images.githubusercontent.com/18138496/101280181-b68ba200-37d8-11eb-96d6-c83cc42993d6.png)

I am trying to convert attached png to eps in order to use in Latex, however 
p <- image_read("Afghanistan_Polar.png")
image_write(p, "Afghanistan_Polar.eps", format = "eps")
the new eps resolution is not good at all.
Please advise.

**Comment by jeroen** [comment]
png is a bitmap format (pixels), whereas eps is a vector format (lines and shapes). You cannot convert a bitmap into a vector in any meaningfull way. Why do you want eps?

**Comment by msgoussi** [comment]
I do need images in eps because I want to use them in latex later on.

**Comment by jeroen** [comment]
I think you can use png or jpeg images in latex?
