### ISSUE TITLE
CRAN Mac binary doesn't support HEIC

### ISSUE THREAD

**Issue by wch** [ropensci/magick#292]
With the Mac binary package from CRAN, magick isn't able to read in HEIC files, but it does work if I build the package locally. This isn't exactly a bug in magick, but it would be nice if it did support HEIC without having to install stuff from homebrew and compile from source. 

This is what happens with the binary package from CRAN:

```
> magick::image_read('image.heic')
Error in magick_image_readpath(path, density, depth, strip, defines) : 
  rsession: NoDecodeDelegateForThisImageFormat `HEIC' @ error/constitute.c/ReadImage/566
```

This is what happens with the locally-built package:

```
> install.packages("magick", type = "source")
> magick::image_read('image.heic')
  format width height colorspace matte filesize density
1   HEIC  4032   3024      YCbCr FALSE  1485993 +72x+72
```

**Comment by jeroen** [comment]
Yeah I try to keep the binary somewhat reasonably sized. But if you would like this, you can send a PR to https://github.com/autobrew/homebrew-core/blob/master/Formula/imagemagick@6.rb

**Comment by jeroen** [comment]
I have added libheic and dependencies to the mac binary package. You can install the latest mac binary from:

```r
install.packages("magick", repos = "https://ropensci.r-universe.dev")
```

I am now also working on adding this in the windows stack.

**Comment by wch** [comment]
Great, thanks!

**Comment by jeroen** [comment]
This should now also be available in the Windows binaries. Thanks for the suggestion!

**Comment by jeroen** [comment]
magick 2.6.0 is on cran now.

**Comment by dmi3kno** [comment]
I don't want to open another issue, but if anyone is searching for HEIC support in magick, here are [some instructions](https://eplt.medium.com/5-minutes-to-install-imagemagick-with-heic-support-on-ubuntu-18-04-digitalocean-fe2d09dcef1) how to get ImageMagick compiled with heic support on Ubuntu.
I did not get it to work, but those were the guidelines I followed to get the dependencies installed.

**Comment by jeroen** [comment]
FWIW, heif should be natively supported starting ubuntu 22.04.
