### ISSUE TITLE
Compression and density options on convert

### ISSUE THREAD

**Issue by stephenturner** [ropensci/magick#293]
Great work here! I've used ImageMagick for years, scripting `system()` calls through R, but this would provide a much more robust solution. 

I can't seem to find the documentation I'm looking for for setting command line options to the `convert` command. A typical use case for me is to convert a PDF (one or multiple pages) into a TIF (one or multiple pages), with lossless lzw compression, at 300dp or in some cases 150 dpi. Here's how I'd do it on the command line.

```sh
# Get an example multi-page PDF to play with
wget https://www.senate.gov/artandhistory/history/resources/pdf/June1844_MorseTelegraphTest.pdf
# Convert it to a multi-page tif, lzw compressed, 300dpi.
convert -density 300 -compress lzw June1844_MorseTelegraphTest.pdf June1844_MorseTelegraphTest.tif
```

Here's the output tif (sorry, github won't let me upload files ending with .tif, so zipped a single image file instead).

[June1844_MorseTelegraphTest.tif.zip](https://github.com/ropensci/magick/files/5782572/June1844_MorseTelegraphTest.tif.zip)

Here's a screenshot of the image in preview, showing that it is 300 dpi, and showing multiple pages, and that the current compressed image is ~800kb in size.

![image](https://user-images.githubusercontent.com/460076/103913040-14602200-50d6-11eb-9ad0-c7efccb7f79b.png)

I've tried fussing around with `image_set_defines` and changing options on read/write, but can't seem to get this working. The code below doesn't support the compression, and instead of giving me an output tif at ~800kb, the uncompressed tif is nearly 60MB!

```r
library(magick)
i <- image_read_pdf("https://www.senate.gov/artandhistory/history/resources/pdf/June1844_MorseTelegraphTest.pdf")
o <- image_convert(i, "tif")
image_write(o, path="magickpkg-converted.tif", defines=c("compress:lzw"="", "density:300"=""))
```

Thanks for any tips you might have or pointers to documentation I might have missed!

**Comment by jeroen** [comment]
It turned out that this feature was not yet exposes so I added it. Can you try to install the latest version:

```r
install.packages("magick", repos = "https://ropensci.r-universe.dev")
```

And then this should work:

```r
library(magick)
url <- 'https://www.senate.gov/artandhistory/history/resources/pdf/June1844_MorseTelegraphTest.pdf'
input <- image_read_pdf(url, density = 300)
output <- image_convert(input, "tif")
image_write(output, 'uncompressed.tiff')
image_write(output, 'compressed.tiff', compression = 'lzw')
```

**Comment by stephenturner** [comment]
Beautiful! Works perfectly! Thanks for the quick update! 🙇 🙏

**Comment by jeroen** [comment]
magick 2.6.0 is on cran now.
