### ISSUE TITLE
Issues loading magick following installation

### ISSUE THREAD

**Issue by amsesk** [ropensci/magick#298]
I'm getting errors when loading magick into the R environment whether I'm explicitly loading it with `library(magick)` or another package is loading magick as a dependency, e.g., library(ggimage). No errors are thrown during magick installation - it finishes with 0 exit status when using `install.packages`.

```
Error in get(method, envir = envir) : 
  lazy-load database '/home/aimzez/R/x86_64-pc-linux-gnu-library/4.0/magick/R/magick.rdb' is corrupt
In addition: Warning message:
In get(method, envir = envir) : internal error -3 in R_decompress1
```

I'm on Arch Linux using the following versions of the magick-related libraries:

```
graphicsmagick 1.3.36-1
imagemagick 7.0.10.61-1
libmagick6 6.9.11.58-1
```

I wasn't having this problem a couple of days ago, so I suspect that the errors have something to do with the above Arch Linux packages getting updated, but am confused by the errors that I'm getting. That is, the errors aren't the normal "Error loading shared object file ...." and instead reference a corrupt file in my R library path. I have tried removing magick with `remove.packages` and reinstalling, but the error persists.

Thank you for your help in resolving this issue and thanks for the continued development of this library!

**Comment by jeroen** [comment]
The error `internal error -3 in R_decompress1` always means you simply need to restart R. This happens when you reinstall a package that is currently in use.

**Comment by amsesk** [comment]
Hah! That is a much simpler resolution than I was expecting. Thank you, I will remember this in the future.
