### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by adamsorbie** [ropensci/magick#305]
Hi, 

I'm unable compeltely to install the latest version of magick and it also seems to be affecting installation of other packages. I get the following error:  

```
Error in curl::curl_download(sprintf("https://github.com/rwinlib/imagemagick%s/archive/v%s.zip",  : 
  Timeout was reached: [] Connection timed out after 10000 milliseconds
```

I've tried installing from the tarball and I get the same error. Installing using the zip file works, but is not the latest version as far as I can tell (2.7), so when I try to update other packages I again receive the above error. 

Do you have any idea what's causing this? The output of my sessioninfo is below:

```
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10 compiler_4.0.4      tools_4.0.4         tinytex_0.30        xfun_0.21
 ```

**Comment by jeroen** [comment]
Apparently you cannot connect to github.com. This should solve itself later today when the updated binary package for Windows is on CRAN. For now you can use:

```r
install.packages("magick", type = 'binary')
```

**Comment by adamsorbie** [comment]
Ok great! Thanks.
