### ISSUE TITLE
reading pdf from R global environment and not an external url

### ISSUE THREAD

**Issue by andresmorago** [ropensci/magick#307]
Hello

Is there a chance the function `image_read_pdf` could read data from a global environment variable instead that from a url or external path?

I have read a pdf from a SFTP server and stored it as binary in a variable and this will throw an error

`image1 = image_read_pdf (data, density=200) `

**Comment by jeroen** [comment]
What type is `data` in your case?

**Comment by andresmorago** [comment]
thanks. i was hoping to omit the additional write to folder between the SFTP get and the PDF read since i plan to read multiple files from an external server

**Comment by jeroen** [comment]
You can try this:

```r
read_raw_pdf <- function(data){
  con <- rawConnection(data)
  on.exit(close(con))
  magick::image_read(pdftools::pdf_render_page(con))
}
```

**Comment by andresmorago** [comment]
thanks so much!!  it works!

**Comment by andresmorago** [comment]
hello again
im trying to improve the quality of the scanned file but no luck so far. i included the `density `flag but it is not being considered

read_raw_pdf <- function(data){
  con <- rawConnection(data)
  on.exit(close(con))
  magick::image_read(pdftools::pdf_render_page(con), density =250)
}

**Comment by andresmorago** [comment]
i think ive got the quality to work. im unsure if this will save all the pdf pages into the same object. will test
```
read_raw_pdf <- function(data){
  con <- rawConnection(data)
  on.exit(close(con))
  magick::image_read(pdftools::pdf_render_page(con, dpi = 250))
  }
```

**Comment by jeroen** [comment]
The `pdf_render_page()` function has a second argument to specify which page you want to render.
