### ISSUE TITLE
can image_read_pdf read a raw vector?

### ISSUE THREAD

**Issue by andresmorago** [ropensci/magick#308]
Hello

Im trying to pass a file coming from a STFP server to the `image_read_pdf` function.  Is there a way this function can take a binary vector instead of a path?

This is what im trying but its not working
```
data1 <- getBinaryURL (url = url, userpwd=userpwd)
image2 = magick::image_read_pdf (data1, density=250) 
```

this does work
`image2 = magick::image_read_pdf ("document1.pdf", density=250) `

**Comment by jeroen** [comment]
Why are you asking the same question again as last week? https://github.com/ropensci/magick/issues/307#issuecomment-821520872
