### ISSUE TITLE
Performance degradation with repeated function calls

### ISSUE THREAD

**Issue by jniedballa** [ropensci/magick#309]
Hello, 
I am processing a few thousand images with magick, and sometimes identical operations are orders of magnitude slower when called again. It happened with image_flop() and image_flip(), I didn't test any other functions. 

```
frink <- image_read("https://jeroen.github.io/images/frink.png")
frink2 <- rep(frink, 1000)

system.time(frink2_flop1 <- image_flop(frink2))
   user  system elapsed 
   0.28    0.15    0.44 

system.time(frink2_flop2 <- image_flop(frink2))
   user  system elapsed 
   0.34    0.14    0.48 

system.time(frink2_flop3 <- image_flop(frink2))
   user  system elapsed 
   3.92   30.36  249.95 
```
In this example, it seemed to reliably be the third run that took very long. 

CPU utilization was low (a few %) with a few Mb/s (at most) disk write. Files of 765kb each were written in the Temp directory very slowly, at about 1 file /second.(e.g. magick-1zLZRgKpNqlSN5_faVJm4Yp6ssY6jVRM). 

Also, when running the following lines repeatedly it worked fine and didn't hang.
```
frink2_flop2 <- image_flop(frink2)
rm(frink2_flop2)
```

Doing the following repeatedly, it did hang:
```
frink2_flop3 <- image_flop(frink2)
rm(frink2_flop3)
```

The following seemed to work reliably: 
```
> replicate(10, 
+ system.time(image_flop(frink2))
+ )
           [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
user.self  0.23 0.29 0.30 0.25 0.27 0.25 0.25 0.28 0.27  0.28
sys.self   0.22 0.23 0.19 0.23 0.31 0.25 0.23 0.25 0.25  0.21
elapsed    0.45 0.54 0.49 0.48 0.57 0.50 0.48 0.53 0.51  0.48
user.child   NA   NA   NA   NA   NA   NA   NA   NA   NA    NA
sys.child    NA   NA   NA   NA   NA   NA   NA   NA   NA    NA

> replicate(10, 
+           system.time(frink2_flop <- image_flop(frink2))
+ )
           [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
user.self  0.18  0.3  0.3 0.35 0.33 0.29 0.34 0.18 0.29  0.28
sys.self   0.31  0.2  0.2 0.16 0.18 0.20 0.18 0.30 0.18  0.22
elapsed    0.50  0.5  0.5 0.50 0.50 0.50 0.53 0.48 0.47  0.50
user.child   NA   NA   NA   NA   NA   NA   NA   NA   NA    NA
sys.child    NA   NA   NA   NA   NA   NA   NA   NA   NA    NA
```

I am at a loss here. Am I doing something I'm not supposed to do? And is there any way to prevent this from happening? 

R becomes unresponsive, and usually the only solution is to terminate R it and start over, which is quite inconvenient. 

Thank you for your help and best regards,
Jürgen

**Comment by jeroen** [comment]
It could be that your system is running out of memory. You could test this by running `gc()` after `rm()` to force releasing the memory directly. Usually you don't need to do this, as R will automatically run `gc()` once in a while.

Another way to test is calling `image_destroy()` on the image to force releasing the memory directly.

**Comment by jniedballa** [comment]
I just tested the following:
```
system.time({
  frink2_flop1 <- image_flip(frink2)
  rm(frink2_flop1)
  gc()
})
system.time({
  frink2_flop2 <- image_flip(frink2)
  rm(frink2_flop2)
  gc()
})
system.time({
  frink2_flop3 <- image_flip(frink2)
  rm(frink2_flop3)
  gc()
})
```

- With `rm()` + `gc()`, it worked. 
- With `rm()` only `#gc()`, it also worked. 
- With both `#rm()` and #`gc()`, the first two worked, and it consistently hang on the third block. 
- When i didn't assign a variable (only running image_flip(frink2)), it worked also. 

So it happens only when assigning to variables. 

I'm testing this on a machine with 16Gb memory. Memory utilization currently sitting around 40% in total, with RStudio using 2.6Gb, >9Gb memory available, and it hangs. Just now image_flip() with 1000 frink images first took 0.4 seconds in the first two calls, then 440 seconds in the third call.

1000 frink images are around 74Mb only.

```
> sum(image_info(frink2)$filesize) / 1e6
[1] 73.494
```

I also first encountered the problem when working on around 2000 images of 256x160 pixels each or a machine with 128Gb memory, so find it hard to imagine memory would be a limiting factor. At the time more than 100Gb of memory were free. 

So there seems to be plenty of free memory on these quite capable machines, and the data sets are small. Can memory still be an issue somehow? And can you reproduce the issue?

Also, in my normal workflow removing images would not be appropriate, since I wish to create more images (data augmentation for deep learning). It was more for demonstration of the issue and narrowing it down. 

The main problem is the code being extremely slow after a few executions, despite plentiful system resources and just small data sets. 

Thank you for your help.

**Comment by jniedballa** [comment]
@jeroen any thoughts what the issue may be, or how to solve it?

**Comment by jeroen** [comment]
I think you are hitting a memory limit in imagemagick, after which it starts swapping to disk, which is much slower. I have [added a diagnostic](https://github.com/ropensci/magick/commit/86433dc73f044363738843ec571c017dc19bed89) function, can you please try to install the dev version of this R package?

```r
# Run in a clean empty R session!
remotes::install_github("ropensci/magick")
``` 

And then run:

```r
magick:::magick_resource_limits()
```

And tell me what you get on your machine? I noticed on my Windows machinee, the `memory` limit defaults to 2GB, even though the machine has much more.

**Comment by jniedballa** [comment]
Thank you. This is the output: 

```
> magick:::magick_resource_limits()
$area
[1] 4294967296

$thread
[1] 1

$map
[1] 4294967296

$memory
[1] 2147483648

$disk
[1] 9.223372e+18

$file
[1] 64
```

It was exactly the same on both machines I tested (Win10, 16Gb and 128Gb RAM). 

Would it be possible to increase the memory limit then?

**Comment by jeroen** [comment]
Yes I found the bug: https://github.com/ImageMagick/ImageMagick/issues/3684
Will try to release a fix soon.

**Comment by jniedballa** [comment]
Thank you good Sir. Much appreciated.

**Comment by jeroen** [comment]
This should be fixed in the latest versions. Can you try again?
I have also retroactively updated the current cran version magick 2.7.2, so once CRAN rebuilds the binaries (usually once per week) those should be fixed as well.

**Comment by jniedballa** [comment]
Thank you so much, it works now (using the github version). On the laptop with 16Gb memory, memory limit was shown as 8.532 Gb, on the 128Gb machine as 68.672 Gb. 
The functions didn't hang anymore and everything went smoothly, fantastic.

I noticed though that 1000 frink images use 700-800Mb of memory (which probably led to the out of memory error on the third call in the first post, when it exceeded 2Gb). Just wondering if that is normal and expected, since frink.png is 72kb only, but occupies 10x more memory than the actual file size?

**Comment by jeroen** [comment]
I'm not sure about that either. I would expect one image to use `w*h*rgba` memory, so in the case of frink that would be 200 *  445 * 4 = 178kb per image. So if you make 1000 copies that would be around 180MB. But perhaps imagemagick is keeping additional metadata in memory, not sure.

**Comment by jniedballa** [comment]
Ok, thank you. Well, I'm just glad the main issue is solved and the memory problem fixed. Thank you very much for your help!
