### ISSUE TITLE
image_read and image_append corrupting GIFs

### ISSUE THREAD

**Issue by pschloss** [ropensci/magick#315]
I'm trying to reproduce an example from the `gganimate` package that shows [how to put two animations side by side](https://github.com/thomasp85/gganimate/wiki/Animation-Composition). I'm able to generate the two GIFs, which are stored as `a_gif` and `b_gif`. Each of those has 100 frames. When I run the following...

```R
a_mgif <- image_read(a_gif)
b_mgif <- image_read(b_gif)
```

Both `a_mgif` and `b_mgif` end up having 60 frames. If I load either `a_mgif` or `b_mgif`, those images look fine.

![a_mgif](https://user-images.githubusercontent.com/1264132/116617393-c7fe5380-a90b-11eb-994f-d88a653bfc57.gif)
![b_mgif](https://user-images.githubusercontent.com/1264132/116617408-ccc30780-a90b-11eb-84fe-eb878867e42f.gif)

However, when I then do the following...

```R
new_gif <- image_append(c(a_mgif[1], b_mgif[1]))

for(i in 2:61){
  combined <- image_append(c(a_mgif[i], b_mgif[i]), stack=FALSE)
  new_gif <- c(new_gif, combined)
}

new_gif
anim_save("double.gif", new_gif)
```

The output gets pretty funky. There's weird distortion and ghosting.

![double](https://user-images.githubusercontent.com/1264132/116617452-d6e50600-a90b-11eb-8bae-0104d2f40a21.gif)

Any ideas on what might be wrong? I think all of my packages are up to date...

```R
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magick_2.7.1    gganimate_1.0.7 ggplot2_3.3.2   dplyr_1.0.2    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        rstudioapi_0.13   magrittr_2.0.1    hms_0.5.3        
 [5] progress_1.2.2    tidyselect_1.1.0  munsell_0.5.0     colorspace_2.0-0 
 [9] R6_2.5.0          rlang_0.4.10      fansi_0.4.1       plyr_1.8.6       
[13] tools_4.0.5       grid_4.0.5        gtable_0.3.0      utf8_1.1.4       
[17] cli_2.1.0         gifski_1.4.3      withr_2.3.0       ellipsis_0.3.1   
[21] assertthat_0.2.1  digest_0.6.27     tibble_3.0.4      lifecycle_0.2.0  
[25] crayon_1.3.4      farver_2.0.3      tweenr_1.0.2      purrr_0.3.4      
[29] vctrs_0.3.5       glue_1.4.2        labeling_0.4.2    stringi_1.5.3    
[33] compiler_4.0.5    pillar_1.4.6      generics_0.1.0    scales_1.1.1     
[37] prettyunits_1.1.1 pkgconfig_2.0.3  
```

**Comment by jeroen** [comment]
Instead of `anim_save()` can you try to use:

```r
image_write_gif(new_gif, "test1.gif")
```

Or try to use

```r
new_gif2 <- image_animate(gif)
image_write(new_gif2, "test2.gif")
```

And see if either of those works?

**Comment by pschloss** [comment]
Thanks for the feedback. Both `test1.gif` and `test2.gif` give the same output, which actually looks worse...

![test1](https://user-images.githubusercontent.com/1264132/116696292-b8285300-a98f-11eb-8a2f-a0f3cbf5c55d.gif)

Picking up on your comment that the figures are different sizes - if I do...

```R
a_gif <- animate(a, width = 240, height = 240)
b_gif <- animate(b, width = 240, height = 240)

a_mgif <- image_read(a_gif)
b_mgif <- image_read(b_gif)
```

I noticed that besides there only being 61 rather than 100 frames in `a_mgif` and `b_gif`, that the heights seem to vary considerably...

```R
> a_mgif
# A tibble: 61 x 7
   format width height colorspace matte filesize density
   <chr>  <int>  <int> <chr>      <lgl>    <int> <chr>  
 1 GIF      240    240 sRGB       TRUE    112551 72x72  
 2 GIF      240    193 sRGB       TRUE    112551 72x72  
 3 GIF      240    191 sRGB       TRUE    112551 72x72  
 4 GIF      240    186 sRGB       TRUE    112551 72x72  
 5 GIF      240    183 sRGB       TRUE    112551 72x72  
 6 GIF      240    169 sRGB       TRUE    112551 72x72  
 7 GIF      240     83 sRGB       TRUE    112551 72x72  
 8 GIF      240     86 sRGB       TRUE    112551 72x72  
 9 GIF      240    176 sRGB       TRUE    112551 72x72  
10 GIF      240    168 sRGB       TRUE    112551 72x72  
# … with 51 more rows
```

The height of `b_mgif` also fluctuates. Is there possibly a problem with `image_read()`? When I view the GIFs separately, they look fine.

**Comment by jeroen** [comment]
OK I understand the problem now. Because we save to a gif, and then read again, we need to coalesce the input.

The gif format is kind of weird, only the first frame is saved in full. All subsequent frames are only saved partially, and then played on top of the previous one. So that is why they all have different heights, and look weird. 

In the new version I added a function `image_coalesce` but also make the default to coalesce when reading gif images.
