### ISSUE TITLE
Error in image_draw(): "figure margins too large" with very small images (solution proposed)

### ISSUE THREAD

**Issue by MatteaE** [ropensci/magick#317]
Offending code (R 3.6.3, magick 2.6.0, ImageMagick 6.9.10.23, Ubuntu 20.04, 1920x1200 resolution):

```R
library(magick)
image_draw(image_blank(30,30))
```
```
Error in graphics::plot.new() : figure margins too large
```

From both console and RStudio. No value of parameter `mar` passed to `image_draw()` fixes the issue. Also resizing the plot panel in RStudio has no effect.

**Solution** (on my system at least): swap two lines in `magick:::setup_device()`, from 

```R
graphics::plot.new()
graphics::par(mar = mar)
```
to
```R
graphics::par(mar = mar)
graphics::plot.new()
```

Not sure if this breaks anything else :-)

**Comment by Balaika** [comment]
This issue still exists with magick version 2.8.0. The MatteaE work around is still valid.

**Comment by jeroen** [comment]
Thanks! I committed it now.
