### ISSUE TITLE
Request for further instructions on how to draw additional shapes

### ISSUE THREAD

**Issue by SugarRayLua** [ropensci/magick#321]
Hello. I'm and amateur R programmer who recently found and started using your magick package on my Alpine linux system and really like it. Would you please additionally clarify if and how one might use the image_draw command to:

1) fill in a drawn rectangle (would one use image_fill and could you provide an example)?

2) draw lines other than a horizontal line across the a full image as in the example on the magick website (i.e. how to draw a vertical line or a line from pixel point x1y1 to x2y2)?

3) draw a circle (there seems to be an example of drawing a circle on the magick website but it is intermixed with other code; it would be helpful if you could provide an 1 line example of how to draw a circle/fill in a circle)?

4) paint a specific pixel region with color? The magick website seems to indicate one could do this with the "fuzz" option but it would be also helpful if you could perhaps provide a 1 line code example showing how to fill in half of a rectangle with color.

I appreciate any further suggestions you could provide.

Thank you.

Sincerely,

Mike

**Comment by jeroen** [comment]
You can use the standard methods from the R graphics device, for exaple: https://cran.r-project.org/web/packages/magick/vignettes/intro.html#Drawing_device
