### ISSUE TITLE
Problem installing R magick package on google colab

### ISSUE THREAD

**Issue by max-poltora** [ropensci/magick#324]
Hello, I am seeking help with issue installing R `magick` package on google colab. First, I tried to do it in general way:
`install.packages("magick")`
and I get the output as follows:

>Installing package into ‘/usr/local/lib/R/site-library’
>(as ‘lib’ is unspecified)
>Warning message in install.packages("magick"):
>“installation of package ‘magick’ had non-zero exit status”

None of alternative solutions that I have found on kaggle like [this one](https://www.kaggle.com/questions-and-answers/111229) or [this one](https://www.kaggle.com/product-feedback/124873) worked in my case.

Can you please help me to figure out, what is the problem?

**Comment by jeroen** [comment]
Can you please provide the full output of the install.packages command.

**Comment by gongx030** [comment]
@max-poltora You need to have `libmagick++-dev` installed first: 

```
apt-get install libmagick++-dev
```

**Comment by AlejandroDGR** [comment]
@gongx030 that does not work for me:
```
system("apt-get install libmagick++-dev")
install.packages("magick")
```
The following error arises too:
```
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Warning message in install.packages("magick"):
“installation of package ‘magick’ had non-zero exit status”
```

**Comment by AlejandroDGR** [comment]
The error I get when running `install.packages("magick")` is the same:
```
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Warning message in install.packages("magick"):
“installation of package ‘magick’ had non-zero exit status”
```
I have executed it in the R Kernel of Colab. I don't know if this is what you are referring to when saying " run an R session under colab console".

**Comment by gongx030** [comment]
> 

This should work for now: 
```
system('add-apt-repository -y ppa:cran/imagemagick')
system('apt-get update')
system("apt-get install libmagick++-dev")
install.packages("magick")
```

**Comment by AlejandroDGR** [comment]
@gongx030, that works for me!

Thanks a lot!

**Comment by lolsaless** [comment]
Thank you so much!

**Comment by OffByOne37** [comment]
You are amazing @gongx030! Helped me a lot!
