### ISSUE TITLE
Configure file has Magick++-6.Q16 hard coded

### ISSUE THREAD

**Issue by lois54** [ropensci/magick#328]
When installing this library I had to open the tar file and edit the configure script changing:
PKG_LIBS="-lMagick++-6.Q16"
to:
PKG_LIBS="-lMagick++-7.Q16HDRI"
for my new install of imagemagick 7.1.0

**Comment by jeroen** [comment]
If you have `pkg-config` or `Magick++-config` on the PATH, the package will automatically get the correct flags. The default is really just a fallback.

**Comment by lois54** [comment]
When I used INCLUDE_DIR and LIB_DIR I got this:
```
R CMD INSTALL  --configure-vars='INCLUDE_DIR=/app/imagemagick-7.1.0@i86-rhel7.0/include/ImageMagick-7 LIB_DIR=/app/imagemagick-7.1.0@i86-rhel7.0/lib' ./magick_2.7.3.tar.gz
* installing to library ‘/app/R-4.1.0@i86-rhel7.0/lib64/R/library’
* installing *source* package ‘magick’ ...
** package ‘magick’ successfully unpacked and MD5 sums checked
** using staged installation
Found INCLUDE_DIR and/or LIB_DIR!
Using PKG_CFLAGS=-I/app/imagemagick-7.1.0@i86-rhel7.0/include/ImageMagick-7,
Using PKG_LIBS=-L/app/imagemagick-7.1.0@i86-rhel7.0/lib  -lMagick++-6.Q16

```
The issue is on the last line of the above.  After editing `configure` to reference the correct `-lMagick++-7.Q16HDRI` It  compiled  right away.
