### ISSUE TITLE
tutorial banana.gif not in package?  (image_read("") never stops)

### ISSUE THREAD

**Issue by RMHogervorst** [ropensci/magick#33]
Hi there,
I tried to follow the ropensci tutorial about magick, and I found an error. I'm using R 3.3.2 (also tried with previous version) on windows 10, 64 bit.

in 
```
# foreground
banana <- image_read(system.file("banana.gif", package = "magick"))
```
my r process doesn't stop. 
I have to terminate it. 

So I broke down the problem:

- When I search for the file with only `system.file("banana.gif", package = "magick")` it returns `""`
- when I do a `image_read("")` the r process hangs (?) or at least does not terminate or error. it just keeps going.

**Comment by RMHogervorst** [comment]
I downloaded the cran version of imagemagick btw

**Comment by jeroen** [comment]
Thanks! We should update the blog post. I have fixed the problem where R hangs for  `image_read("")`. You can get the banana from:

```r
banana <- image_read("https://jeroen.github.io/images/banana.gif")
```
