### ISSUE TITLE
Inconsistent handling of c() for multiple images

### ISSUE THREAD

**Issue by dmenne** [ropensci/magick#330]
I tried to layer an image using a list of images, when I encountered an inconsistency and had to rely on a for-loop workaround (`input 5`, last in source below) which looks very ugly to me. Did I miss something obvious?

```
# See also https://stackoverflow.com/q/66080522/229794

library(magick)

# Works
input = rep(logo, 2)
image_montage(input, tile = '2x1')

input1 = c(logo, logo)
image_montage(input1, tile = '2x1')

# Fail
input2 = list(logo, logo)
image_montage(input2, tile = '2x1')
# Error: The 'image' argument is not a magick image object.

input3 = lapply(input2, c)
image_montage(input3, tile = '2x1')

input4 = NULL
for (i in 1:3)
  input =  c(input4, logo)
image_montage(input4, tile = '3x1')

input6 = vapply(input2, c, FUN.VALUE = logo)
image_montage(input3, tile = '2x1')
# FUN.VALUE' must be a vector

# Works, but not really good practice
input5 = logo
for (i in 2:3)
  input =  c(input4, logo)
image_montage(input5, tile = '3x1')

**Comment by jeroen** [comment]
I think you are confusing lists with images.

You can use the `image_join()` function to convert a list of images into a single image. Or if you want to use base R things you can use something like `do.call(c, input)` to convert the list of images into an image object.

**Comment by dmenne** [comment]
Sorry, I had missed `image_join`. Still a bit confused by explicit c(logo, logo) works. Probably I was better using do.call in the early 3 millenium.

**Comment by jeroen** [comment]
Why is that confusing? It works the same as for any other R type:

```r
# numeric vectors
x <- 123
y <- 456

# still a numeric vector
c(x,y)

# a list
list(x,y)
```

**Comment by dmenne** [comment]
Bad day.
