### ISSUE TITLE
Cannot find a way to draw a shape on empty canvas

### ISSUE THREAD

**Issue by Kalaschnik** [ropensci/magick#336]
I came thus far to create an empty canvas, yet I fail to create simple shapes on that:

```r
library(magick)
img <- image_blank(width = 600, height = 400, color = "none")
print(img)
```

How would I proceed, if I want to place a filled circle at specific coordinates (e.g., 480, 123) on that canvas?

**Comment by jeroen** [comment]
Have a look at the [drawing and graphics](https://cran.r-project.org/web/packages/magick/vignettes/intro.html#Drawing_and_Graphics) section in the vignette.

**Comment by Kalaschnik** [comment]
Yes I read the entire page; yet, I cannot figure it out. Would you mind helping me here?

**Comment by jeroen** [comment]
Here is one way

```r
library(magick)
img <- image_blank(width = 600, height = 400, color = "yellow")
plot.new()
drawing <- image_draw(img)
symbols(480, 123, circles = 100, bg = 'green', fg = 'blue', lwd=10, inches = FALSE, add = TRUE)
symbols(480, 123, circles = 50, bg = 'red', fg = 'blue', lwd=10, inches = FALSE, add = TRUE)
dev.off()
print(drawing)

```

**Comment by Kalaschnik** [comment]
Thanks, I was stuck with `image_draw()` and falsely expecting to open a new graphics device. Makes a lot of sense! Yet, your code also works without the line `plow.new()`. Is that actually necessary?

**Comment by jeroen** [comment]
Ah sorry you are right that line shouldn't be there! I've edited the above code for future reference.
