### ISSUE TITLE
Set seed to reproduce image_blank fractal?

### ISSUE THREAD

**Issue by dcaud** [ropensci/magick#338]
Is it possible to reproduce the exact image created with the following?

`image_blank(200,200, pseudo_image = "plasma:fractal")`

The following declaration of a seed in R doesn't seem to be passed to magick.
```
set.seed(100)
image_blank(200,200, pseudo_image = "plasma:fractal")
```

I'm not sure if this is possible with imagemagick, but this suggests that a seed can be set for some functions:

https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=12768

**Comment by jeroen** [comment]
I have added a new function `magick_set_seed()` now.

**Comment by dcaud** [comment]
Excellent! Thank you!

In case others are interested, this is how I see `magick_set_seed()` working.

This sequence will produce the same two images:

```
magick_set_seed(99)
image_blank(200, 200,
            pseudo_image = "plasma:fractal") 
image_blank(200, 200,
            pseudo_image = "plasma:fractal") 
```

This will produce 2 different images:

```
magick_set_seed(99)
image_blank(200, 200,
            pseudo_image = "plasma:fractal") 
magick_set_seed(100)
image_blank(200, 200,
            pseudo_image = "plasma:fractal") 
```

In short, `magick_set_seed()` will make subsequent repeated magic functions produce identical output. This is somewhat different than how other packages use R's set.seed(), which is that the *sequence* of randomized things after set.seed() is called will reproduce the same things.

Once this is included on CRAN, it will be super great. For now, this is needed to get this recently developed function to work:

```
library(devtools)
install_github("ropensci/magick")
```
