### ISSUE TITLE
add image_ocr

### ISSUE THREAD

**Issue by jeroen** [ropensci/magick#34]
Wrapper for extracting text from images.

**Comment by dcolley** [comment]
I'm working on this sort of thing...

```
library(tesseract)
text <- ocr("http://jeroenooms.github.io/images/testocr.png")
cat(text)
```
Seems I've come around full-circle...! [jeroenooms.github.io]
The ocr method requires a file, url or "raw vector", and I still have to find a way to map/cast the image from magick to tesseract.

I also tried:
mixing [imager](https://github.com/dahtah/imager) and magick - but my lack of R skills started to show...
```
library(imager)
library(magick)
# load file with imager...
img = load.image(filename) %>% grayscale #%>% threshold (.,"25%")

# try the new image_deskew() method recently implemented
dimg <- image_deskew(img, 40)
Error in magick_image_deskew(image, treshold) :  ## **TYPO in the error message...**
  not compatible with requested type

> head(img)
[1] 0.003037293 0.003206459 0.003144944 0.003144944 0.003175702 0.003144944
> head(dimg)
  format width height colorspace filesize
1   JPEG  3266   2450       sRGB        0
> str(img)
 cimg [1:3264, 1:2448, 1, 1] 0.00304 0.00321 0.00314 0.00314 0.00318 ...
> str(dimg)
Class 'magick-image' <externalptr> 
```
Do we need some helper methods to bring magick-image format/images into R?
imager seems to be using an implementation of Cimg

**Comment by jeroen** [comment]
I added an `image_ocr()` function.
