### ISSUE TITLE
Remove text output from display

### ISSUE THREAD

**Issue by errcricket** [ropensci/magick#359]
I am using the `image_read_pdf` function to display images in a shiny app.

    ```{r include = FALSE}
    ...
    qc1 <- image_read_pdf(paste0(figures_dir,'qc_1.pdf'))
    ```

    #### Initial QC:
    ```{r echo = FALSE, warning=FALSE, message = FALSE, out.height='50%', out.width='80%'}
    print(qc1)
    ```

The image displays sans issue but I am getting additional text before the image. I would like to remove that text for a cleaner output/report.

[![enter image description here][2]][2]

I have tried `echo = FALSE, warning=FALSE, message = FALSE` without success; how can this output be removed?

    ## # A tibble: 2 × 7
    ##   format width height colorspace matte filesize density
    ##   <chr>  <int>  <int> <chr>      <lgl>    <int> <chr>  
    ## 1 PNG     3300   2550 sRGB       TRUE         0 300x300
    ## 2 PNG     3300   2550 sRGB       TRUE         0 300x300

  [1]: https://cran.r-project.org/web/packages/magick/vignettes/intro.html
  [2]: https://i.stack.imgur.com/JzaCJ.png

**Comment by jeroen** [comment]
Try `print(qc1, info = FALSE)`

**Comment by errcricket** [comment]
Solved!
