### ISSUE TITLE
Novice Question: Basic Image Annotation Stopped Working

### ISSUE THREAD

**Issue by jackmcnabola** [ropensci/magick#361]
Hello, I'm a novice with Magick, but I am having an issue getting a basic image annotation to work. It was working before, but for some reason when I try to annotate a PNG I get the following error:

Sample Code: `image_annotate(frink, "I like R!", size = 70, gravity = "southwest", color = "green")`
_Error in magick_image_annotate(image, text, gravity, location, degrees,  : 
  rsession-arm64: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/RenderMVGContent/4405_

Most other features in the Magick package works, but for whatever reason it will not let me annotate anything. I am running MacOS and did a basic install.

`install.packages("magick")`
`library('magick')`
Linking to ImageMagick 6.9.12.3
Enabled features: cairo, fontconfig, freetype, heic, lcms, pango, raw, rsvg, webp
Disabled features: fftw, ghostscript, x11

If anybody could give me any guidance it would be much appreciated. I'm working on a semester project for an undergraduate class and this would be a huge help.

**Comment by jeroen** [comment]
Which operating system do you use

**Comment by jackmcnabola** [comment]
> Which operating system do you use? On MacOS try installing xquartz, see also #350

Thanks for the response! I am using macOS Monterey, I will give the xquartz solution a try and let you know how it goes.
