### ISSUE TITLE
Read nativeVector format images

### ISSUE THREAD

**Issue by noamross** [ropensci/magick#37]
I'm trying to plot an image directly to **magick** memory rather than round-tripping to disk, and can do so like so:

```
library(Cairo)
library(ggplot2)
library(magick)
x = 1680
y= 1050

Cairo(type="raster", width=x, height=y)
ggplot(mtcars, aes(x=cyl, y=mpg)) + geom_point()
i <- image_read(structure(packBits(intToBits(dev.capture(native=TRUE))), dim=c(4, x, y)))
dev.off()
image_write(i, "testmem.gif")
```

However, this is still slower than disk round-trip, with most of the time being taken up by translating the nativeRaster (8-bit ARGB, stored as integers) produced by `dev.capture()` to the right raw format:

<img width="920" alt="screen shot 2016-12-06 at 8 52 56 pm" src="https://cloud.githubusercontent.com/assets/571752/20951801/0caac106-bbf6-11e6-8542-9f3d673d9804.png">

It would be great if `image_read()` could also take nativeRasters for this use case and do the right conversion in a performant way.  I think there are lots of applications where you'd like to manipulate plots without going to disk for good performance. (I'm currently trying to do this to update the **gganimate** package).

**Comment by jeroen** [comment]
As of version 0.6 magick includes a native graphics device: https://cran.r-project.org/web/packages/magick/vignettes/intro.html#drawing_and_graphics

**Comment by jeroen** [comment]
Thank you! As of 1.0 we can read/write all raster formats and also have a native device.
