### ISSUE TITLE
[At least some] macOS versions need -D_GLIBCXX_USE_CXX11_ABI=0

### ISSUE THREAD

**Issue by barracuda156** [ropensci/magick#372]
Otherwise loading fails with:
```
Symbol not found: __ZN6Magick5Image10fontFamilyERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by jeroen** [comment]
How are you installing imagemagick? This flag would only be needed if you
are using an imagemagick that was built using gcc 4.x. If you install the
binary package from cran or install imagemagick from homebrew it is not
needed.


Op vr 14 apr. 2023 17:20 schreef Sergey Fedorov ***@***.***>:

**Comment by barracuda156** [comment]
> How are you installing imagemagick? This flag would only be needed if you are using an imagemagick that was built using gcc 4.x. If you install the binary package from cran or install imagemagick from homebrew it is not needed. Op vr 14 apr. 

@jeroen Macports does not require C/C++ 2011 for ImageMagick, so it gets built with whatever system compiler is the default one, including pre-2011.

```
svacchanda$ port deps ImageMagick
Full Name: ImageMagick @6.9.11-60_5+x11
Extract Dependencies: xz
Library Dependencies: bzip2, djvulibre, xz, jbigkit, libjpeg-turbo, lcms2,
                      libpng, libraw, tiff, webp, zlib, fftw-3, freetype,
                      fontconfig, ghostscript, libiconv, libtool, openjpeg,
                      openexr, expat, libxml2, libheif, pkgconfig, xorg-libX11,
                      xorg-libXext, xorg-libXt
Runtime Dependencies: urw-fonts
```

https://github.com/macports/macports-ports/blob/master/graphics/ImageMagick/Portfile

**Comment by jeroen** [comment]
If you use the same compiler to build the R package as was used to build
imagemagick, it will work.



Op vr 14 apr. 2023 18:14 schreef Sergey Fedorov ***@***.***>:

**Comment by barracuda156** [comment]
> If you use the same compiler to build the R package as was used to build imagemagick, it will work.

Thank you, this is good to know.

My point was that while `R` does require at least 2011 (if not itself, then large number of packages, and that imposes a requirement on `R` anyway), `ImageMagick` does not, so there will be users who build it with pre-2011 compilers (in Macports or elsewhere).

But it is up to you and other developers, of course, whether to consider such case or not.
(Locally in Macports we can easily fix it by adding `-D_GLIBCXX_USE_CXX11_ABI=0` via a patch.)

P. S. I guess we can close the issue? If this gets fixed in upstream (i.e. here), we just drop our patch, or if/when `ImageMagick` will require 2011 standard.
