### ISSUE TITLE
Strange wrong pixel in cmyk tiff

### ISSUE THREAD

**Issue by chroetz** [ropensci/magick#376]
Using R 4.2.3 with the magick package version 2.7.4.
```
library(magick)
img <- image_graph(width = 4, height = 4) # or any other image size
# make empty plot
par( 
  bg = "red", # or any other color
  mar = c(0,0,0,0),
  xaxs = "i", xaxt="n",
  yaxs = "i", yaxt="n")
plot.new()
dev.off()
imgOut <- image_convert(img, colorspace = "cmyk")
print(imgOut) # shows purely red image
image_write(imgOut, path = "out1.tiff") # creates purely red image
image_write(imgOut, path = "out2.tiff", format = "tiff") # makes one pixel cyan
```
The file out.tiff is a purely red square. The file out2.tiff looks like this:
![out2](https://github.com/ropensci/magick/assets/69958015/e49bd2c1-3ed7-42a0-960c-214f0781d4ad)
tiff images: [out.zip](https://github.com/ropensci/magick/files/12266673/out.zip)

There seems to be something wrong with how cmyk tiff images are handled, as the wrong pixel does not appear when `colorspace = "cmyk"` is removed. Replacing the first lines until `dev.off()` by `img <- image_blank(4, 4, "red")` also does not result in a wrong pixel.

**Comment by jeroen** [comment]
This looks like a bug in the underlying imagemagick or libtiff. What OS are you on?

**Comment by chroetz** [comment]
I use Windows 10

**Comment by jeroen** [comment]
I updated the version of imagemagick and libtiff. Can test with magick 2.7.5 from https://ropensci.r-universe.dev/magick

**Comment by chroetz** [comment]
The wrong pixel is gone with the new version. Thanks!
