### ISSUE TITLE
CRAN incoming checks fail due to magick's usage of more than 2 cores

### ISSUE THREAD

**Issue by mrcaseb** [ropensci/magick#382]
It seems like this package makes sure it uses 2 cores in R CMD Checks. 
https://github.com/ropensci/magick/blob/36340eeb826efd2454ad3ea2caf5c0d75381b010/R/init.R#L18-L21
However, the function isn't exported, so package developers with a magick dependency have no way to access the function. 
It also doesn't seem to respect the value of `OMP_THREAD_LIMIT`. As a result, my R package with a magick dependency doesn't pass cran incoming checks. 
Any advice how I can make sure magick limits itself to 2 cores?

**Comment by jeroen** [comment]
Last time I checked, this was not working anymore, or at least not in the way CRAN is measuring. I ended up disabling tests and examples to please cran: https://github.com/ropensci/magick/commit/fd53da8f040ed91d87a91c4f363120729f2e2441

**Comment by mrcaseb** [comment]
Thanks for the quick reply. Disabling tests is the worst in my opinion. I hate being forced by CRAN to do so.

**Comment by jeroen** [comment]
You can still run the tests and examples in your own CI, as I did in my commit: https://github.com/ropensci/magick/commit/fd53da8f040ed91d87a91c4f363120729f2e2441

**Comment by mrcaseb** [comment]
Yeah I do run tests and examples on CI but this won't allow revdepcheck to detect if one of my dependencies breaks my package. 

It happened to me in another package where I depend on dplyr. The tidyverse would have detected the failing test and submitted a PR IF I had any tests running on CRAN.

**Comment by jeroen** [comment]
I think if you condition your tests on the NOT_CRAN envvar, they wil also get run in revdep-checks.
