### ISSUE TITLE
Where to find policy.xml used by magick on osx?

### ISSUE THREAD

**Issue by dcaud** [ropensci/magick#385]
With `sudo find / -name policy.xml 2>/dev/null` I see paths to various policy.xml inside of ImageMagick-7 folders. However, I believe that your library uses imagemagick-6. 

I am ultimately trying to set some of the values to mimic on my Mac how magick works on shinyapps.io. As is, they still haven't removed the policy.xml file (after upgrading to Jammy) and so my apps crash. I figure I can write some code that uses less resources... if I can replicate a similar environment.

Is there a way to print which imagemagick is used from R, perhaps with `magick::magick_options()`?

**Comment by jeroen** [comment]
Hmm I don't think there is a policy on Mac and Windows. It will probably be easier for you to reproduce the problems using docker, so that you can run inside a linux container with jammy.

**Comment by dcaud** [comment]
Thanks, good idea.
