### ISSUE TITLE
Dplyr/tidyverse verbs do not work with magick-image tibbles.

### ISSUE THREAD

**Issue by rgzn** [ropensci/magick#387]
If you have collection of magick-image objects, eg as returned by `magick::image_split()`, they appear as a tibble. This leads one to expect to be able to use them as such. For example, to apply transformations to the each image in the collection using the verbs from `purrr`.

However, this does not work. I would like to request that be added.

**Comment by jeroen** [comment]
Can you include a basic example?

**Comment by rgzn** [comment]
``` r
library(tidyverse)
library(magick)
img <- image_quantize(logo, 4)
layers <- image_split(img)

image_add <- function(x,y, operator = "plus") {
  magick::image_composite(image = x, composite_image = y, operator = operator)
}

#desired output:
layers[1] %>% 
  image_add(layers[2]) %>% 
  image_add(layers[3]) %>% 
  image_add(layers[4])
```

<img src="https://i.imgur.com/BtgbAtF.png" width="640" />

``` r

# This does not work:
layers %>%
  purrr::reduce(image_add)
#> Error: The 'image' argument is not a magick image object.

# This works:
layers %>%
  as.list() %>% 
  purrr::reduce(image_add)
```

<img src="https://i.imgur.com/F9GGUKt.png" width="640" />

<sup>Created on 2023-10-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rgzn** [comment]
Maybe I just didn't undwerstand the data model of a `<magick-image>` object.  I guess if they are converted to lists first this should work.

**Comment by jeroen** [comment]
The `<magick-image>` type is intended to be vectorized where possible. So you can do things like `length()` or `as.list()` indeed. The tibble is just for printing the image properties, it does not represent the image data.
