### ISSUE TITLE
image_annotate(): Get available fonts

### ISSUE THREAD

**Issue by matutosi** [ropensci/magick#391]
I use magick package on Windows.
To use Japanese fonts with image_annotate(), fonts must be specified.
we can get the available fonts with the following command with ImageMagick.
  convert -list font
Please let me know a way to do the same thing with magick package.
If not, a function to do so would be greatly appreciated.

**Comment by jeroen** [comment]
Would you need this information for debugging, or to program with? I added a function `dump_option_info` that internally calls the the same as `convert -list` so you can do:

```r
# same as convert -list font
magick::dump_option_info("font")
```

This will make imagemagick print stuff to the console, so it may work in Rterm.exe and RStudio, but not in RGui.

**Comment by matutosi** [comment]
THANKS. It works well.
I will use the function to specify the font as an argument to the image_annotate() function.

**Comment by matutosi** [comment]
Sorry for the additional request. 
It would be appreciated if a string of font information displayed in the console could be obtained as a return value.

**Comment by jeroen** [comment]
I can try. Do you need the font name or the path?

**Comment by jeroen** [comment]
OK I have added a new function `magick_fonts()`. You can install the latest magick from https://ropensci.r-universe.dev/magick

Can you let me know if this works? I personally don't know how fonts on Windows work exactly.

**Comment by matutosi** [comment]
Thanks. The function also works on RGui.
