### ISSUE TITLE
The problem of not installing in anaconda

### ISSUE THREAD

**Issue by yangjing1016** [ropensci/magick#397]
Hi rOpenSci,

The following error occurred when I installed using the install.packages("magick ") code.

> * installing *source* package ‘magick’ ...
** package ‘magick’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/lib/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/lib/include/ImageMagick-6 -I/usr/lib/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/lib/include/ImageMagick-6 -I/usr/lib/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/lib/include/ImageMagick-6
Using PKG_LIBS=-L/usr/lib/lib/x86_64-linux-gnu -lMagick++-6.Q16 -lMagickWand-6.Q16 -lMagickCore-6.Q16
--------------------------- [ANTICONF] --------------------------------
Configuration failed to find the Magick++ library. Try installing:
 - deb: libmagick++-dev (Debian, Ubuntu)
 - rpm: ImageMagick-c++-devel (Fedora, CentOS, RHEL)
 - csw: imagemagick_dev (Solaris)
 - brew imagemagick@6 (MacOS)
If Magick++ is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a Magick++.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: Magick++.h: No such file or directory
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘magick’
* removing ‘/opt/miniconda3/envs/display/lib/R/library/magick’

The downloaded source packages are in
        ‘/tmp/Rtmpfk2PJb/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("magick") :
  installation of package ‘magick’ had non-zero exit status

I installed libmagick++-dev according to the prompt. The Magick++.h file is in the path of/usr/include/imagemagick-6/magick++.h.
But the same error message still appears.

Best wishes,
yangjing

**Comment by jeroen** [comment]
You seem to be using anaconda. You need to install from here: https://anaconda.org/conda-forge/r-magick

**Comment by yangjing1016** [comment]
According to your answer, the installation with conda was successful.Really appreciate your help!
