### ISSUE TITLE
Feature request: local adaptive thresholding

### ISSUE THREAD

**Issue by jsta** [ropensci/magick#40]
The use case I have in mind is to clean-up images before feeding them to [tesseract](https://github.com/ropensci/tesseract). I personally have seen great improvements running [lat](https://www.imagemagick.org/Usage/transform/#lat) on images before feeding to `tesseract`but `magick` has no bindings for this? I can't seem to achieve the same effect with a combination of `image_contrast`, `image_blur`, and `image_enhance`.

**Comment by dmypstl** [comment]
I found combination of `image_quantize` and `image_median` work relatively well for some images. Agree that **local adaptive thresholding** would be the crucial feature for OCR pipeline.

**Comment by jeroen** [comment]
I've tried to add bindings for this, but i don't understand myself what LAT is supposed to do. Can you try the development version?

**Comment by dmi3kno** [comment]
Hi, thanks for lightning response. Something very basic is missing in Rcpp bindings, it seems:
```r
# inspired by https://www.imagemagick.org/discourse-server/viewtopic.php?t=25087
image_read("http://www.scanbizcards.com/benefitquest.jpg") %>% 
  image_treshold(25, 25, offset=10)
#> 
#> Error in .Call("_magick_magick_image_treshold", PACKAGE = "magick", input,  : 
#>   "_magick_magick_image_treshold" not available for .Call() for package "magick"
```

**Comment by jeroen** [comment]
@dmi3kno looks like your installation is corrupted, probably because you tried to install magick while the package was already loaded (perhaps in another R process).

Try reinstalling from source in a clean R session.

**Comment by dmi3kno** [comment]
Oh, my bad. Did not notice another session running in the background.
Looks awesome! I am really impressed by the results so far:
```r
image_read("http://www.scanbizcards.com/benefitquest.jpg") %>% 
  image_convert(type="Grayscale") %>% 
  image_negate() %>% 
  image_treshold(30, 30, offset=6000) %>% 
  image_negate() %>% 
  tesseract::ocr() %>% readr::read_lines()
#>
#>   [1] "Eric Cohen"                       ", Managing Director"             
#>   [3] "Insurance & Employee Beneﬁts"     "BEN EFlT/IQU EST"                
#>   [5] "420 Lexington Avenue, Suite 2400" "New York, NY 10170"              
#>   [7] "Tel: (212) 389-7838 x7839"        "Fax: (212) 389-7828"             
#>   [9] "eric.cohen@beneﬁtquest.com"
```
I have also tried on my local examples and it cleans up noise around the text better than anything I tried so far.

The only thing I wonder how to relate to the units of `offset`. ImageMagick uses percentage, but here we are having an absolute offset. Not a big deal, just need to be explicit about it in the documentation.

**Comment by dmi3kno** [comment]
Good question! [This ](http://imagemagick.org/discourse-server/viewtopic.php?t=20610)seems to imply that it is a percentage of either 256 or 65535 depending on the image depth (8 or 16 bit, respectively).

**Comment by jeroen** [comment]
Update: i have renamed the function to `image_lat()` for consistency with the command line.

**Comment by jeroen** [comment]
@dmi3kno can you test if the new `image_lat()` function does what you need?

**Comment by dmi3kno** [comment]
Yes, beyond expectations. I think your default of "5x5+2%" results in a little too aggressive thinning of letters - wider window helps differentiate the background background better and does not result in excessive thinning and simplification of letters. Again, I am working with this type of images, so my opinion might be influenced by that.
```r
#>   format width height colorspace matte filesize density
#> 1   JPEG  1000  10065       sRGB FALSE  3153164 300x300
```
Do you really need to provide a default value there?

**Comment by dmi3kno** [comment]
`image_lat` is nice and good. Would you like a PR into vignette? Where would you like this to be added (own vignette on thresholding or addition to existing vignette)?

**Comment by jeroen** [comment]
The problem is that the vignette is already too large for CRAN. We're considering starting a bookdown. Would you be interested in contributing?

**Comment by dmi3kno** [comment]
Yes, I'd love to contribute. Keep me in the loop
