### ISSUE TITLE
building a thumbnail gallery

### ISSUE THREAD

**Issue by rjake** [ropensci/magick#41]
I am enjoying this package. However, I cannot figure out how to use image_append to create a thumbnail gallery of images. I have a table with the names of each png that needs to be added for a given week. I am trying to write something that will create 4 images across and have a variable number of rows, some weeks it will be 23 (6 rows) images, other weeks 75+ (19 rows). I've been trying to create a for loop that appends left_to_right and then top_to_bottom as shown in the vignette. Using assign(x, image_read) goes through but then says it isn't a magick image when I try to call it with get(). Any help would be appreciated.

**Comment by vbonhomme** [comment]
possibly a twist around `image_montage` which doesn't seem to be configurable from R than it is in magick itself?

**Comment by dmi3kno** [comment]
You could do some sort of layered cake between `image_montage()` and `image_append()`.
```r
imgs <- list.files("~/Downloads/dl/", full.names = TRUE) %>% 
  sample(17, replace = TRUE)


split(imgs, (seq_along(imgs)-1)%/%4) %>%
  lapply(function(x){
    lapply(x, image_read) %>% 
    {Reduce(c, .)} %>% 
    image_montage() %>% 
    image_trim()
    }) %>% 
  {Reduce(c, .)} %>% 
  image_append(stack = TRUE)
```

![preview](https://user-images.githubusercontent.com/13419011/61595538-d5e05a00-abf8-11e9-82e5-ba73d91f58fd.png)

**Comment by jeroen** [comment]
Romain's [collage](https://github.com/ThinkR-open/collage) package which builds on magick is also a good example of how to do this.

**Comment by jeroen** [comment]
Also check out the [hexwall](https://blog.mitchelloharawild.com/blog/user-2018-feature-wall/) example from user2018:

[![hexmap](https://blog.mitchelloharawild.com/blog/2018-07-11-user-2018-feature-wall_files/final.jpg)](https://blog.mitchelloharawild.com/blog/user-2018-feature-wall/)
