### ISSUE TITLE
Feature request: -gravity and -extent

### ISSUE THREAD

**Issue by smach** [ropensci/magick#44]
I'm trying to batch process images to pad their canvas sizes so they fit a 3 x 2 ratio. This works in the command line with ImageMagick

    convert mypic.jpg -background white -gravity center  -extent 1611x1074  mypic_3x2.jpg

As far as I can tell, magick implements the -background functionality with image_background(), but not gravity or extent. If at some point those could be added, that would be great. (Meanwhile, off to figure out how to run that command as a shell script from R....)

Thanks for the great package.

**Comment by yutannihilation** [comment]
I really want `gravity`; if we want to crop the center without `gravity`, we need to calculate the offset by ourselves, which feels boring:

``` r
library(magick)

rose <- image_convert(image_read("rose:"), "png")
info <- image_info(rose)
orig_width <- info$width
orig_height <- info$height

crop_width <- 30
crop_height <- 30

offset_x <- as.integer((orig_width - crop_width) / 2)
offset_y <- as.integer((orig_height - crop_height) / 2)

g <- sprintf("%dx%d%+d%+d", crop_width, crop_height, offset_x, offset_y)
image_crop(rose, g)
```

I just want to do this:

```r
image_crop(rose, "30x30", gravity = "center")
```

But, after a quick look at [Magick++'s API](https://www.imagemagick.org/Magick++/Image++.html), I found `crop()` doesn't take `Gravity`... Maybe I need to use [`ParseGravityGeometry`](https://www.imagemagick.org/include/api/geometry.php#ParseGravityGeometry) or [`GravityAdjustGeometry`](https://www.imagemagick.org/include/api/geometry.php#GravityAdjustGeometry)?

(l feel `image_composite()` can easily get `gravity` argument, btw)

**Comment by jeroen** [comment]
@dlemstra is there a way to set the `gravity` for the `Magick::cropImage()` STL? Should I set a certain image attribute before cropping?

**Comment by dlemstra** [comment]
There is now not a method to do that. But you could use `GravityAdjustGeometry` to change the geometry based on the gravity. It might also be an option to add an extra overload to `crop` and `extent` inside `Magick++` that uses `ParseGravityGeometry`. But this will be a new feature so we will only add this to IM7 then.

**Comment by jeroen** [comment]
When/where do I set `GravityAdjustGeometry` to affect the crop operation? I am currently using this:

https://github.com/ropensci/magick/blob/c116b2b8505f491db72a139b61cd543b7a2ce873/src/resize.cpp#L80-L90

**Comment by jennybc** [comment]
This would be really handy because then we could turn hex logos into Open Graph images suitable for the social media cards of GitHub repos.

https://github.blog/2019-04-17-custom-open-graph-images-for-repositories/

Here's a `convert` snippet, but I don't think we can currently do same with magick?

``` bash
convert usethis-full-logo.png -thumbnail '600x600>' -background white -gravity center -extent 1280x640 usethis-og-1280x640.png
```

**Comment by dmi3kno** [comment]
You can definitely do it in `magick`, even without `gravity` and  `extent`

```r
img <- image_read("https://raw.githubusercontent.com/r-lib/usethis/master/man/figures/usethis-full-logo.png")

card_width <-1280
card_height <- 640

offset_x <- card_width/2-image_info(img_scaled)$width/2
offset_y <- card_height/2-image_info(img_scaled)$height/2

image_blank(card_width, card_height, "#ede8e2ff") %>% 
  image_composite(img_scaled, offset = geometry_point(offset_x, offset_y))
```

The trick is to calculate how much to offset the logo on the card, but this is just some basic math, so it should be quick.

**Comment by jeroen** [comment]
I still want to expose a gravity parameter in `image_crop()` but haven't yet figured out how to do this.

**Comment by yutannihilation** [comment]
Thanks for this great feature! :tada:

**Comment by dmi3kno** [comment]
I don't think `gravity` can be mixed with `offset`in `image_composite(img1, img2)`. Look at how `gravity` is interpreted in [ImageMagic's `compose`](http://www.imagemagick.org/Usage/annotating/#gravity_image)

**Comment by jeroen** [comment]
In the C++ API you can either set a gravity or an offset, but not both. So I have overloaded them like so:

```
> image_composite(logo, rose, offset = '+100+100')
  format width height colorspace matte filesize density
1    GIF   640    480       sRGB FALSE        0   72x72
> image_composite(logo, rose, offset = 'east')
  format width height colorspace matte filesize density
1    GIF   640    480       sRGB FALSE        0   72x72
```

**Comment by jeroen** [comment]
@dmi3kno I finally figured out how we can set _both_ a gravity and offset in `image_composite()`. Now fixed in master.

**Comment by dmi3kno** [comment]
Can we do something about `location` argument in `image_annotate`? If you don't want to change it right away you could soft-deprecate it until next version and introduce `offset` as parallel argument. Remembering the names of the arguments is annoying. This one is usually a named argument anyways, so we are not risking much.

**Comment by jeroen** [comment]
You mean to rename the argument? Or to change how it works? Can you open a separate issue for this?

**Comment by dmi3kno** [comment]
Yes, I meant renaming the argument for the purpose of maintaining consistency. I am not sure this is good enough reason, so I am hesitant to open an issue for this. What is your attitude towards renaming attributes (gracefully, with soft-deprecation)?

**Comment by jeroen** [comment]
> What is your attitude towards renaming attributes (gracefully, with soft-deprecation)?

If there is a good reason to do it, I'm generally in favor, but in this case I'm not convinced...  This change will break quite a few scripts because most people will use the `location` argument when using `image_annotate()`. Do you think `location` is ambiguous or confusing? How would `offset` be a better name?

**Comment by dmi3kno** [comment]
It is not better, but the fact that two similar things (`location` in `image_annotate()` and `offset` in `image_composite()` ) are called differently is confusing. Maybe it should be `location` in `composite` as well, but I thing `offset` makes more sense, because it literally offsets location of the item against "point of gravity". Dunno. Maybe we leave it as is.
