### ISSUE TITLE
remove print(image_info(x)) from magick:::`print.magick-image`

### ISSUE THREAD

**Issue by yonicd** [ropensci/magick#46]
is there a way to suppress the print call at the end of the function?

if not can it be removed or add for a flag to control its print?

it is causing issues when we want to use the print function and are getting output in the console

```
magick:::`print.magick-image`
function (x, ...) 
{
   viewer <- getOption("viewer")
   ext <- ifelse(length(x), tolower(image_info(x[1])$format), 
       "gif")
   if (is.function(viewer)) {
       tmp <- file.path(tempdir(), paste0("preview.", ext))
       image_write(x, path = tmp)
       viewer(tmp)
   }
   print(image_info(x))
   invisible()
}
```

**Comment by jeroenooms** [comment]
Causing what kind of issues? Most `print()` methods output stuff to the console?

**Comment by yonicd** [comment]
We are using print as an intermediary step in a bigger function the prints other information to the console, which is read into a file. Right now it's first line is the print from print.magick, and is causing problems

**Comment by jeroen** [comment]
Just `caputure.output()` or so if you want to suppress `print()` output.
