### ISSUE TITLE
as.double.bitmap & as.integer.bitmap

### ISSUE THREAD

**Issue by jwijffels** [ropensci/magick#47]
Question. Why do you divide in `as.double.bitmap` by 255 and `as.integer.bitmap` the division is not done?

**Comment by jeroenooms** [comment]
I think it was a legacy thing in how the R graphics device expects bitmaps.

**Comment by jwijffels** [comment]
But is it the intention to map a Red RGB value of 255 to 1?

**Comment by jeroen** [comment]
Yes, this is the same scale as e.g. `png::readPNG()`.
