### ISSUE TITLE
v0.4 fails to install on macOS

### ISSUE THREAD

**Issue by pat-s** [ropensci/magick#49]
```r
** package ‘magick’ successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/7.0.5-4/include/ImageMagick-7
Using PKG_LIBS=-L/usr/local/Cellar/imagemagick/7.0.5-4/lib -lMagick++-7.Q16HDRI -lMagickWand-7.Q16HDRI -lMagickCore-7.Q16HDRI
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because Magick++ was not found. Try installing:
 * deb: libmagick++-dev (Debian, Ubuntu)
 * rpm: ImageMagick-c++-devel (Fedora, CentOS, RHEL)
 * csw: imagemagick_dev (Solaris)
 * brew: imagemagick (OSX)
If Magick++ is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a Magick++.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
```

`brew info`

```ruby
/usr/local/Cellar/imagemagick/7.0.5-4 (1,524 files, 23MB) *
  Built from source on 2017-03-26 at 18:14:18 with: --with-openmp --with-fontconfig --with-librsvg --with-ghostscript --with-webp --with-pango
```

I assume one of the options I built `imagemagick` with is causing problems? I will rebuild with your README suggestion and report back.

**Comment by pat-s** [comment]
Using `brew install imagemagick --with-fontconfig --with-librsvg --with-fftw` works. Any idea which switch of my initial install could be the problematic one?

**Comment by jeroen** [comment]
The `-fopenmp` doesn't look familiar. Perhaps it conflicts with R? The default `imagemagick` has:

```
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/7.0.5-4/include/ImageMagick-7
Using PKG_LIBS=-L/usr/local/Cellar/imagemagick/7.0.5-4/lib -lMagick++-7.Q16HDRI -lMagickWand-7.Q16HDRI -lMagickCore-7.Q16HDRI
```

**Comment by pat-s** [comment]
I was following the installation advice of @bhaskarvk here: https://dev.to/bhaskar_vk/setup-osx-for-r. Maybe he clean explain possible interferences?

**Comment by jeroen** [comment]
Yeah you shouldn't do that, unless you know what you are doing. Most OSX users should use the standard [R for mac](https://cran.r-project.org/bin/macosx/) binaries, and compilers from Xcode.

I would highly recommend to avoid mixing other compilers (e.g. gcc from homebrew) unless you really need openmp or so.

**Comment by jeroen** [comment]
Closing this issue because it is about managing multiple compilers on your system.

**Comment by bhaskarvk** [comment]
@pat-s If you are following my guide, you will need to use homebrew's gcc, instead of clang. I do see some performance improvements when using ImageMagick compiled with `openmp`, but system clang doesn't support openmp.
FWIW any R package that you want to use openmp you will need to use GCC, but @jeroen  is right unless you know the ins and outs of co-mingling compliers, you should stick with the defaults.

I should probably remove the `--with-openmp` from my post.

**Comment by pat-s** [comment]
Thought I had setup homebrew `gcc` correctly following your guide. Well, I set it up on two systems and maybe something went wrong here.

However, you are both right - I do not know what I'm doing here since I have no knowledge about compilers. Reverting and sticking with `clang` then :)
