### ISSUE TITLE
Feature request: function for converting to bw/grayscale

### ISSUE THREAD

**Issue by salupere** [ropensci/magick#50]
function for converting a loaded image to bw/grayscale,

thanks for great package btw!

**Comment by zx8754** [comment]
Maybe related post at SO:

https://stackoverflow.com/questions/44385982/quantize-grayscale-images

**Comment by ShirinG** [comment]
I would like to second that feature request! Thank you! :-)

**Comment by jeroen** [comment]
I have just added two new parameters to `image_convert`. You can use either of these:

```r
image_convert(image, colorspace = 'gray')
image_convert(image, type = 'grayscale')
```

**Comment by zx8754** [comment]
@jeroen Does this include *levels* of gray, example from above SO post?

**Comment by jeroen** [comment]
OK. I just added another option `image_quantize()` that you can use to reduce colors. I think what you want is something like:

```r
image_quantize(img, max = 16, colorspace = 'gray')
```
