### ISSUE TITLE
Is it possible to generate a color palette from an image?

### ISSUE THREAD

**Issue by jhemsley** [ropensci/magick#52]
Here is an example: http://lokeshdhakar.com/projects/color-thief/

I don't know if this kind of functionality is implemented in imagemagick, but finding and comparing palettes would be quite useful.

**Comment by hadley** [comment]
To do this yourself is pretty simple - convert colours to perceptually uniform space (e.g. Lab), cluster, extract cluster centroids.

**Comment by jeroen** [comment]
You can use `as.raster()` on the image to get the color values of all the pixels. And then use whatever method you want to derive a palette. The latter is outside the scope of imagemagick.
