### ISSUE TITLE
Abandoned temporary files

### ISSUE THREAD

**Issue by jzadra** [ropensci/magick#57]
I just discovered that I had over 100 GB of magick temp files.  I believe they were left when an rmagick function locked up and I had to force quit R.  Some way of making sure these get cleaned would be a bonus.

**Comment by jeroen** [comment]
That sounds very strange, but your report does not include sufficient detail to investigate what might have caused this. 

Can you please state where you found these files? What were they named? What platform are you using? What magick function were you using when this happened?

**Comment by jeroen** [comment]
I'm closing this issue because there is nothing I can do if you don't give me any more details.
