### ISSUE TITLE
Create GIF

### ISSUE THREAD

**Issue by ShKlinkenberg** [ropensci/magick#59]
I was wondering how I would go about creating a GIF from multiple r plots with magick.

What i normally do is:

```r
png(file="temp/example%02d.png")

for (i in subsets) {

    plot(subset(data, some.subset == i))

}

dev.off()
```

and then use the png in temp to create a GIF. I think magick can make this process easier but I do not really see how to go about.

**Comment by jeroen** [comment]
The development version of magick has a native graphics device which should make this easier:

```r
devtools::install_github("ropensci/magick")
```

You can then do:

```r
img <- image_device()
for (i in subsets) {
    plot(subset(data, some.subset == i))
}
dev.off()

# make animation
anim <- image_animate(img)
```

**Comment by ShKlinkenberg** [comment]
Thanks so much!

**Comment by jeroen** [comment]
This is now on cran.
