### ISSUE TITLE
Font metrics are slow (especially first time) for static builds

### ISSUE THREAD

**Issue by jeroen** [ropensci/magick#61]
### Mac OSX

Using the OSX magick CRAN build, the magick graphics device has a few sec overhead on the first time of using fonts after a reboot: 

```r
fig <- image_device(res = 96)
ggplot2::qplot(mpg, wt, data = mtcars, colour = cyl)
dev.off()
print(fig)
```

After the first time it is gone. Even if we restart R. Perhaps fontconfig is rebuilding some tmp cache?

### Windows

On Windows all font operations (both calc metrics and drawing) are consistently quite slow. Need to figure out how to debug what it is doing.

### FontCondfig Debugging

The [fontoconfig manual](https://www.freedesktop.org/software/fontconfig/fontconfig-user.html) pages:

```
Name         Value    Meaning
  ---------------------------------------------------------
  MATCH            1    Brief information about font matching
  MATCHV           2    Extensive font matching information
  EDIT             4    Monitor match/test/edit execution
  FONTSET          8    Track loading of font information at startup
  CACHE           16    Watch cache files being written
  CACHEV          32    Extensive cache file writing information
  PARSE           64    (no longer in use)
  SCAN           128    Watch font files being scanned to build caches
  SCANV          256    Verbose font file scanning information
  MEMORY         512    Monitor fontconfig memory usage
  CONFIG        1024    Monitor which config files are loaded
  LANGSET       2048    Dump char sets used to construct lang values
  MATCH2        4096    Display font-matching transformation in patterns
```

So we can get some debugging info:

```r
Sys.setenv(FC_DEBUG = 1 + 4 + 8 + 16 + 128 + 1024)
library(magick)
fig <- image_device(res = 96)
ggplot2::qplot(mpg, wt, data = mtcars, colour = cyl)
dev.off()
print(fig)
```

Any tips would be amazing :) @lionel- @jimhester @hadley

**Comment by lionel-** [comment]
Hi Jeroen,

Fontconfig builds up a cache of the system fonts the first time it's used. You could work around this with `gdtools::set_dummy_conf()`: https://github.com/davidgohel/gdtools/blob/3b0e23e70639abe3c603a4ee2de2161f9fe4624e/R/fontconfig.R#L83

**Comment by jeroen** [comment]
@lionel- thanks! I have solved the caching problem indeed. Now there is a remaining problem with font metrics being slow on Windows, but that might be a bug in libmagick++.

**Comment by jeroen** [comment]
Both are now solved. The OSX problem was due to an invalid `<cache>` path in the `fonts.conf` file for the static library and has been [fixed in autobrew](https://github.com/jeroen/autobrew/blob/gh-pages/imagemagick#L61-L63).

The windows regression is a [bug in freetype](http://lists.nongnu.org/archive/html/freetype-devel/2017-07/msg00071.html). I have disabled `FT_LOAD_TARGET_LIGHT` in the imagemagick6 build on rwinlib which avoids the problem.
