### ISSUE TITLE
Error in magick_image_write: Magick: memory allocation failed

### ISSUE THREAD

**Issue by lozalojo** [ropensci/magick#62]
I get an error in a 1gb ubuntu machine at AWS:

Warning: Error in magick_image_write: Magick: memory allocation failed `' @ error/gif.c/WriteGIFImage/1648

The server used to work fine with 0.4 version, but today I updated the system and R packages and image_write does not work anymore. I've tried rolling back to 0.4 and I get the same error, so I guess it is a problem with libmagick++-dev which probably has been updated too.

Any hint on how to use magick in low RAM machines?

sessionInfo()
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] memapp_2.4.20170802 magick_0.5

loaded via a namespace (and not attached):
[1] shiny_1.0.3     compiler_3.4.1  R6_2.2.2        htmltools_0.3.6
[5] Rcpp_0.12.12    digest_0.6.12   xtable_1.8-2    httpuv_1.3.5
[9] mime_0.5
>

**Comment by jeroen** [comment]
Did you upgrade your ubuntu system from a previous version? Perhaps libraries were not properly upgraded. Try reinstalling 

```
sudo apt-get remove --purge libmagick*
sudo apt-get autoremove --purge
```

reinstall:

```
sudo apt-get dist-upgrade
sudo apt-get install libmagick++-dev
```

**Comment by lozalojo** [comment]
Done, no success. Purged libmagick, upgraded and installed again. Reinstalled R magick.

The code throws the same error.

Warning: Error in magick_image_write: Magick: memory allocation failed `' @ error/gif.c/WriteGIFImage/1648

**Comment by jeroen** [comment]
Do you have example code I can reproduce?

**Comment by lozalojo** [comment]
I am not sure what happened but it works again, honestly I dont know why. I have the log file of this morning at 7:45 with the error (my last message) and I have tested now and It works again. I dont have an explanation for this I've changed nothing in my server.

Thanks for your attention, anyway.

**Comment by jeroen** [comment]
You're probably running out of memory on your machine so the operation only works if there happens to be sufficient memory available.

Note that 1gb is not a lot of memory for R.

**Comment by lozalojo** [comment]
Probably you are in the right direction, I will try making the graph before performing other tasks.

The server is at memapp dot com (test data to load in the mem package data directory, flucyl.rda), the animated graph is at Surveillance/surveillance/animated.
