### ISSUE TITLE
Does not compile on MacOS

### ISSUE THREAD

**Issue by neuwirthe** [ropensci/magick#65]
In RStudio, I did
```
Sys.setenv(PATH=paste0("/usr/local/Cellar/imagemagick@6/6.9.9-5_1/lib/pkgconfig:",Sys.getenv("PATH")))
devtools::install_github("ropensci/magick")
```

I had installed the required version of imag magick via homebrew,
but I got an error:

```
devtools::install_github("ropensci/magick")
Downloading GitHub repo ropensci/magick@master
from URL https://api.github.com/repos/ropensci/magick/zipball/master
Installing magick
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  ```
'/private/var/folders/zf/y3v1wp1n6yg4yyd68s0770xc0000gn/T/RtmpaXPw1K/devtools2e8617e3807e/ropensci-magick-165cca0'  \
  --library='/Users/neuwirth/Library/R/3.4/library' --install-tests 

* installing *source* package ‘magick’ ...
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick@6/6.9.9-5_1/include/ImageMagick-6
Using PKG_LIBS=-L/usr/local/Cellar/imagemagick@6/6.9.9-5_1/lib -lMagick++-6.Q16 -lMagickWand-6.Q16 -lMagickCore-6.Q16
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because Magick++ was not found. Try installing:
 - deb: 'libmagick++-dev' (Debian, Ubuntu)
 - rpm: 'ImageMagick-c++-devel' (Fedora, CentOS, RHEL)
 - csw: 'imagemagick_dev' (Solaris)
On MacOS it is recommended to use homebrew and install ImageMagick-6:
   brew remove imagemagick
   brew reinstall imagemagick@6 --with-fontconfig --with-librsvg
These features are required for high quality font/svg rendering.
If Magick++ is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a Magick++.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘magick’
* removing ‘/Users/neuwirth/Library/R/3.4/library/magick’
Installation failed: Command failed (1)
```

**Comment by jeroen** [comment]
Why are you changing the `PATH`? The install should work out of the box but if anything you should set `PKG_CONFIG_PATH`. Can you try to install without that?

If that does not work try:

```
brew link --force imagemagick@6
```

**Comment by neuwirthe** [comment]
That was a copy-paste error.
I also tried changin the PATH when it did not work.
And PKG_CONFOG_PATH was set anyhow.
I did it again, with

```
Sys.setenv(PKG_CONFIG_PATH="/usr/local/Cellar/imagemagick@6/6.9.9-5_1/lib/pkgconfig")
devtools::install_github("ropensci/magick")
```

and got the same error

This is what I now did in a clean session

```
Sys.setenv(PKG_CONFIG_PATH="/usr/local/Cellar/imagemagick@6/6.9.9-5_1/lib/pkgconfig")
Sys.getenv("PKG_CONFIG_PATH")
devtools::install_github("ropensci/magick")
```

and  this is what happened

```
> source('~/CloudStation/WahlParallel/install_magick.R', echo=TRUE)

> Sys.setenv(PKG_CONFIG_PATH="/usr/local/Cellar/imagemagick@6/6.9.9-5_1/lib/pkgconfig")

> Sys.getenv("PKG_CONFIG_PATH")
[1] "/usr/local/Cellar/imagemagick@6/6.9.9-5_1/lib/pkgconfig"

> devtools::install_github("ropensci/magick")
Downloading GitHub repo ropensci/magick@master
from URL https://api.github.com/repos/ropensci/magick/zipball/master
Installing magick
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/zf/y3v1wp1n6yg4yyd68s0770xc0000gn/T/RtmpffdryR/devtools49ab12703df6/ropensci-magick-165cca0'  \
  --library='/Users/neuwirth/Library/R/3.4/library' --install-tests 

* installing *source* package ‘magick’ ...
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick@6/6.9.9-5_1/include/ImageMagick-6
Using PKG_LIBS=-L/usr/local/Cellar/imagemagick@6/6.9.9-5_1/lib -lMagick++-6.Q16 -lMagickWand-6.Q16 -lMagickCore-6.Q16
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because Magick++ was not found. Try installing:
 - deb: 'libmagick++-dev' (Debian, Ubuntu)
 - rpm: 'ImageMagick-c++-devel' (Fedora, CentOS, RHEL)
 - csw: 'imagemagick_dev' (Solaris)
On MacOS it is recommended to use homebrew and install ImageMagick-6:
   brew remove imagemagick
   brew reinstall imagemagick@6 --with-fontconfig --with-librsvg
These features are required for high quality font/svg rendering.
If Magick++ is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a Magick++.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘magick’
* removing ‘/Users/neuwirth/Library/R/3.4/library/magick’
Installation failed: Command failed (1)
```

**Comment by jeroen** [comment]
That's odd. We can run through the configure script to see why it is failing. Can you run the lines below in a terminal window?

```
R_HOME=$(R RHOME)
PKG_CFLAGS=$(pkg-config --cflags Magick++)
PKG_LIBS=$(pkg-config --libs Magick++)
CXXCPP=$(${R_HOME}/bin/R CMD config CXXCPP)
CXXFLAGS=$(${R_HOME}/bin/R CMD config CXXFLAGS)
CPPFLAGS=$(${R_HOME}/bin/R CMD config CPPFLAGS)

PKG_TEST_HEADER="<Magick++.h>"
echo "#include $PKG_TEST_HEADER" | ${CXXCPP} ${CPPFLAGS} ${PKG_CFLAGS} ${CXXFLAGS} -xc++ - > /dev/null
```

**Comment by neuwirthe** [comment]
Mozart:Downloads neuwirth$ R_HOME=$(R RHOME)
Mozart:Downloads neuwirth$ PKG_CFLAGS=$(pkg-config --cflags Magick++)
Mozart:Downloads neuwirth$ PKG_LIBS=$(pkg-config --libs Magick++)
Mozart:Downloads neuwirth$ CXXCPP=$(${R_HOME}/bin/R CMD config CXXCPP)
Mozart:Downloads neuwirth$ CXXFLAGS=$(${R_HOME}/bin/R CMD config CXXFLAGS)
Mozart:Downloads neuwirth$ CPPFLAGS=$(${R_HOME}/bin/R CMD config CPPFLAGS)
Mozart:Downloads neuwirth$
Mozart:Downloads neuwirth$ PKG_TEST_HEADER="<Magick++.h>"
Mozart:Downloads neuwirth$ echo "#include $PKG_TEST_HEADER" | ${CXXCPP} ${CPPFLAGS} ${PKG_CFLAGS} ${CXXFLAGS} -xc++ - > /dev/null
In file included from <stdin>:1:
In file included from /usr/local/Cellar/imagemagick@6/6.9.9-5_1/include/ImageMagick-6/Magick++.h:10:
In file included from /usr/local/Cellar/imagemagick@6/6.9.9-5_1/include/ImageMagick-6/Magick++/Include.h:23:
/usr/local/clang4/bin/../include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h'
      file not found
#include_next <stdio.h>
              ^~~~~~~~~
1 error generated.

**Comment by jeroen** [comment]
The problem is that you have a conflicting libcxx in `/usr/local/clang4/`. Try removing this.

**Comment by jeroen** [comment]
The problem is that `imagemagick` is conflicting with the libc++ library that you have installed in `/usr/local/clang4/`. Did you install a custom compiler?

**Comment by neuwirthe** [comment]
It seems installing imagemagick@6 is the problem.
I did
brew install imagemagick

brew install imagemagick
and then I could compile magick

(in fact, I needed /usr/local/clang4!)

and then I did
brew reinstall imagemagick --with-fontconfig --with-librsvg

and things worked again

**Comment by jeroen** [comment]
Where did you get `/usr/bin/clang4`? Is that the CRAN compiler?

**Comment by neuwirthe** [comment]
I think that is just the command line tools from Apple XCode.

Mozart:bin neuwirth$ pwd
/usr/local/clang4/bin
Mozart:bin neuwirth$ ./clang --version
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /usr/local/clang4/bin/.

**Comment by jeroen** [comment]
No it's not. Under unix everything under `/usr/local/` is always manually installed. Stuff installed by the operating system or package manager is in `/usr/bin` or `/usr/lib`, etc.

xcode clang on osx is in `/usr/bin/clang` and `/usr/bin/clang++`. Whatever you have in `/usr/local` (probably the CRAN compiler) is conflicting with homebrew.

Unless you really need a custom compiler, I highly recommend you try to stick with xcode compilers which will work with both R and homebrew.

**Comment by jeroen** [comment]
What I don't understand is how R picks up on `/usr/local/clang4/bin` because this is normally not in the `PATH`. Did you manually change the PATH or Makevars to use this compiler?

**Comment by neuwirthe** [comment]
IIRC I got it from here:

http://r.research.att.com/libs/clang-4.0.0-darwin15.6-Release.tar.gz

**Comment by jeroen** [comment]
Right but if you just put those files in `/usr/local/clang4` R won't find them. Did you modify `~/.R/Makevars ` or so to make R use that compiler?

**Comment by neuwirthe** [comment]
Your are right,
thats what I did,

**Comment by jeroen** [comment]
OK so I recommend you remove or comment out the lines in `~/.R/Makevars` that refer `/usr/local/clang4` so that R just uses clang from xcode. That will probably resolve this and many other problems :)
