### ISSUE TITLE
Add comment to image

### ISSUE THREAD

**Issue by richfitz** [ropensci/magick#68]
I might be missing something, but is it possible to use magick to add a comment to images, like so:

http://www.imagemagick.org/discourse-server/viewtopic.php?t=20183

The use case is embedding information about the provenance of an image into the image itself.

**Comment by jeroen** [comment]
Thank you for the suggestion. Added this in https://github.com/ropensci/magick/commit/08f34da311e0851939a49cfdd1104ef2d52ce05f. Please LMK if this works for you,

**Comment by richfitz** [comment]
Wowzers, that was fast.  I'll give this a try hopefully tomorrow and let you know how it goes

**Comment by richfitz** [comment]
Thanks; this is great:

```r
filename <- "myplot.png"
filename_mod <- "myplot2.png"
png(filename)
plot(1:10)
dev.off()

img <- magick::image_read(filename)
magick::image_write(img, filename_mod, comment = "hello world")
```

However, the only way I can see of getting the comment back *out* is to use `identify` on the command line as

```
$ identify -verbose myplot2.png | grep Comment
    Comment: hello world
```

Is it possible to add some way of querying to `magic::image_info`, or some other function?

**Comment by jeroen** [comment]
OK in that case maybe it's easier if we make a special `image_comment()` function? Can you test https://github.com/ropensci/magick/commit/d7686a223d24e3b86e7b01035ea2e4dc4046c7cd?

**Comment by richfitz** [comment]
This is perfect thanks

**Comment by richfitz** [comment]
One potential issue: this, on some platforms at least, converts white to transparent (excuse the hacky travis shenanigans): https://travis-ci.org/vimc/orderly/jobs/265204948#L988-L993

I don't see this on my desktop computer, or in a docker container built with this dockerfile: https://github.com/vimc/orderly/blob/master/docker/Dockerfile but I do see it on travis.  I can file this to a separate issue if that would be easier.

I suspect that the issue is more the roundtrip than anything.  Or is there some way to stop imagemagic doing any re-encoding of the image data on save?

**Comment by jeroen** [comment]
I don't think so. Afaik, IM always reads the image into an internal raster format, so there will always be some recoding. I'm surprised though it doesn't roundtrip properly. Are you saving it to the same format?

You can always use `image_background(img, "white")` to force a white background color.

If you *just* want to change some medatdata you might just be able to do that with libjpeg or so.

**Comment by jeroen** [comment]
I think exactly that is stated in the last reply in the forum post that you linked above.
