### ISSUE TITLE
RStudio bug to detect image NULL pointer

### ISSUE THREAD

**Issue by jeroen** [ropensci/magick#70]
Saved images in the workspace turn into external NULL ptrs when R is restarted.  However RStudio seems to think these are not NULL and calls the `length()` method which raises an error.

The problem is [this line](https://github.com/rstudio/rstudio/blob/3bd734f3a4cf995a5a8d0cc3686ff28557a9e3cb/src/cpp/session/modules/SessionEnvironment.R#L660) in rstudio which does work because our `externalptr` object has a custom class and print method.

```r
# Create image
logo <- magick::image_read("logo:")

# This image is a null pointer
logo2 <- unserialize(serialize(logo, NULL))

# However this is FALSE
as.environment('tools:rstudio')$.rs.hasNullExternalPointer(logo2)
```

The best solution would be for RStudio to do this in C or C++ something like:

```c
bool is_null_ptr(SEXP obj){
  return TYPEOF(obj) == EXTPTRSXP && R_ExternalPtrAddr(ptr) == NULL;
}
```

@jmcphers @kevinushey @jjallaire

**Comment by jmcphers** [comment]
Thanks, we've got an issue tracking this on our end now (we'll update when we have a fix).

**Comment by kevinushey** [comment]
This also seems like a buglet in R to me:

```R
library(magick)

# Create image
logo <- magick::image_read("logo:")

# This image is a null pointer
logo2 <- unserialize(serialize(logo, NULL))

# we can confirm the type
typeof(logo2)

# but inherits disagrees ...
inherits(logo2, "externalptr")

# ... unless you explicitly drop the class
class(logo2) <- NULL
inherits(logo2, "externalptr")
```

IMO `inherits()` should still report that this object is an `externalptr` -- what do you think, @jeroen?

**Comment by kevinushey** [comment]
I guess this isn't an R bug since similar semantics hold for other R objects:

```R
inherits(list(), "list")         # TRUE
inherits(data.frame(), "list")   # FALSE
```

**Comment by kevinushey** [comment]
Thanks, that's right. My confusion arose because, for _unclassed_ R objects, `inherits()` checks the actual underlying type, whereas for _classed_ R objects it does not.

**Comment by jeroen** [comment]
Right but for some reason R doesn't let you `unclass()` an `externalptr` I think.

**Comment by kevinushey** [comment]
Yep. Either way, I have a PR up for RStudio that now uses `typeof()`, so this should be properly handled in the next builds (after that's merged)

**Comment by jeroen** [comment]
OK I think that will solve it. If I may ask, why are you not checking the actual pointer in C instead of doing `capture.output(base::print.default(obj)) == "<pointer: 0x0>"` ?

**Comment by kevinushey** [comment]
Just because that was simpler to implement at the time -- I'll look into adding that.

**Comment by jeroen** [comment]
Thanks!

**Comment by cboettig** [comment]
@kevinushey @jeroen did you find a better way to do this than:
`capture.output(base::print.default(obj)) == "<pointer: 0x0>"`

**Comment by kevinushey** [comment]
I don't think there's a better base-R solution because (to the best of my knowledge) there's no way (with plain R code) to extract the underlying address from an external pointer :(

If you can use the C API then `R_ExternalPtrAddr()` gives you what you need.

**Comment by cboettig** [comment]
@kevinushey thanks! then I'll happily steal your solution so I have a simple base R check I can run, (in my case the null pointer comes from another package so I'm not handling the C API)
