### ISSUE TITLE
RGB color space not permitted on grayscale PNG

### ISSUE THREAD

**Issue by patperry** [ropensci/magick#74]
I couldn't figure out how to create a blank canvas in `macick`. While trying to come up with a hack for this, I ran into the following bug:

```r
tmp <- tempfile()
png(tmp, width = 480, height = 80, res = 96)
plot(c(0, 1), c(0, 1), type = "n", axes = FALSE, xlab = "", ylab = "")
dev.off()

bg <- image_read(tmp)
image_browse(bg)

Error in magick_image_write(image, format, quality, depth, density, comment) : 
  Magick: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `' @ warning/png.c/MagickPNGWarningHandler/1665
```

**Comment by jeroen** [comment]
Thanks for the bug report. One way to create a blank canvas is using the graphics device;

```
img <- image_graph(width = 800, height = 600, bg = 'white')
plot.new()
dev.off()
print(img)
```

**Comment by jeroen** [comment]
Another way would be to create it yourself from R's raster format:

```r
image_read(matrix("white",80, 480))
```

Or:

```
image_read(matrix(0L, 80, 480))
```

**Comment by jeroen** [comment]
Simple reproducible example:

```r
tmp <- tempfile(fileext = ".png")
png(tmp)
plot(1, col = 'red')
dev.off()

bg <- image_read(tmp)
image_browse(bg)

```

But if we add color to the png it's fine:

```r
tmp <- tempfile(fileext = ".png")
png(tmp)
plot(1, col = 'red')
dev.off()

bg <- image_read(tmp)
image_browse(bg)
```

**Comment by jeroen** [comment]
Upstream issue: https://github.com/ImageMagick/ImageMagick/issues/884

**Comment by jeroen** [comment]
Added a function `image_blank()` to create blank images. Also added a `image_strip()` to remove (faulty) attributes from PNG images.

**Comment by hermelino** [comment]
I'm having the same problem with the following code:

`library(texPreview)
latex_expression = "$$\\frac { 4 x } { \\sqrt { x ^ { 2 } + 1 } }$$"
texPreview(latex_expression)`

> This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6300) entering extended mode
> SyncTeX written on tex_tempDoc.synctex.gz.
> Error in magick_image_write(image, format, quality, depth, density, comment) : 
>   Magick: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `' @ warning/png.c/MagickPNGWarningHandler/1665

What can I do?
