### ISSUE TITLE
fps factor of 100

### ISSUE THREAD

**Issue by 16EAGLE** [ropensci/magick#76]
An error occurs when calling image_animate() with fps > 10 except for 20, 40, etc. Is this intentional?

```s
image_animate(img, fps = 30)

error in image_animate(img, fps = 11) : 
  argument 'fps' must be a factor of 100
```

```s
image_animate(img, fps = 12)

error in image_animate(img, fps = 12) : 
  argument 'fps' must be a factor of 100
```

img contains 200 frames.

Thanks for the great package!

**Comment by jeroen** [comment]
Yes that is intentional. The gif format internally encodes the duration of a frame in 1/100th of a second. So there is now way to represent fps of 11.

**Comment by 16EAGLE** [comment]
Thanks for your reply. I should have known, but was not aware of this.
