### ISSUE TITLE
Add interface to convolve

### ISSUE THREAD

**Issue by thomasp85** [ropensci/magick#77]
While a range of predefined kernel convolutions are available, it would be great to have complete control over the use of `-morphology Convolve` for e.g. better edge detection.

Ref: <http://www.imagemagick.org/Usage/convolve/>

Whether it should all be lumped together in an `image_convolve` function or be split out based on what the different kernels produce I don't know (I err on the side of keeping it in one function)

**Comment by jeroen** [comment]
I don't really know how convolve is used. Can you help me see if the [Image++ API](https://legacy.imagemagick.org/Magick++/Image++.html) might have what you need?

**Comment by jeroen** [comment]
So are these kernels hardcoded arrays or so? The method only allows me to pass a matrix of doubles?

**Comment by thomasp85** [comment]
You know what - let me make a pr for it. It seems rather straightforward and I’ll get some under-the-hood experience with magick

**Comment by thomasp85** [comment]
I think they are enumerated in the cli program

**Comment by thomasp85** [comment]
If you already have working code then just add that of course

**Comment by thomasp85** [comment]
If the function allows any square matrix and magick exports a list of predefined kernels (or constructors) it would allow maximum flexibility

**Comment by jeroen** [comment]
I can solve that part. Let me try something...

**Comment by thomasp85** [comment]
It seems to work - what is the format for the `args` argument?

**Comment by thomasp85** [comment]
I guess it is just whatever is after the kernel name..? Is there any way of adding the scaling and bias functions available in the cli?

**Comment by jeroen** [comment]
Yes I think what you pass on the cli is the `kernel:args`. 

I have added a `scaling` parameter. Can you test this? I'm still trying to find how to do the bias.

**Comment by thomasp85** [comment]
Works like a charm... The way to pass kernel and scaling arguments are a bit... un-R :-) I don't know how this can be approved upon but I will give it some thoughts...

This is already great (and if bias gets added it's ++). If there is a way to manually define kernels as a matrix it would be even better.

**Comment by jeroen** [comment]
@dlemstra I'm having a hard time finding where in the Magick++ api I can set the bias for `Image.morphology()`. Any guess?

**Comment by dlemstra** [comment]
You will need to set the `convolve:bias` artifact on the image. I hide this in the API in Magick.NET: https://github.com/dlemstra/Magick.NET/blob/b385373b3d1ee35c64523696092b41f8de549a7d/Source/Magick.NET/Shared/MagickImage.cs#L4256

**Comment by jeroen** [comment]
@dlemstra thanks! @thomasp85 I have added a `bias` parameter to `image_convolve()`. Can you test this when you have a chance?

**Comment by jeroen** [comment]
@thomasp85 OK we now have support for named kernels and matrix ones. Does this now do everything you need?

**Comment by thomasp85** [comment]
everything seems to be working splendidly - thanks for all your work!

**Comment by jeroen** [comment]
Thanks for the feedback! LMK if you have more ideas for useful features.

**Comment by jeroen** [comment]
Seriously, I'm a noob wrt imaging so hearing what people need is the only way to improve this pkg.

**Comment by thomasp85** [comment]
Ha - that is how I feel about web servers

**Comment by jeroen** [comment]
This is on CRAN now.
