### ISSUE TITLE
Font alias 'monospace' does not work

### ISSUE THREAD

**Issue by smonsays** [ropensci/magick#80]
Currently changing the graphical parameter "family" to "family = mono" has no effect on the graphical device. See the following test case as an example:
 ```
  # Open magick image device
  img <- image_graph(width = 140, height = 40, bg = "white", pointsize = 20,
                     res = 120, clip = TRUE, antialias = TRUE)
  # Set margins to 0
  par(mar = c(0,0,0,0))  
  
  # Initialize plot & print text
  plot(c(0,1), axes = FALSE, main = "", xlab = "", ylab = "", col = "white")
  par(family = "mono", font = 2)  # <---- Setting font family has no effect
  text(0.95, 0.42, "Test", pos = 4)
    
  # Close the magick image device
  dev.off() 
```
EDIT (2017/10/30):
It seems like defining another font family (e.g. family = "courier new") shows the expected behavior. I am not sure, why family = "mono" is not working as expected (it works for other graphical devices on my system).

**Comment by jeroen** [comment]
Probably a fontconfig issue. Can you pls include `sessionInfo()`?

**Comment by jeroen** [comment]
TODO: check https://cran.r-project.org/web/packages/svglite/vignettes/fonts.html

**Comment by smonsays** [comment]
```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS: /usr/lib/libblas.so.3.7.1
LAPACK: /usr/lib/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lme4_1.1-14   Matrix_1.2-11 magick_1.4   

loaded via a namespace (and not attached):
 [1] locfit_1.5-9.1      Rcpp_0.12.13        lattice_0.20-35     fftwtools_0.9-8     png_0.1-7          
 [6] MASS_7.3-47         tiff_0.1-5          grid_3.4.2          nlme_3.1-131        magrittr_1.5       
[11] minqa_1.2.4         nloptr_1.0.4        splines_3.4.2       tools_3.4.2         jpeg_0.1-8         
[16] abind_1.4-5         yaml_2.1.14         compiler_3.4.2      BiocGenerics_0.22.1
```

**Comment by jeroen** [comment]
@lionel- @hadley I'm confused, how does svglite do this? Where does the font `mono` get resolved into `courier` / `courier new`? I thought fontconfig would do this but it doesn't seem so. Should we implement these mappings in the graphics device?

**Comment by lionel-** [comment]
IIRC the family aliases are set up in fontconfig's configuration file. Perhaps your setup is missing `mono`?

**Comment by hadley** [comment]
Don’t we have some standard mapping in svglite?

**Comment by hadley** [comment]
Yeah - https://github.com/r-lib/svglite/blob/master/R/fonts.R

**Comment by smonsays** [comment]
@lionel- Indeed, my setup is missing `mono` (Courier is not installed). However, when using the standard graphical device (i.e. only running commands 2-5 from my original post), Courier is automatically substituted by another mono font (in my case by Nimbus Mono). I think this should be the expected behavior for `magick` as well.
Output from magick:
![rplot-magick](https://user-images.githubusercontent.com/8426567/32415156-75bdce5e-c235-11e7-9753-827d8323280a.png)

Output for standard graphical device:
![rplot-standard](https://user-images.githubusercontent.com/8426567/32415157-77a43e92-c235-11e7-8e48-10c449474df9.png)
