### ISSUE TITLE
Can a pdf be saved as a vectorized image?

### ISSUE THREAD

**Issue by talgalili** [ropensci/magick#81]
(Hi Jeroen )

The following results in an un vectorized image. Can it be saved as a vectorized pdf file?

```
pdf("tmp.pdf")
plot(1:10, pch = 1:10)
dev.off()

library(magick)
tmp_mgk <- image_read("tmp.pdf")
image_write(tmp_mgk, "tmp2.pdf")

```

(thanks)

**Comment by talgalili** [comment]
(update: as far as I can see, this is not possible in IM: http://www.imagemagick.org/Usage/formats/#vector but correct me if I'm wrong)

**Comment by jeroen** [comment]
No I don't think this is possible. Magick manipulates bitmap images, and the `pdf` format is not an image format. If you really need to convert an image to pdf I would recommend wrapping it into a tiny md/tex document and converting that to pdf.

**Comment by talgalili** [comment]
Bummer, thanks Jeroen.
I wonder if there might be some tool that could do this. I could only find pdfcrop, but it seems to be for linux only.

**Comment by jeroen** [comment]
What exactly is it that you need this for then? pdf is a poor format to store images...

**Comment by talgalili** [comment]
Because of this:
https://github.com/ropensci/plotly/issues/1143
I want to export a plotly output into something vectorized. The svg option doesn't work and the pdf option gives me the figure inside an A4 page size :\
