### ISSUE TITLE
Provide geometry helper

### ISSUE THREAD

**Issue by hadley** [ropensci/magick#82]
e.g.

```
geometry(300, 500) 
geometry(300, 500, preserve_aspect = FALSE)
geometry(w = 300)
geometry(h = 500)
geometry("50%", "30%") 
geometry("500", "300", x = 10, y = 20)
```

Would also be handy to have something that generates a geometry from an existing image, since it's not common to want to resize images to match a template.

**Comment by jeroen** [comment]
This has landed in magick 1.6 on CRAN. Thank you for the suggestion.

<img width="706" alt="screen shot 2017-12-03 at 2 03 39 pm" src="https://user-images.githubusercontent.com/216319/33525592-1aa4cf36-d833-11e7-964f-0ba53eccd182.png">
