### ISSUE TITLE
[vignette]

### ISSUE THREAD

**Issue by sobradob** [ropensci/magick#84]
Hi, thanks a lot for the work!

The combining example seems to be broken. This is what it looked like in July:
![image](https://user-images.githubusercontent.com/10224192/32783545-20176f74-c987-11e7-80c8-2a42c14d797a.png)

This is what it looks like now. 
![image](https://user-images.githubusercontent.com/10224192/32783565-3114c65a-c987-11e7-8fd1-8c93e341cc52.png)

I tried replicating the original and I'm afraid I get the same results as in the vignette.

**Comment by jeroen** [comment]
Hmm thanks for letting me know. I'll look into it.
