### ISSUE TITLE
Can we link the current 'magick' package release with the newer version of Image Magick?

### ISSUE THREAD

**Issue by adwiputra** [ropensci/magick#85]
The current package installed from cran automatically link with ImageMagick 6.9.9.14 which doesn't support the fontconfig features. I would like to link the package with newer updates which does support such functionality to specify font in text annotation. Is it possible?

Thanks.
Adrian

**Comment by jeroen** [comment]
The version is only fixed on Windows. On linux/mac the package will use whatever imagemagick version you have installed on your system.

I don't understand which fontconfig features you are talking about.

**Comment by adwiputra** [comment]
I see.. The 'fontconfig' I refer to is the feature which enables the user to modify the font style. At least that's what I inferred from the vignette:
![image](https://user-images.githubusercontent.com/14678187/32923890-89596b54-cb6c-11e7-991a-e09acecd015f.png)
However, when I loaded the library 'magick', I get the message below:
![image](https://user-images.githubusercontent.com/14678187/32923970-0079415a-cb6d-11e7-9783-89358236c44d.png)

Nice package btw.

**Comment by jeroen** [comment]
Fontconfig is a library for linux/mac to lookup fonts. Windows has another system for finding fonts.
