### ISSUE TITLE
image_charcoal() crashes R

### ISSUE THREAD

**Issue by clauswilke** [ropensci/magick#86]
After upgrading R from 3.4.1 to 3.4.2 and upgrading magick accordingly, `image_charcoal()` crashes R.

Reproducible example:
```
# this part works
img <- magick::image_read("http://jeroen.github.io/images/tiger.svg")
grid::rasterGrob(img)

# now the part that used to work but doesn't anymore
img <- magick::image_charcoal(img) # all is good so far
grid::rasterGrob(img) # crash
```

Traceback:
```
 *** caught segfault ***
address 0x10c7ab003, cause 'memory not mapped'

Traceback:
 1: .Call("_magick_magick_image_as_raster", PACKAGE = "magick", data)
 2: magick_image_as_raster(image[[1]])
 3: `as.raster.magick-image`(image)
 4: as.raster(image)
 5: grid::rasterGrob(img)
```

As far as I can tell, the issue is specific to `image_charcoal()` and doesn't happen with other image manipulation functions. (I didn't check all of them, though.)

**Comment by jeroen** [comment]
I modified `as.raster()` a bit. Can you check if this still happens with the dev version of magick?

**Comment by clauswilke** [comment]
Yes, this seems to have solved the issue.
