### ISSUE TITLE
print() printing image_info in Jupyter Notebook

### ISSUE THREAD

**Issue by amrrs** [ropensci/magick#98]
Hi, 

Unlike Rstudio that displays the image when using `print()`, Jupyter Notebook just prints the image_info. 
But `plot()` displays the image (so that's not a problem). Is there any other right way of doing this?

Thanks!

**Comment by jeroen** [comment]
Thanks for the suggestion, I will look into it. The `IRdisplay` package has a `display_png` function that we may be able to call from magick.

**Comment by amrrs** [comment]
Thanks, Displaying gif is also a problem - that's a Jupyter problem I guess, just highlighting though!

**Comment by jeroen** [comment]
This should now work in the dev version. Can you pls test?

```r
devtools::install_github("ropensci/magick")
```
