### ISSUE TITLE
Using lapply with image_crop not working

### ISSUE THREAD

**Issue by richardneilbelcher** [ropensci/magick#99]
For example, using: lapply croppedimage <- lapply(rawimage, image_crop("1510x1130+250+185"))
Give me the error "Error: The 'image' argument is not a magick image object."
However it works when reading in the "raw" PNG files.

**Comment by jeroen** [comment]
What is `rawimage`? If it is an image you just need `image_crop(image, "1510x1130+250+185")`

**Comment by richardneilbelcher** [comment]
Hi Jeroen,

It is a list of magick image objects. I created it by:

#getting a list of png image files
filenames <- list.files()#enter file path here

#reading them in as a list of magick objects
rawimage <- lapply(filenames, image_read)

**Comment by jeroen** [comment]
Perhaps you mean `lapply(rawimage, image_crop, "1510x1130+250+185")` ? The first argument of `image_crop` must be the image, therefore you get the error.

Also note that magick is vectorized so you can also do:
```r
image_crop(image_read(filenames),"1510x1130+250+185")
```

**Comment by richardneilbelcher** [comment]
Thanks Jeroen, that works!
